import {icons} from './icons.js';
import {boot,context,rpc,escapeHTML as esc,exportCSV,applyTheme} from '/restaurant/shared.js?v=20260914-1';
import {names,number,currency,share,delta,periodDates,previousDates,normalise,weekdayOrders} from './data.js';
import {renderExpansion} from './expansion.js';
const titles={overview:'التحليلات',revenue:'تفاصيل الإيرادات','order-sources':'مصادر الطلبات',drivers:'أداء المندوبين',categories:'أفضل الفئات أداءً','peak-hours':'ساعات الذروة',kitchen:'أداء المطبخ',customers:'رؤى العملاء',insights:'رؤى ذكية',products:'أداء الأصناف','order-types':'أنواع الطلبات','order-status':'حالة الطلبات'};
const routes={overview:'/analytics',revenue:'/analytics/revenue','order-sources':'/analytics/order-sources',drivers:'/analytics/drivers',categories:'/analytics/categories','peak-hours':'/analytics/peak-hours',kitchen:'/analytics/kitchen',customers:'/analytics/customers',insights:'/analytics/insights',products:'/analytics/products','order-types':'/analytics/order-types','order-status':'/analytics/order-status'};
const expansionPages=new Set(['kitchen','customers','insights','products','order-types','order-status']);
const legacy={sources:'order-sources',hours:'peak-hours'};
const params=new URLSearchParams(location.search),old=params.get('section'),segment=location.pathname.split('/').filter(Boolean)[1];
const page=titles[segment]?segment:titles[legacy[old]||old]?legacy[old]||old:'overview';
document.title='CARDfy — '+titles[page];
let template,data,comparison=null,exportRows=[],expansionDetails={},request=0,applied;
const $=s=>document.querySelector(s),today=new Date().toLocaleDateString('en-CA',{timeZone:'Africa/Cairo'});
const url=id=>{const q=new URLSearchParams();if(context.role!=='owner')q.set('as','staff');if(applied){q.set('from',applied.from);q.set('to',applied.to);if(applied.branch)q.set('branch',applied.branch);}return routes[id]+(q.size?'?'+q.toString():'');};
const icon=(name='chart-no-axes-combined')=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${(icons[name]||icons["chart-no-axes-combined"]).map(([tag,attrs])=>`<${tag} ${Object.entries(attrs).map(([k,v])=>`${k}="${v}"`).join(" ")}/>`).join("")}</svg>`;
const empty=(message='لا توجد بيانات لهذه الفترة.')=>`<p class="analytics-empty">${esc(message)}</p>`;
const unknown=message=>empty(message||'غير متاح: لا يسجل النظام هذا المؤشر حاليًا.');
function table(headers,rows){return `<div class="analytics-table-wrap"><table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${r.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${headers.length}">لا توجد بيانات لهذه الفترة.</td></tr>`}</tbody></table></div>`;}
const colours=['#f97316','#3b82f6','#10b981','#fbbf24','#a855f7','#06b6d4'];
function donut(rows,key='orders',unit='طلب'){const total=rows.reduce((s,r)=>s+(Number(r[key])||0),0);if(!total)return empty();let offset=0;return `<div class="analytics-donut"><svg viewBox="0 0 200 200" role="img" aria-label="توزيع ${esc(unit)}"><circle cx="100" cy="100" r="74" fill="none" stroke="#1e2b3a" stroke-width="25"/>${rows.map((r,i)=>{const length=share(r[key],total)*4.65,result=`<circle cx="100" cy="100" r="74" fill="none" stroke="${colours[i%6]}" stroke-width="25" stroke-dasharray="${length} 465" stroke-dashoffset="${-offset}" transform="rotate(-90 100 100)"/>`;offset+=length;return result;}).join('')}<text x="100" y="97" text-anchor="middle" fill="currentColor" font-size="24" font-weight="800">${esc(number(total))}</text><text x="100" y="122" text-anchor="middle" fill="#94a3b8" font-size="12">${esc(unit)}</text></svg><div>${rows.map((r,i)=>`<p><span style="color:${colours[i%6]}">●</span> ${esc(names[r.label]||r.label)} <b>${esc(number(share(r[key],total)))}%</b> <small>(${esc(number(r[key]))})</small></p>`).join('')}</div></div>`;}
function bars(rows,key='value'){if(!rows.some(r=>Number(r[key])>0))return empty();const max=Math.max(...rows.map(r=>Number(r[key])||0),1);return `<div class="analytics-bars" role="img" aria-label="مقارنة القيم">${rows.map((r,i)=>`<div><span>${esc(number(r[key]))}</span><div class="analytics-bar-track"><div style="height:${Math.max(0,Number(r[key])||0)/max*100}%;background:${colours[i%6]}"></div></div><small>${esc(names[r.label]||r.label)}</small></div>`).join('')}</div>`;}
function line(rows,key='value'){if(!rows.length||!rows.some(r=>Number(r[key])>0))return empty();const max=Math.max(...rows.map(r=>Number(r[key])||0),1),points=rows.map((r,i)=>[35+i*330/Math.max(rows.length-1,1),200-(Number(r[key])||0)/max*165]);return `<svg class="analytics-line" viewBox="0 0 400 250" role="img" aria-label="اتجاه القيم خلال الفترة">${[0,1,2,3].map(i=>`<line x1="35" y1="${200-i*55}" x2="375" y2="${200-i*55}" stroke="#233245" stroke-dasharray="3 3"/><text x="25" y="${204-i*55}" fill="#64748b" text-anchor="end" font-size="10">${esc(number(max*i/3))}</text>`).join('')}<path d="M ${points.map(p=>p.join(' ')).join(' L ')} L 365 200 L 35 200 Z" fill="#f97316" opacity=".12"/><polyline points="${points.map(p=>p.join(',')).join(' ')}" fill="none" stroke="#f97316" stroke-width="3"/>${points.map((p,i)=>`<circle cx="${p[0]}" cy="${p[1]}" r="3" fill="#f97316"><title>${esc(rows[i].label)}: ${esc(number(rows[i][key]))}</title></circle>`).join('')}${rows.filter((_,i)=>i%Math.max(1,Math.ceil(rows.length/6))===0).map(r=>`<text x="${points[rows.indexOf(r)][0]}" y="225" fill="#94a3b8" text-anchor="middle" font-size="10">${esc(r.label)}</text>`).join('')}</svg>`;}
function metric(label,value,key,format=number){const change=key?delta(value,comparison?.summary[key]):null;return `<article class="${esc(template.cardClass)} analytics-metric"><div><span class="analytics-muted">${esc(label)}</span><strong dir="auto">${esc(format(value))}</strong><small class="${change==null?'analytics-muted':change>=0?'analytics-success':'analytics-danger'}">${change==null?'المقارنة غير متاحة':esc(number(Math.abs(change)))+'% '+(change>=0?'↑':'↓')+' مقارنة بالفترة السابقة'}</small></div><span class="analytics-icon">${icon(key==='revenue'?'wallet':'chart-no-axes-combined')}</span></article>`;}
function sourceTrend(rows){if(!rows.length)return empty();const days=[...new Set(rows.map(r=>r.day))].sort(),sources=[...new Set(rows.map(r=>r.source))],max=Math.max(...rows.map(r=>Number(r.orders)||0),1);return `<svg class="analytics-line" viewBox="0 0 400 250" role="img" aria-label="اتجاه الطلبات لكل مصدر">${[0,1,2,3].map(i=>`<line x1="35" y1="${200-i*55}" x2="375" y2="${200-i*55}" stroke="#233245"/>`).join('')}${sources.map((source,i)=>{const points=days.map((day,j)=>[35+j*330/Math.max(days.length-1,1),200-(Number(rows.find(r=>r.day===day&&r.source===source)?.orders)||0)/max*165]);return `<polyline points="${points.map(p=>p.join(',')).join(' ')}" fill="none" stroke="${colours[i%6]}" stroke-width="3"><title>${esc(names[source]||source)}</title></polyline>`;}).join('')}${days.filter((_,i)=>i%Math.max(1,Math.ceil(days.length/5))===0).map(day=>`<text x="${35+days.indexOf(day)*330/Math.max(days.length-1,1)}" y="225" text-anchor="middle" fill="#94a3b8" font-size="10">${esc(day)}</text>`).join('')}</svg><div class="analytics-legend">${sources.map((s,i)=>`<span><i style="color:${colours[i%6]}">●</i> ${esc(names[s]||s)}</span>`).join('')}</div>`;}
function metrics(){const s=data.summary,peak=[...data.hours].sort((a,b)=>b.value-a.value)[0],top=data.categories[0],source=[...data.sources].sort((a,b)=>b.orders-a.orders)[0];
 let m=[['مبيعات اليوم',s.revenue,'revenue',currency],['إجمالي الطلبات',s.orders,'orders'],['متوسط قيمة الطلب',s.average_order,'average_order',currency],['طلبات مكتملة',s.completed,'completed'],['طلبات ملغاة',s.cancelled,'cancelled'],['متوسط وقت التحضير',s.preparation_minutes,'preparation_minutes'],['متوسط وقت التوصيل',s.delivery_minutes,'delivery_minutes'],['مندوبين نشطين',s.active_drivers],['تقييم العملاء',s.rating,'rating']];
 if(page==='revenue')m=[['إجمالي الإيرادات المدفوعة',s.revenue,'revenue',currency],['عدد الطلبات',s.orders,'orders'],['متوسط الطلب المدفوع',s.average_order,'average_order',currency],['صافي التحصيل',null]];
 if(page==='order-sources')m=[['إجمالي الطلبات',s.orders,'orders'],['أكثر مصدر طلبات',source?.label,null,v=>names[v]||v||'لا توجد بيانات'],['معدل التحويل الإجمالي',null],['مساهمة المصادر في الإيرادات',s.revenue,'revenue',currency]];
 if(page==='categories')m=[['أفضل فئة أداء',top?.label,null,v=>v||'لا توجد بيانات'],['إيرادات الفئة',top?.value,null,currency],['الوحدات المباعة للفئة',top?.quantity],['معدل النمو',top?delta(top.value,comparison?.categories.find(c=>c.label===top.label)?.value):null,null,v=>v==null?'غير متاح':number(v)+'%']];
 if(page==='drivers')m=[['مندوبين نشطين الآن',s.active_drivers],['طلبات تم توصيلها',data.drivers.reduce((n,r)=>n+Number(r.delivered),0)],['متوسط وقت التوصيل',s.delivery_minutes,'delivery_minutes'],['متوسط العودة للمطعم',null],['مشاكل مفتوحة',data.drivers.reduce((n,r)=>n+Number(r.issues),0)]];
 if(page==='peak-hours')m=[['أكثر ساعة ازدحامًا',peak?.value?peak.label:null,null,v=>v==null?'لا توجد بيانات':number(v)+':00'],['طلبات ساعة الذروة',peak?.value],['إجمالي الطلبات',s.orders,'orders'],['وقت التحضير في الذروة',peak?.preparation_minutes]];
 return `<section class="${esc(template.kpiClass)}">${m.map(x=>metric(...x)).join('')}</section>`;}
function panelBody(title){const d=data,s=d.summary;
 if(title.includes('عبر الزمن'))return d.source_days.length?sourceTrend(d.source_days):unknown('اتجاه المصادر غير متاح في إصدار البيانات الحالي.');
 if(title==='المبيعات'||title.includes('على مدار'))return line(applied.from===applied.to?d.hours.map(r=>({...r,label:r.label+':00',value:r.revenue})):d.days);
 if(title.includes('حسب طريقة الدفع')||title.includes('رؤى العملاء'))return donut(d.payments,'value','EGP')+`<p class="analytics-muted">تقييم العملاء: ${esc(number(s.rating))}. تكرار العملاء غير مسجل في التحليلات الحالية.</p>`;
 if(title.includes('الإيرادات حسب مصدر'))return bars(d.sources);
 if(title.includes('توزيع الطلبات حسب المصدر')||title==='مصادر الطلبات')return donut(d.sources);
 if(title==='أنواع الطلبات')return donut(d.types);
 if(title==='حالة الطلبات')return donut(d.statuses,'value');
 if(title.includes('حسب ساعات')||title==='ساعات الذروة')return `<div class="analytics-heatmap">${d.hours.map(r=>`<button data-detail="hour:${r.label}" title="${r.label}:00 — ${number(r.value)} طلب" style="background:rgba(249,115,22,${r.value?Math.max(.18,r.value/Math.max(...d.hours.map(x=>x.value),1)):.03})">${number(r.label)}<b>${number(r.value)}</b></button>`).join('')}</div>`;
 if(title.includes('أيام الأسبوع'))return bars(weekdayOrders(d.days));
 if(title.includes('توزيع الطلبات حسب الفئة'))return donut(d.categories,'quantity','وحدة');
 if(title.includes('إيرادات الفئات')||title.includes('أفضل الفئات'))return bars(d.categories);
 if(title.includes('أكثر الأصناف'))return d.products.length?bars(d.products,'quantity'):unknown('ترتيب الأصناف غير متاح في إصدار البيانات الحالي.');
 if(title.includes('عدد الطلبات التي'))return line(d.driver_days.map(x=>({label:x.day,value:x.delivered})));
 if(title.includes('متوسط وقت التوصيل'))return bars(d.drivers.filter(r=>r.duration!=null).map(r=>({label:r.name,value:r.duration})));
 if(title.includes('حالة التوصيل الكلية'))return donut([{label:'تم التوصيل',value:d.drivers.reduce((n,r)=>n+Number(r.delivered),0)},{label:'طلبات أخرى مسندة',value:d.drivers.reduce((n,r)=>n+Math.max(0,r.handled-r.delivered),0)}],'value');
 if(title.includes('أداء المندوبين'))return table(['المندوب','المسند','المسلّم','الدقائق'],d.drivers.slice(0,5).map(r=>[r.name,r.handled,r.delivered,number(r.duration)]));
 if(title.includes('أداء المطبخ'))return metric('متوسط التحضير بالدقائق',s.preparation_minutes,'preparation_minutes')+unknown('تحليل خطوط الإنتاج والتأخير غير متاح دون أحداث تشغيل مسجلة.');
 if(title.includes('رؤى ذكية')){const peak=[...d.hours].sort((a,b)=>b.value-a.value)[0];return peak.value?`<p>أعلى عدد طلبات: ${esc(number(peak.value))} في الساعة ${esc(number(peak.label))}:00.</p><p class="analytics-muted">معلومة محسوبة من الطلبات المسجلة؛ لا توجد توصيات تقديرية.</p>`:empty();}
 return empty();}
function target(title){if(title.includes('مصدر')||title.includes('مصادر'))return 'order-sources';if(title.includes('مندوب')||title.includes('توصيل'))return 'drivers';if(title.includes('فئة')||title.includes('فئات'))return 'categories';if(title.includes('ساع')||title.includes('ذروة'))return 'peak-hours';if(title.includes('مطبخ'))return 'kitchen';if(title.includes('رؤى العملاء'))return 'customers';if(title.includes('رؤى ذكية'))return 'insights';if(title.includes('أكثر الأصناف'))return 'products';if(title.includes('أنواع الطلبات'))return 'order-types';if(title.includes('حالة الطلبات'))return 'order-status';if(title.includes('مبيعات')||title.includes('إيرادات'))return 'revenue';return null;}
function charts(){return template.rows.map(row=>`<section class="${esc(row.classes)}">${row.titles.map(title=>{const p=template.panels.find(p=>p.title===title),id=target(title);return `<article class="${esc(p.classes)} analytics-panel"><div class="analytics-panel-title"><h2>${esc(title)}</h2>${id&&id!==page?`<a href="${url(id)}">عرض الكل</a>`:`<button data-detail="${esc(title)}">عرض التفاصيل</button>`}</div>${panelBody(title)}</article>`;}).join('')}</section>`).join('');}
function renderSections(){$('#analyticsSections').innerHTML=Object.entries(titles).map(([id,title])=>`<a href="${url(id)}" ${id===page?'aria-current="page"':''}>${esc(title)}</a>`).join('');}
function detailTable(){let heads,rows;
 if(page==='revenue'){heads=['التاريخ','عدد الطلبات','الإيرادات المدفوعة','متوسط الطلب المدفوع'];rows=data.days.map(r=>[r.label,r.orders,currency(r.value),r.paid_orders!=null?currency(r.paid_orders?r.value/r.paid_orders:0):'غير متاح لكل يوم']);}
 if(page==='order-sources'){heads=['المصدر','عدد الطلبات','نسبة الطلبات','الإيرادات','متوسط الإيراد لكل طلب'];rows=data.sources.map(r=>[names[r.label]||r.label,r.orders,number(share(r.orders,data.summary.orders))+'%',currency(r.value),currency(r.orders?r.value/r.orders:0)]);}
 if(page==='categories'){heads=['اسم الفئة','الوحدات المباعة','الإيرادات','نسبة إيرادات الفئات'];const total=data.categories.reduce((n,r)=>n+Number(r.value),0);rows=data.categories.map(r=>[r.label,r.quantity,currency(r.value),number(share(r.value,total))+'%']);}
 if(page==='drivers'){heads=['المندوب','طلبات مسندة','تم توصيلها','مشاكل مفتوحة','دقائق التوصيل','الحالة','الرجوع / الشيفت / الاستراحات'];rows=data.drivers.filter(r=>!$('#driverSearch')?.value||r.name.includes($('#driverSearch').value)).map(r=>[r.name,r.handled,r.delivered,r.issues,number(r.duration),names[r.shift_state]||'غير متاح','غير متاح']);}
 if(page==='peak-hours'){heads=['الساعة','عدد الطلبات','الإيرادات المدفوعة','نسبة الطلبات','وقت التحضير'];rows=data.hours.map(r=>[r.label+':00',r.value,currency(r.revenue),number(share(r.value,data.summary.orders))+'%',number(r.preparation_minutes)]);}
 if(!heads)return '';exportRows=[heads,...rows];return `<section class="${esc(template.tableClass)}"><div class="analytics-table-title"><h2>التفاصيل — ${esc(titles[page])}</h2><button id="exportDetails">تصدير CSV</button>${page==='drivers'?'<input id="driverSearch" type="search" aria-label="البحث عن مندوب" placeholder="البحث عن مندوب…">':''}</div><div id="detailRows">${table(heads,rows)}</div></section>`;}
function render(){const main=$('#analyticsMain');if(expansionPages.has(page)){const view=renderExpansion(page,data,comparison,{esc,number,currency,share,delta,empty,donut,bars,line,table,url,titles,icon});main.className='analytics-expansion';main.innerHTML=view.html;exportRows=view.exportRows||[];expansionDetails=view.details||{};}else{main.className=template.mainClass;main.innerHTML=`<div class="analytics-title"><div><p class="analytics-muted"><a href="${url('overview')}">التحليلات</a> / ${esc(titles[page])}</p><h1>${esc(titles[page])}</h1><p class="analytics-muted">بيانات الطلبات المسجلة بتوقيت القاهرة — الإيرادات المدفوعة فقط.</p></div></div>${metrics()}${charts()}${detailTable()}`;}$('#analyticsPeriodLabel').textContent=applied.from+' — '+applied.to;document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>showDetail(b.dataset.detail));$('#exportDetails')?.addEventListener('click',()=>{if(exportRows.length)exportCSV('CARDfy-'+page,exportRows[0],exportRows.slice(1));});$('#driverSearch')?.addEventListener('input',e=>{const query=e.target.value;const host=document.createElement('div');host.innerHTML=detailTable();$('#detailRows').innerHTML=host.querySelector('#detailRows').innerHTML;$('#driverSearch').value=query;});window.lucide?.createIcons();}
function showDetail(title){const dialog=$('#analyticsDetail'),hour=title.startsWith('hour:')?Number(title.split(':')[1]):null;$('#detailTitle').textContent=hour==null?title:hour+':00';let content=expansionPages.has(page)?(expansionDetails[title]||empty()):hour==null?panelBody(title):table(['الساعة','الطلبات','الإيرادات'],data.hours.filter(r=>Number(r.label)===hour).map(r=>[r.label,r.value,currency(r.revenue)]));$('#detailContent').innerHTML=content;dialog.showModal();}
async function loadData(){const from=$('#from').value,to=$('#to').value,branch=$('#branch').value||null;if(!from||!to||from>to)throw new Error('راجع الفترة الزمنية: تاريخ البداية يجب ألا يتجاوز النهاية.');const version=++request;$('#analyticsStatus').textContent='جارٍ تحميل التحليلات…';$('#analyticsMain').setAttribute('aria-busy','true');const p=previousDates(from,to);const [current,prior]=await Promise.allSettled([rpc('cfy_os_analytics',{p_token:context.token,p_from:from,p_to:to,p_branch:branch}),rpc('cfy_os_analytics',{p_token:context.token,p_from:p.from,p_to:p.to,p_branch:branch})]);if(version!==request)return;if(current.status==='rejected')throw current.reason;data=normalise(current.value);comparison=prior.status==='fulfilled'?normalise(prior.value):null;applied={from,to,branch};$('#branch').innerHTML='<option value="">جميع الفروع</option>'+data.branches.map(b=>`<option value="${esc(b.id)}">${esc(b.name)}</option>`).join('');$('#branch').value=branch||'';renderSections();render();$('#analyticsMain').removeAttribute('aria-busy');$('#analyticsStatus').textContent=comparison?'':'تعذر تحميل المقارنة؛ بيانات الفترة الحالية معروضة.';}
async function refresh(){const b=$('#applyFilters');b.disabled=true;try{await loadData();}catch(e){$('#analyticsStatus').textContent=e.message||'تعذر تحميل التحليلات.';$('#analyticsMain').removeAttribute('aria-busy');}finally{b.disabled=false;}}
try{if(await boot('analytics')){if(!expansionPages.has(page))template=await fetch('/analytics/'+page+'.template.json').then(r=>{if(!r.ok)throw Error('تعذر تحميل الواجهة.');return r.json();});const css=document.createElement('link');css.rel='stylesheet';css.href='/analytics/'+(expansionPages.has(page)?'expansion':page)+'.css';document.head.append(css);$('#analyticsSections').innerHTML=Object.entries(titles).map(([id,title])=>`<a href="${url(id)}" ${id===page?'aria-current="page"':''}>${esc(title)}</a>`).join('');$('#period').onchange=()=>{if($('#period').value==='custom')return;const d=periodDates($('#period').value,today);$('#from').value=d.from;$('#to').value=d.to;};$('#from').value=params.get('from')||today;$('#to').value=params.get('to')||today;if(params.has('from')||params.has('to'))$('#period').value='custom';if(params.get('branch')){$('#branch').add(new Option('الفرع المحدد',params.get('branch')));$('#branch').value=params.get('branch');}$('#applyFilters').onclick=refresh;$('#closeDetail').onclick=()=>$('#analyticsDetail').close();$('#osStatus').textContent='';await refresh();}}catch(e){$('#analyticsStatus').textContent=e.message||'تعذر تحميل الصفحة.';}
