const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const {PGlite}=require('@electric-sql/pglite');const {pgcrypto}=require('@electric-sql/pglite/contrib/pgcrypto');
const migration=['20260912130332_restaurant_os_master.sql','20260912183500_restaurant_os_fk_indexes.sql','20260912184500_restaurant_os_compatibility.sql','20260912214500_restaurant_os_trigger_privileges.sql'].map(file=>fs.readFileSync(path.join(__dirname,'..','supabase','migrations',file),'utf8')).join('\n');
const owner='11111111-1111-4111-8111-111111111111';
const baseline=`
create schema if not exists extensions;create extension pgcrypto with schema extensions;create role anon;create role authenticated;
create table cfy_clients(id uuid primary key default gen_random_uuid(),code text unique,whatsapp text default '',active boolean default true,sub_end date,brand_name_ar text default '',brand_name_en text default '');
create table cfy_client_services(client_id uuid references cfy_clients(id),service text,enabled boolean default true);
create table cfy_menu_staff(id uuid primary key default gen_random_uuid(),client_id uuid references cfy_clients(id),code text,name text,role text,pin_hash text,enabled boolean default true,shift_state text default 'offline',updated_at timestamptz default now());
create table cfy_menu_staff_sessions(staff_id uuid,client_id uuid,token_hash text,expires_at timestamptz);
create table cfy_menu_orders(id uuid primary key default gen_random_uuid(),reference text,client_id uuid references cfy_clients(id),order_type text,order_source text,customer_name text,phone text,address text,delivery_zone_id uuid,table_number text,table_id uuid,table_session_id uuid,pickup_time timestamptz,scheduled_for timestamptz,notes text,coupon_code text,products_subtotal numeric default 0,product_discount numeric default 0,coupon_discount numeric default 0,delivery_fee numeric default 0,total numeric default 0,status text default 'new',idempotency_key text,tracking_token_hash text,delivery_otp_hash text,payment_method text default 'cash',payment_status text default 'unpaid',assigned_driver_id uuid,issue_open boolean default false,issue_text text,created_at timestamptz default now(),updated_at timestamptz default now(),accepted_at timestamptz,preparing_at timestamptz,ready_at timestamptz,picked_up_at timestamptz,delivered_at timestamptz,completed_at timestamptz,cancelled_at timestamptz,paid_at timestamptz,rating int,food_quality_rating int,delivery_speed_rating int,packaging_rating int,feedback text);
create table cfy_menu_delivery_zones(id uuid primary key default gen_random_uuid(),client_id uuid references cfy_clients(id),name text,fee numeric default 0,enabled boolean default true);
create table cfy_menu_tables(id uuid primary key default gen_random_uuid(),client_id uuid references cfy_clients(id),label text,enabled boolean default true,sort_order int default 0);
create table cfy_menu_table_sessions(id uuid primary key default gen_random_uuid(),client_id uuid,table_id uuid,status text default 'open',opened_at timestamptz default now(),updated_at timestamptz default now());
create table cfy_menu_order_events(id uuid primary key default gen_random_uuid(),client_id uuid,order_id uuid,event_type text,actor_type text,actor_id uuid,data jsonb default '{}',created_at timestamptz default now());
create table cfy_menu_delivery_assignments(id uuid primary key default gen_random_uuid(),client_id uuid,order_id uuid,driver_id uuid,status text,assigned_at timestamptz default now(),picked_up_at timestamptz,delivered_at timestamptz);
create table cfy_menu_order_items(id uuid primary key default gen_random_uuid(),order_id uuid,product_id uuid,quantity int,unit_price numeric,options_total numeric,discount_amount numeric,line_total numeric,snapshot jsonb default '{}',created_at timestamptz default now());
create table cfy_menu_products(id uuid primary key default gen_random_uuid(),client_id uuid,category_id uuid,name_ar text,name_en text);
create table cfy_menu_categories(id uuid primary key default gen_random_uuid(),client_id uuid,name_ar text,name_en text);
create function cfy_token_client_id(text,text) returns uuid language sql as $$select case when $1='1234567890123456' then '${owner}'::uuid else null end$$;
create function cfy_menu_staff_client_id(text,text) returns uuid language sql as $$select '${owner}'::uuid$$;
create function cfy_menu_public_catalog(text) returns jsonb language sql as $$select '{"settings":{},"categories":[],"products":[],"delivery_zones":[]}'::jsonb$$;
create function cfy_menu_order_payload(uuid) returns jsonb language sql as $$select jsonb_build_object('id',$1)$$;
create function cfy_menu_order_action_core(uuid,text,uuid,text,uuid,text,jsonb) returns jsonb language sql as $$select jsonb_build_object('ok',true)$$;
create function cfy_menu_create_internal_order_v2(uuid,text,uuid,text,jsonb) returns jsonb language sql as $$select jsonb_build_object('id',gen_random_uuid(),'reference','TEST')$$;
create function cfy_menu_finalize_created_order_v3(uuid,jsonb,jsonb) returns jsonb language sql as $$select $3$$;
create function cfy_menu_quote_order_v3(text,jsonb) returns jsonb language sql as $$select '{"total":0}'::jsonb$$;
create function cfy_menu_table_action_core(uuid,text,uuid,text,uuid,text) returns jsonb language sql as $$select '{"ok":true}'::jsonb$$;
create function cfy_menu_public_order_track(text,text) returns jsonb language sql as $$select null::jsonb$$;
create function cfy_menu_create_order_v3(text,jsonb) returns jsonb language sql as $$select jsonb_build_object('id',gen_random_uuid(),'tracking_token','token')$$;
create function cfy_menu_staff_operational_snapshot(text,integer) returns jsonb language sql as $$select '{}'::jsonb$$;
create function cfy_menu_staff_create_order(text,text,jsonb) returns jsonb language sql as $$select '{}'::jsonb$$;
create function cfy_menu_staff_create_order_v3(text,text,jsonb) returns jsonb language sql as $$select '{}'::jsonb$$;
create function cfy_menu_staff_order_action(text,uuid,text,jsonb) returns jsonb language sql as $$select '{}'::jsonb$$;
create function cfy_menu_staff_table_action(text,uuid,text) returns jsonb language sql as $$select '{}'::jsonb$$;
create function cfy_menu_public_feedback(text,text,integer,text) returns boolean language sql as $$select true$$;
create function cfy_menu_public_feedback_detailed(text,text,integer,integer,integer,integer,text) returns boolean language sql as $$select true$$;
create function cfy_delete_legacy_client() returns trigger language plpgsql security definer as $$begin return old;end$$;
create function cfy_sync_core_to_legacy() returns trigger language plpgsql security definer as $$begin return new;end$$;
create function cfy_sync_social_to_legacy() returns trigger language plpgsql security definer as $$begin return new;end$$;
insert into cfy_clients(id,code,brand_name_ar) values('${owner}','DEMO','مطعم تجريبي');insert into cfy_client_services values('${owner}','menu',true);
`;
test('Restaurant OS migration applies atomically and core secured flows execute',async()=>{const db=new PGlite({extensions:{pgcrypto}});await db.exec(baseline);await db.exec('begin');await db.exec(migration);await db.exec('commit');
 const branch=await db.query('select count(*)::int n from cfy_os_branches where client_id=$1',[owner]);assert.equal(branch.rows[0].n,1);
 const phone=await db.query("select cfy_os_phone('01012345678') value");assert.equal(phone.rows[0].value,'+201012345678');
 const session=await db.query("select cfy_os_session('1234567890123456')->>'role' role");assert.equal(session.rows[0].role,'owner');
 const inventory=await db.query("select cfy_os_finance_mutate('1234567890123456','inventory','save',jsonb_build_object('name','دقيق','unit','kg','quantity',10,'unit_price',40,'minimum_quantity',2)) item");assert.equal(inventory.rows[0].item.name,'دقيق');
 const denied=await db.query("select has_function_privilege('anon','cfy_os_require(text,text)','EXECUTE') ok");assert.equal(denied.rows[0].ok,false);
 for(const fn of ['cfy_delete_legacy_client()','cfy_sync_core_to_legacy()','cfy_sync_social_to_legacy()']){const privilege=await db.query("select has_function_privilege('anon',$1,'EXECUTE') ok",[fn]);assert.equal(privilege.rows[0].ok,false)}await db.close();});

test('Driver fallback, customer confirmation and page permissions are enforced',async()=>{const db=new PGlite({extensions:{pgcrypto}});await db.exec(baseline);await db.exec(migration);const driver='22222222-2222-4222-8222-222222222222',order='33333333-3333-4333-8333-333333333333',token='driver-session-token-123456',tracking='tracking-token-123456';
 await db.query("insert into cfy_menu_staff(id,client_id,code,name,role,pin_hash,enabled) values($1,$2,'DRV','Driver','delivery','x',true)",[driver,owner]);await db.query("insert into cfy_menu_staff_sessions(staff_id,client_id,token_hash,expires_at) values($1,$2,encode(extensions.digest($3,'sha256'),'hex'),now()+interval '1 day')",[driver,owner,token]);
 await db.query("insert into cfy_menu_orders(id,reference,client_id,order_type,status,assigned_driver_id,tracking_token_hash,payment_method,payment_status) values($1,'TEST-OTP',$2,'delivery','on_the_way',$3,encode(extensions.digest($4,'sha256'),'hex'),'cash','unpaid')",[order,owner,driver,tracking]);await db.query("insert into cfy_menu_delivery_assignments(client_id,order_id,driver_id,status) values($1,$2,$3,'picked_up')",[owner,order,driver]);
 await assert.rejects(()=>db.query("select cfy_os_require($1,'prep')",[token]),/page_forbidden/);await db.query("select cfy_os_order_action($1,'delivery',$2,'delivery_exception','{\"reason\":\"customer lost code\",\"confirmed\":true}')",[token,order]);
 await assert.rejects(()=>db.query("select cfy_os_public_feedback('TEST-OTP',$1,5,null,null,null,'')",[tracking]),/receipt_confirmation_required/);const receipt=await db.query("select cfy_os_customer_receipt('TEST-OTP',$1,true) result",[tracking]);assert.equal(receipt.rows[0].result.receipt_verification,'verified');const rating=await db.query("select cfy_os_public_feedback('TEST-OTP',$1,5,null,null,null,'great') ok",[tracking]);assert.equal(rating.rows[0].ok,true);await db.close();});

test('Customer profile remains private to its unguessable device token',async()=>{const db=new PGlite({extensions:{pgcrypto}});await db.exec(baseline);await db.exec(migration);const a='aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',b='bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',branch=(await db.query('select id from cfy_os_branches limit 1')).rows[0].id;const saved=await db.query("select cfy_os_customer_profile('DEMO',$1,jsonb_build_object('name','Test Customer','phone','01012345678','branch_id',$2::text)) result",[a,branch]);assert.equal(saved.rows[0].result.profile.phone,'01012345678');const isolated=await db.query("select cfy_os_customer_profile('DEMO',$1,null) result",[b]);assert.equal(isolated.rows[0].result,null);await db.close();});
