(function(){
const SUPA_URL='https://ytixcczbjmjnuotzavbb.supabase.co',SUPA_KEY='sb_publishable_0j9jf0boDrMGGO8S6mw-4Q_5bOeHIuU';
const client=window.supabase.createClient(SUPA_URL,SUPA_KEY);const p=new URLSearchParams(location.search),reference=(p.get('ref')||'').trim().toUpperCase(),trackToken=(p.get('token')||'').trim();
const box=document.getElementById('reportIssueBox'),text=document.getElementById('issueText'),btn=document.getElementById('sendIssue'),status=document.getElementById('issueStatus');let busy=false,last=null;
function paymentLabel(o){if(!o)return'';const method=o.payment_method==='cash'?'نقدي':(o.payment_method||'');const state=o.payment_status==='paid'?'مدفوع':o.payment_status==='refunded'?'مسترد':o.payment_status==='pending'?'قيد الدفع':'غير مدفوع';return `${method} · ${state}`}
function render(o){last=o;if(!o||!box)return;box.hidden=!!o.issue_open||o.status==='cancelled';let pay=document.getElementById('trackPaymentRow');if(!pay&&document.getElementById('summary')){pay=document.createElement('div');pay.id='trackPaymentRow';pay.className='row';pay.innerHTML='<span>الدفع</span><b></b>';document.getElementById('summary').appendChild(pay)}if(pay)pay.querySelector('b').textContent=paymentLabel(o)}
async function refresh(){if(!reference||!trackToken)return;const r=await client.rpc('cfy_menu_public_order_track',{p_reference:reference,p_token:trackToken});if(!r.error&&r.data)render(r.data)}
async function submit(){if(busy)return;const v=text.value.trim();status.textContent='';if(v.length<5){status.textContent='اكتب وصفًا أوضح للمشكلة.';return}busy=true;btn.disabled=true;btn.textContent='جاري الإرسال...';const r=await client.rpc('cfy_menu_public_report_issue',{p_reference:reference,p_token:trackToken,p_issue:v});busy=false;btn.disabled=false;btn.textContent='إرسال للمطعم';if(r.error||!r.data){const m=String(r.error?.message||'');status.textContent=m.includes('issue_already_open')?'يوجد بلاغ مفتوح بالفعل على هذا الطلب.':m.includes('order_cancelled')?'لا يمكن فتح بلاغ على طلب ملغي.':'تعذر إرسال البلاغ. حاول مرة أخرى.';return}status.textContent='تم إرسال البلاغ للمطعم.';box.hidden=true;await refresh()}
if(btn)btn.onclick=submit;refresh();setInterval(refresh,20000);
})();
