import {$,context,rpc,run,status,money,escapeHTML as esc,dateFilters,bindPeriods,filterArgs,table,chart,exportCSV} from './shared.js';
const pages=[['revenue','الإيرادات'],['sources','مصادر الطلبات'],['drivers','أداء المندوبين'],['categories','أفضل الأقسام'],['hours','ساعات الذروة']];
const labels={online:'أونلاين',pos:'POS',phone:'هاتف',delivery:'توصيل',takeaway:'استلام',dinein:'الصالة',cash:'نقدي',pay_on_delivery:'الدفع عند الاستلام',card_at_venue:'بطاقة في المطعم',new:'جديد',preparing:'جاري التجهيز',ready:'جاهز',on_the_way:'في الطريق',delivered:'تم التوصيل',completed:'مكتمل',cancelled:'ملغي'};
const named=rows=>rows.map(x=>({...x,label:labels[x.label]||x.label}));
const decimal=n=>n==null?'غير متاح':Number(n).toLocaleString('ar-EG',{maximumFractionDigits:1});
let section,exportRows=[];
export async function mountAnalytics(page){section=page.replace('analytics-','');$('#osContent').innerHTML=`<div class="os-heading"><div><h1>${pages.find(x=>x[0]===section)?.[1]||'التحليلات'}</h1><p>مؤشرات من الطلبات المسجلة، بتوقيت القاهرة.</p></div><button class="os-button" id="exportAnalytics">تصدير CSV</button></div>${dateFilters()}<div class="os-actions">${pages.map(([id,title])=>`<a class="os-button" href="?page=analytics-${id}${context.role==='owner'?'':'&as=staff'}">${title}</a>`).join('')}</div><div id="analyticsBody" style="margin-top:20px"></div>`;bindPeriods();$('#applyFilters').onclick=e=>run(e.target,load);$('#exportAnalytics').onclick=()=>exportCSV('CARDfy-analytics-'+section,exportRows[0]||[],exportRows.slice(1));await load();}
function card(title,body){return `<section class="os-card"><h2>${title}</h2>${body}</section>`;}
async function load(){status('جارٍ تحميل التحليلات…');const d=await rpc('cfy_os_analytics',{p_token:context.token,...filterArgs()});const branch=$('#branch'),old=branch.value;branch.innerHTML='<option value="">جميع الفروع</option>'+d.branches.map(b=>`<option value="${esc(b.id)}">${esc(b.name)}</option>`).join('');branch.value=old;const s=d.summary;
 let html='<div class="os-grid">'+[['الإيرادات المدفوعة',money(s.revenue)],['إجمالي الطلبات',s.orders],['متوسط الطلب المدفوع',money(s.average_order)],['طلبات مكتملة',s.completed],['طلبات ملغاة',s.cancelled],['التحضير بالدقائق',decimal(s.preparation_minutes)],['التوصيل بالدقائق',decimal(s.delivery_minutes)],['التقييم',decimal(s.rating)]].map(([label,value])=>`<div class="os-card"><span>${label}</span><strong class="os-kpi">${esc(value)}</strong></div>`).join('')+'</div><div class="os-grid" style="margin-top:18px">';exportRows=[['المؤشر','القيمة'],['الطلبات',s.orders],['الإيرادات',s.revenue]];
 if(section==='drivers'){const heads=['المندوب','المسند','المسلّم','مشاكل مفتوحة','التوصيل بالدقائق'];const rows=d.drivers.map(x=>[x.name,x.handled,x.delivered,x.issues,decimal(x.duration)]);html+=card('أداء فريق التوصيل',table(heads,rows)+'<p class="os-muted">وقت الرجوع للمطعم غير متاح: لا يوجد حدث رجوع مسجل. لا تُعرض مدة تقديرية كبيانات فعلية.</p>');exportRows=[heads,...rows];}
 else if(section==='categories'){html+=card('مبيعات الأقسام',chart(d.categories)+table(['القسم','الكمية','المبيعات'],d.categories.map(x=>[x.label,x.quantity,money(x.value)])));exportRows=[['القسم','الكمية','المبيعات'],...d.categories.map(x=>[x.label,x.quantity,x.value])];}
 else if(section==='hours'){html+=card('الطلبات حسب الساعة',chart(d.hours)+table(['الساعة','الطلبات','الإيرادات'],d.hours.map(x=>[x.label,x.value,money(x.revenue)])));exportRows=[['الساعة','الطلبات','الإيرادات'],...d.hours.map(x=>[x.label,x.value,x.revenue])];}
 else if(section==='sources'){html+=card('قنوات الطلب',chart(named(d.sources))+table(['المصدر','الطلبات','الإيرادات'],named(d.sources).map(x=>[x.label,x.orders,money(x.value)])))+card('نوع الخدمة',chart(named(d.types)));exportRows=[['المصدر','الطلبات','الإيرادات'],...named(d.sources).map(x=>[x.label,x.orders,x.value])];}
 else if(section==='revenue'){html+=card('الإيرادات اليومية',chart(d.days)+table(['التاريخ','الطلبات','الإيرادات'],d.days.map(x=>[x.label,x.orders,money(x.value)])))+card('حسب طريقة الدفع',chart(named(d.payments)))+card('حسب المصدر',chart(named(d.sources)));exportRows=[['التاريخ','الطلبات','الإيرادات'],...d.days.map(x=>[x.label,x.orders,x.value])];}
 else html+=card('الإيرادات',chart(d.days))+card('مصادر الطلبات',chart(named(d.sources)))+card('حالة الطلبات',chart(named(d.statuses)))+card('أفضل الأقسام',chart(d.categories.slice(0,8)))+card('ساعات الذروة',chart(d.hours));
 $('#analyticsBody').innerHTML=html+'</div>';status('');}
