import {$,context,rpc,run,status,money,escapeHTML as esc,dateFilters,bindPeriods,filterArgs,chart,exportCSV} from './shared.js?v=20260920-kitchen-ui';
import {active,total,group,byDate,percent,financeModel,safeMargin,suggestedPrice} from './finance-data.js?v=20260920-kitchen-ui';

const sections=[['revenues','الإيرادات','↗','متابعة المبيعات وقنوات التحصيل'],['expenses','المصروفات','↘','تسجيل ومراجعة مصروفات التشغيل'],['cashbox','الخزنة','▣','حركة النقدية والرصيد المتوقع'],['inventory','المخزن','▤','قيمة المواد وحدود إعادة الطلب'],['recipes','الوصفات والتكلفة','◫','تكلفة الوصفة وهامش الصنف'],['payroll','الموظفون والرواتب','♙','الرواتب الأساسية والمدفوعات'],['profit','الأرباح والخسائر','⌁','النتيجة التشغيلية للفترة'],['reports','التقارير','▥','تقارير مالية قابلة للتصدير']];
const labels=Object.fromEntries(sections.map(([id,label])=>[id,label]));
const subtitles={accounts:'نظرة موحّدة على المال الداخل والخارج وتكلفة تشغيل مطعمك.',revenues:'حلّل الإيرادات الفعلية حسب المصدر والخدمة وطريقة الدفع.',expenses:'راجع مصروفات التشغيل المسجلة وأضف القيود اليدوية بأمان.',cashbox:'تابع النقد الداخل والخارج والرصيد المتوقع داخل الخزنة.',inventory:'راقب أرصدة المواد الخام وقيمتها وحالة إعادة الطلب.',recipes:'اربط كل وصفة بمكوّناتها واحسب تكلفتها وهامشها.',payroll:'أدر بيانات الموظفين وسجّل الرواتب المدفوعة فعليًا.',profit:'افهم الربح التشغيلي من الإيرادات والمصروفات المسجلة.',reports:'أنشئ ملخصات حقيقية للفترة والفرع وصدّرها.'};
const kindNames={revenue:'إيراد يدوي',expense:'مصروف',cash_in:'قبض نقدي',cash_out:'صرف نقدي',closure:'جرد إغلاق',payroll:'راتب مدفوع'};
let snapshot={},model={},section='accounts',rows=[];
const route=id=>`?page=accounts${id==='accounts'?'':'-'+id}${context.role==='owner'?'':'&as=staff'}`;
const num=value=>Number(value)||0;
const dateLabel=value=>value?new Intl.DateTimeFormat('ar-EG',{dateStyle:'medium'}).format(new Date(value+'T12:00:00')):'—';
const empty=message=>`<div class="finance-empty"><span>◇</span><strong>${esc(message)}</strong></div>`;
const badge=(text,tone='neutral')=>`<span class="finance-badge ${tone}">${esc(text)}</span>`;
const icon=(symbol,tone='orange')=>`<span class="finance-icon ${tone}" aria-hidden="true">${symbol}</span>`;
const kpi=(label,value,detail='',tone='orange')=>`<article class="finance-kpi">${icon(tone==='good'?'↑':tone==='bad'?'↓':'•',tone)}<div><span>${esc(label)}</span><strong>${esc(value)}</strong>${detail?`<small>${esc(detail)}</small>`:''}</div></article>`;
const panel=(title,body,extra='')=>`<section class="finance-panel"><header><div><h2>${esc(title)}</h2>${extra?`<p>${esc(extra)}</p>`:''}</div></header>${body}</section>`;
const financeTable=(headers,body,emptyText='لا توجد بيانات لهذه الفترة.')=>`<div class="finance-table-wrap"><table class="finance-table"><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${body||`<tr><td colspan="${headers.length}" class="finance-empty-cell">${esc(emptyText)}</td></tr>`}</tbody></table></div>`;

export async function mountFinance(page){
 section=page.replace('accounts-','');if(section===page||!labels[section])section='accounts';document.body.classList.add('finance-active');
 $('#osContent').innerHTML=`<div class="finance-heading"><div><span class="finance-eyebrow"><bdi dir="ltr">CARDfy</bdi> · الحسابات</span><h1>${esc(labels[section]||'الحسابات')}</h1><p>${esc(subtitles[section])}</p></div><div class="finance-heading-actions"><button class="os-button" id="financePrint">طباعة</button><button class="os-button primary" id="export">تصدير CSV</button></div></div><nav class="finance-tabs" aria-label="أقسام الحسابات"><a href="${route('accounts')}" ${section==='accounts'?'aria-current="page"':''}>نظرة عامة</a>${sections.map(([id,label])=>`<a href="${route(id)}" ${section===id?'aria-current="page"':''}>${esc(label)}</a>`).join('')}</nav><div id="financeFilters">${dateFilters()}</div><div id="financeBody"></div>`;
 bindPeriods();$('#applyFilters').onclick=e=>run(e.target,load);$('#financePrint').onclick=()=>window.print();$('#export').onclick=()=>exportCSV(`CARDfy-${section}-${$('#from').value}-${$('#to').value}`,['البيان','القيمة'],rows);await load();
}
async function load(){status('جارٍ تحميل بيانات الحسابات…');snapshot=await rpc('cfy_os_finance_snapshot',{p_token:context.token,...filterArgs()});const select=$('#branch'),old=select.value;select.innerHTML='<option value="">جميع الفروع</option>'+snapshot.branches.map(branch=>`<option value="${esc(branch.id)}">${esc(branch.name)}</option>`).join('');select.value=old;model=financeModel(snapshot);render();status('');}
function render(){const renderers={accounts:renderDashboard,revenues:renderRevenue,expenses:renderExpenses,cashbox:renderCash,inventory:renderInventory,recipes:renderRecipes,payroll:renderPayroll,profit:renderProfit,reports:renderReports};$('#financeBody').innerHTML=renderers[section]();bindActions();}

function renderDashboard(){
 const low=model.inventory.filter(item=>num(item.quantity)<=num(item.minimum_quantity)),paidPayroll=total(model.payroll);const values={revenues:money(model.revenueTotal),expenses:money(model.expenseTotal),cashbox:money(model.closing),inventory:money(model.inventoryValue),recipes:`${model.recipes.length} وصفة`,payroll:money(paidPayroll),profit:money(model.operatingProfit),reports:'7 تقارير'};rows=sections.map(([id,label])=>[label,values[id]]);
 const cards=sections.map(([id,label,symbol,description])=>`<a class="finance-module-card" href="${route(id)}">${icon(symbol,id==='expenses'?'red':id==='profit'?'green':'orange')}<div><h2>${esc(label)}</h2><p>${esc(description)}</p><strong>${esc(values[id])}</strong><span>عرض التفاصيل ←</span></div></a>`).join('');
 const recent=model.entries.slice(0,6).map(entry=>`<tr><td>${dateLabel(entry.occurred_on)}</td><td><strong>${esc(entry.title||entry.reference||'عملية')}</strong><small>${esc(kindNames[entry.kind]||entry.kind||'طلب مدفوع')}</small></td><td class="amount ${['expense','cash_out','payroll'].includes(entry.kind)?'negative':'positive'}">${money(entry.amount)}</td></tr>`).join('');
 return `<div class="finance-kpi-grid">${kpi('إيرادات الفترة',money(model.revenueTotal),'من الطلبات المدفوعة والقيود اليدوية','good')}${kpi('مصروفات الفترة',money(model.expenseTotal),'المصروفات والرواتب المسجلة','bad')}${kpi('صافي التدفق',money(model.operatingProfit),'قبل تكاليف غير مسجلة',model.operatingProfit>=0?'good':'bad')}${kpi('رصيد الخزنة',money(model.closing),'حتى نهاية الفترة')}</div><div class="finance-module-grid">${cards}</div><div class="finance-two"><div>${panel('اتجاه الإيرادات',chart(byDate(model.revenue)),'القيم الحقيقية خلال الفترة المختارة')}</div><div>${panel('تنبيهات التشغيل',`<div class="finance-alert ${low.length?'warn':'good'}"><strong>${low.length?`${low.length} مواد عند حد إعادة الطلب`:'المخزون ضمن الحدود المسجلة'}</strong><span>${low.length?esc(low.slice(0,3).map(x=>x.name).join('، ')):'لا توجد تنبيهات مخزون حالية.'}</span></div><div class="finance-alert"><strong>${model.recipes.length} وصفة معرفة</strong><span>${model.recipes.length?'راجع الهوامش بعد أي تحديث لسعر الشراء.':'ابدأ بربط المنتجات بمكوناتها لحساب التكلفة.'}</span></div>`)}</div></div>${panel('آخر الحركات المسجلة',financeTable(['التاريخ','البيان','القيمة'],recent),'سجل مالي موحّد وقابل للمراجعة')}`;
}
function renderRevenue(){
 const bySource=group(model.revenue,'source'),byType=group(model.revenue,'order_type'),byPayment=group(model.revenue,'payment_method'),average=model.revenue.length?model.revenueTotal/model.revenue.length:0;rows=model.revenue.map(row=>[row.reference||row.title||'إيراد',row.amount]);
 const list=model.revenue.map(row=>`<tr><td>${dateLabel(row.occurred_on)}</td><td><strong>${esc(row.reference||row.title||'إيراد')}</strong><small>${esc(row.source||'قيد يدوي')}</small></td><td>${badge(row.order_type||'يدوي')}</td><td>${esc(row.payment_method||'—')}</td><td class="amount positive">${money(row.amount)}</td><td>${row.kind?entryActions(row):badge('طلب مدفوع','good')}</td></tr>`).join('');
 return `<div class="finance-kpi-grid">${kpi('إجمالي الإيرادات',money(model.revenueTotal),'إيرادات مدفوعة فقط','good')}${kpi('عدد المعاملات',String(model.revenue.length),'طلبات وقيود يدوية')}${kpi('متوسط المعاملة',money(average),'خلال الفترة المختارة')}${kpi('إيرادات نقدية',money(total(model.cashOrders)+total(model.manualRevenue.filter(x=>x.payment_method==='cash'))),'طلبات نقدية وإيراد يدوي')}</div><div class="finance-actions"><button class="os-button primary" data-new="revenue">إضافة إيراد يدوي</button></div><div class="finance-two wide">${panel('الإيرادات عبر الزمن',chart(byDate(model.revenue)),'القيم حسب يوم التحصيل')}${panel('حسب طريقة الدفع',distribution(byPayment,model.revenueTotal),'مقارنة قنوات التحصيل')}</div><div class="finance-three">${breakdown('مصادر الطلب',bySource)}${breakdown('أنواع الخدمة',byType)}${breakdown('طرق الدفع',byPayment)}</div>${panel('تفاصيل الإيرادات',financeTable(['التاريخ','العملية','النوع','الدفع','القيمة','الإجراء'],list),'الطلبات المدفوعة والقيود اليدوية فقط')}`;
}
function renderExpenses(){
 const categories=group(model.expenses,'category'),payments=group(model.expenses,'payment_method'),largest=[...model.expenses].sort((a,b)=>num(b.amount)-num(a.amount))[0];rows=model.expenses.map(row=>[row.title,row.amount]);
 const list=model.expenses.map(row=>`<tr><td>${dateLabel(row.occurred_on)}</td><td><strong>${esc(row.title)}</strong><small>${esc(row.notes||kindNames[row.kind])}</small></td><td>${badge(row.category||'غير مصنف')}</td><td>${esc(row.payment_method)}</td><td class="amount negative">${money(row.amount)}</td><td>${entryActions(row)}</td></tr>`).join('');
 return `<div class="finance-kpi-grid">${kpi('إجمالي المصروفات',money(model.expenseTotal),'يشمل الرواتب المسجلة','bad')}${kpi('عدد القيود',String(model.expenses.length),'قيود فعلية خلال الفترة')}${kpi('متوسط المصروف',money(model.expenses.length?model.expenseTotal/model.expenses.length:0),'لكل قيد')}${kpi('أكبر مصروف',largest?money(largest.amount):money(0),largest?.title||'لا توجد بيانات')}</div><div class="finance-actions"><button class="os-button primary" data-new="expense">إضافة مصروف</button></div><div class="finance-two wide">${panel('المصروفات عبر الزمن',chart(byDate(model.expenses)),'القيم حسب تاريخ القيد')}${panel('حسب طريقة الدفع',distribution(payments,model.expenseTotal),'توزيع المصروفات المسجلة')}</div><div class="finance-two">${breakdown('تصنيفات المصروفات',categories)}${panel('ملاحظة محاسبية',`<div class="finance-note">يعرض CARDfy المصروفات التشغيلية التي سجلها المستخدم. المصروفات الدورية والمرفقات ليست بيانات متاحة في النموذج الحالي، لذلك لا يتم افتراضها.</div>`)}</div>${panel('تفاصيل المصروفات',financeTable(['التاريخ','البيان','التصنيف','الدفع','القيمة','الإجراء'],list),'قيود المصروف والرواتب المسجلة')}`;
}
function renderCash(){
 const varianceEntry=model.entries.find(row=>row.kind==='closure'),actual=varianceEntry?num(varianceEntry.amount):null,variance=actual===null?null:actual-model.closing;const movements=[...model.cashEntries,...model.cashOrders].sort((a,b)=>String(b.occurred_on).localeCompare(String(a.occurred_on)));rows=movements.map(row=>[row.title||row.reference||'طلب نقدي',row.amount]);
 const list=movements.map(row=>{const outgoing=['cash_out','expense','payroll'].includes(row.kind);return `<tr><td>${dateLabel(row.occurred_on)}</td><td><strong>${esc(row.title||row.reference||'طلب نقدي')}</strong><small>${esc(kindNames[row.kind]||'مبيعات نقدية')}</small></td><td>${badge(outgoing?'نقد خارج':'نقد داخل',outgoing?'bad':'good')}</td><td class="amount ${outgoing?'negative':'positive'}">${outgoing?'−':'+'}${money(row.amount)}</td><td>${row.kind?entryActions(row):badge('طلب مدفوع','good')}</td></tr>`}).join('');
 return `<div class="finance-kpi-grid">${kpi('الرصيد الافتتاحي',money(model.opening),'محسوب قبل حركات الفترة')}${kpi('النقد الداخل',money(model.cashIn),'مبيعات وقبض وإيراد نقدي','good')}${kpi('النقد الخارج',money(model.cashOut),'صرف ومصروفات ورواتب','bad')}${kpi('الإغلاق المتوقع',money(model.closing),'حتى نهاية الفترة')}</div><div class="finance-actions"><button class="os-button primary" data-new="cash_in">تسجيل قبض</button><button class="os-button" data-new="cash_out">تسجيل صرف</button><button class="os-button" data-new="closure">تسجيل جرد الإغلاق</button></div><div class="finance-two"><div>${panel('توزيع الحركة النقدية',`<div class="finance-flow"><div><span>داخل</span><strong class="positive">${money(model.cashIn)}</strong><i style="--size:${Math.max(8,percent(model.cashIn,model.cashIn+model.cashOut))}%"></i></div><div><span>خارج</span><strong class="negative">${money(model.cashOut)}</strong><i style="--size:${Math.max(8,percent(model.cashOut,model.cashIn+model.cashOut))}%"></i></div></div>`)}</div><div>${panel('مطابقة الخزنة',`<div class="finance-reconcile"><span>الإغلاق المتوقع</span><strong>${money(model.closing)}</strong><span>آخر رصيد معدود</span><strong>${actual===null?'غير مسجل':money(actual)}</strong><span>الفرق</span><strong class="${variance===null?'':variance===0?'positive':'negative'}">${variance===null?'غير متاح':money(variance)}</strong></div><p class="finance-note">آخر جرد مسجل داخل الفترة هو المرجع المتاح للمطابقة.</p>`)}</div></div>${panel('حركات الخزنة',financeTable(['التاريخ','البيان','الاتجاه','القيمة','الإجراء'],list),'الحركات النقدية الفعلية في الفترة')}`;
}
function renderInventory(){
 const low=model.inventory.filter(item=>num(item.quantity)<=num(item.minimum_quantity)),movements=active(snapshot.movements);rows=model.inventory.map(item=>[item.name,num(item.quantity)*num(item.unit_price)]);
 const list=model.inventory.map(item=>`<tr><td><strong>${esc(item.name)}</strong></td><td>${esc(item.quantity)} ${esc(item.unit)}</td><td>${money(item.unit_price)}</td><td class="amount">${money(num(item.quantity)*num(item.unit_price))}</td><td>${item.minimum_quantity} ${esc(item.unit)}</td><td>${num(item.quantity)<=num(item.minimum_quantity)?badge('إعادة طلب','bad'):badge('متوفر','good')}</td><td>${entityActions(item,'inventory',true)}</td></tr>`).join('');
 const moveRows=movements.slice(0,12).map(move=>{const item=model.inventory.find(x=>x.id===move.item_id);return `<tr><td>${new Intl.DateTimeFormat('ar-EG',{dateStyle:'medium',timeStyle:'short'}).format(new Date(move.occurred_at))}</td><td>${esc(item?.name||'مادة مؤرشفة')}</td><td class="amount ${num(move.quantity_delta)>=0?'positive':'negative'}">${num(move.quantity_delta)>=0?'+':''}${esc(move.quantity_delta)}</td><td>${money(move.unit_price)}</td><td>${esc(move.reason)}</td></tr>`}).join('');
 return `<div class="finance-kpi-grid">${kpi('قيمة المخزون',money(model.inventoryValue),'الكمية × متوسط سعر الوحدة')}${kpi('عدد المواد',String(model.inventory.length),'مواد خام نشطة')}${kpi('مواد منخفضة',String(low.length),low.length?'تحتاج مراجعة':'لا توجد تنبيهات',low.length?'bad':'good')}${kpi('حركات الفترة',String(movements.length),'إضافات وصرف وتسويات')}</div><div class="finance-actions"><button class="os-button primary" data-new="inventory">إضافة مادة</button></div>${low.length?`<div class="finance-alert warn"><strong>تنبيه إعادة الطلب</strong><span>${esc(low.map(x=>x.name).join('، '))}</span></div>`:''}${panel('أرصدة المواد الخام',financeTable(['المادة','الرصيد','تكلفة الوحدة','القيمة','حد الطلب','الحالة','الإجراء'],list),'المخزون الفعلي للفرع المختار')}${panel('سجل حركة المخزون',financeTable(['التاريخ','المادة','الكمية','سعر الوحدة','السبب'],moveRows),'الحركات المسجلة خلال الفترة')}`;
}
function renderRecipes(){
 rows=model.recipes.map(recipe=>[recipe.name,recipe.cost]);const cards=model.recipes.map(recipe=>{const margin=safeMargin(recipe.selling_price,recipe.cost),suggested=suggestedPrice(recipe.cost,recipe.target_margin);return `<article class="finance-recipe"><div class="finance-recipe-head">${icon('◫')}<div><h2>${esc(recipe.name)}</h2><span>${recipe.ingredients?.length||0} مكوّن</span></div>${margin===null?badge('سعر البيع غير محدد'):badge(`${margin}% هامش`,margin>=num(recipe.target_margin)?'good':'warn')}</div><dl><div><dt>تكلفة الوصفة</dt><dd>${money(recipe.cost)}</dd></div><div><dt>سعر البيع</dt><dd>${money(recipe.selling_price)}</dd></div><div><dt>الربح المتوقع</dt><dd class="${num(recipe.selling_price)-num(recipe.cost)>=0?'positive':'negative'}">${money(num(recipe.selling_price)-num(recipe.cost))}</dd></div><div><dt>سعر مقترح</dt><dd>${suggested===null?'غير متاح':money(suggested)}</dd></div></dl><div class="finance-actions">${entityActions(recipe,'recipe')}</div></article>`}).join('');
 return `<div class="finance-kpi-grid">${kpi('الوصفات النشطة',String(model.recipes.length),'وصفات مرتبطة بمواد المخزون')}${kpi('متوسط التكلفة',money(model.recipes.length?model.recipes.reduce((s,x)=>s+num(x.cost),0)/model.recipes.length:0),'حسب أسعار الشراء الحالية')}${kpi('متوسط سعر البيع',money(model.recipes.length?model.recipes.reduce((s,x)=>s+num(x.selling_price),0)/model.recipes.length:0),'القيمة المسجلة في الوصفة')}${kpi('مواد متاحة',String(model.inventory.length),'لإنشاء وصفات جديدة')}</div><div class="finance-actions"><button class="os-button primary" data-new="recipe" ${model.inventory.length?'':'disabled'}>إضافة وصفة</button></div><p class="finance-note">التكلفة تُحسب من كميات المكونات ومتوسط سعر وحداتها المسجل. لا يخصم النظام المخزون تلقائيًا من المبيعات لأن قاعدة الاستهلاك الفعلية غير معتمدة بعد.</p><div class="finance-recipe-grid">${cards||empty('أضف أول وصفة لحساب التكلفة والهامش.')}</div>`;
}
function renderPayroll(){
 const base=model.employees.reduce((sum,employee)=>sum+num(employee.salary),0),paid=total(model.payroll);rows=model.employees.map(employee=>[employee.name,employee.salary]);const list=model.employees.map(employee=>{const paidForEmployee=model.payroll.filter(row=>row.category===employee.id||row.title.includes(employee.name));return `<tr><td><strong>${esc(employee.name)}</strong><small>${esc(employee.job_title||'بدون مسمى وظيفي')}</small></td><td>${branchName(employee.branch_id)}</td><td class="amount">${money(employee.salary)}</td><td class="amount positive">${money(total(paidForEmployee))}</td><td>${paidForEmployee.length?badge('مسجل','good'):badge('غير مسجل','warn')}</td><td>${entityActions(employee,'employee')}<button class="os-button" data-payroll="${employee.id}">تسجيل راتب</button></td></tr>`}).join('');
 return `<div class="finance-kpi-grid">${kpi('عدد الموظفين',String(model.employees.length),'موظفون نشطون')}${kpi('إجمالي الرواتب الأساسية',money(base),'دورة راتب واحدة')}${kpi('رواتب مسجلة بالفترة',money(paid),'قيود دفع فعلية','good')}${kpi('المتبقي النظري',money(Math.max(0,base-paid)),'للمراجعة فقط')}</div><div class="finance-actions"><button class="os-button primary" data-new="employee">إضافة موظف</button><button class="os-button" data-new="payroll">تسجيل راتب عام</button></div><p class="finance-note">النظام الحالي يسجل الراتب الأساسي والمدفوعات الفعلية. البدلات والخصومات وحالة مسير الرواتب غير موجودة في نموذج البيانات المعتمد، لذلك لا تُفترض في الحسابات.</p>${panel('الموظفون والرواتب',financeTable(['الموظف','الفرع','الراتب الأساسي','المدفوع بالفترة','الحالة','الإجراء'],list),'البيانات التشغيلية الأساسية للرواتب')}`;
}
function renderProfit(){
 const payroll=total(model.payroll),otherExpenses=model.expenseTotal-payroll,margin=percent(model.operatingProfit,model.revenueTotal);rows=[['الإيرادات',model.revenueTotal],['تكلفة الطعام','غير متاحة'],['العمالة',payroll],['مصروفات التشغيل',otherExpenses],['الربح التشغيلي',model.operatingProfit]];
 const breakdownRows=`<tr><td>المبيعات والإيرادات</td><td class="amount positive">${money(model.revenueTotal)}</td><td>طلبات مدفوعة + إيراد يدوي</td></tr><tr><td>تكلفة الطعام</td><td>${badge('غير متاحة','warn')}</td><td>لا توجد قاعدة استهلاك معتمدة للمبيعات</td></tr><tr><td>تكلفة العمالة</td><td class="amount negative">${money(payroll)}</td><td>رواتب مدفوعة مسجلة</td></tr><tr><td>مصروفات التشغيل</td><td class="amount negative">${money(otherExpenses)}</td><td>مصروفات فعلية مسجلة</td></tr><tr class="finance-total"><td>الربح التشغيلي المسجل</td><td class="amount ${model.operatingProfit>=0?'positive':'negative'}">${money(model.operatingProfit)}</td><td>${margin}% من الإيرادات</td></tr>`;
 return `<div class="finance-kpi-grid">${kpi('الإيرادات',money(model.revenueTotal),'خلال الفترة','good')}${kpi('مصروفات التشغيل',money(otherExpenses),'باستثناء الرواتب','bad')}${kpi('تكلفة العمالة',money(payroll),'الرواتب المدفوعة المسجلة','bad')}${kpi('الربح التشغيلي',money(model.operatingProfit),`${margin}% هامش مسجل`,model.operatingProfit>=0?'good':'bad')}</div><div class="finance-two wide">${panel('اتجاه الإيرادات',chart(byDate(model.revenue)),'الإيرادات اليومية')}${panel('اتجاه المصروفات',chart(byDate(model.expenses)),'المصروفات والرواتب اليومية')}</div>${panel('قائمة الأرباح والخسائر التشغيلية',financeTable(['البند','القيمة','أساس الحساب'],breakdownRows),'عرض مبسط لمساندة قرار صاحب المطعم')}<div class="finance-alert warn"><strong>حدود التقرير</strong><span>الربح المعروض يطرح المصروفات والرواتب المسجلة فقط. تكلفة الطعام غير مخصومة حتى اعتماد ربط استهلاك الوصفات بالمبيعات؛ لذلك لا يمثل صافي ربح قانوني أو ضريبي.</span></div>`;
}
function renderReports(){
 const reportList=[['revenues','تقرير الإيرادات','الطلبات المدفوعة والإيرادات اليدوية',model.revenueTotal],['expenses','تقرير المصروفات','المصروفات والرواتب المسجلة',model.expenseTotal],['cashbox','تقرير الخزنة','الحركة النقدية والرصيد',model.closing],['inventory','تقرير المخزون','قيمة المواد الخام الحالية',model.inventoryValue],['recipes','تقرير الوصفات والتكلفة','تكلفة الوصفات وهوامشها',model.recipes.length],['payroll','تقرير الموظفين والرواتب','الرواتب الأساسية والمدفوعة',total(model.payroll)],['profit','تقرير الأرباح والخسائر','النتيجة التشغيلية المسجلة',model.operatingProfit]];rows=reportList.map(report=>[report[1],report[3]]);const cards=reportList.map(([id,title,description,value])=>`<article class="finance-report-card">${icon('▥')}<div><h2>${esc(title)}</h2><p>${esc(description)}</p><strong>${typeof value==='number'&&id!=='recipes'?money(value):esc(value)}</strong></div><div class="finance-actions"><a class="os-button" href="${route(id)}">عرض</a><button class="os-button" data-report="${id}">تصدير</button></div></article>`).join('');
 return `<div class="finance-kpi-grid">${kpi('الإيرادات',money(model.revenueTotal),'الفترة المختارة','good')}${kpi('المصروفات',money(model.expenseTotal),'الفترة المختارة','bad')}${kpi('الرصيد النقدي',money(model.closing),'حتى نهاية الفترة')}${kpi('الربح التشغيلي',money(model.operatingProfit),'قبل تكلفة طعام غير مدعومة',model.operatingProfit>=0?'good':'bad')}</div><div class="finance-report-grid">${cards}</div><div class="finance-alert"><strong>تقارير حقيقية عند الطلب</strong><span>يتم تكوين التقرير من الفترة والفرع المحددين حاليًا. لا يحفظ النظام نسخًا مولّدة أو يرسلها تلقائيًا لأن هذه الوظائف غير موجودة في الـbackend الحالي.</span></div>`;
}

function breakdown(title,items){return panel(title,items.length?`<div class="finance-breakdown">${items.slice(0,8).map(item=>`<div><span>${esc(item.label)}</span><i><b style="width:${Math.max(3,percent(item.value,items[0]?.value))}%"></b></i><strong>${money(item.value)}</strong></div>`).join('')}</div>`:empty('لا توجد بيانات للتوزيع.'));}
function distribution(items,whole){return items.length?`<div class="finance-distribution"><div class="finance-donut" style="--slice:${percent(items[0]?.value,whole)}"><strong>${percent(items[0]?.value,whole)}%</strong><span>${esc(items[0]?.label||'—')}</span></div><div>${items.slice(0,5).map((item,index)=>`<p><i class="dot c${index}"></i><span>${esc(item.label)}</span><strong>${percent(item.value,whole)}%</strong><small>${money(item.value)}</small></p>`).join('')}</div></div>`:empty('لا توجد بيانات للتوزيع.');}
function branchName(id){return esc(snapshot.branches.find(branch=>branch.id===id)?.name||'كل الفروع');}
function entryActions(row){return `<span class="finance-row-actions"><button class="os-button" data-edit="${row.id}" data-kind="${row.kind}">تعديل</button><button class="os-button danger" data-archive="${row.id}" data-kind="${row.kind}">أرشفة</button></span>`;}
function entityActions(row,kind,stock=false){return `<span class="finance-row-actions"><button class="os-button" data-edit="${row.id}" data-kind="${kind}">تعديل</button>${stock?`<button class="os-button" data-stock="${row.id}">حركة</button>`:''}<button class="os-button danger" data-archive="${row.id}" data-kind="${kind}">أرشفة</button></span>`;}
function bindActions(){$('#financeBody').querySelectorAll('[data-new]').forEach(button=>button.onclick=()=>edit(button.dataset.new));$('#financeBody').querySelectorAll('[data-edit]').forEach(button=>button.onclick=()=>edit(button.dataset.kind,find(button.dataset.edit)));$('#financeBody').querySelectorAll('[data-stock]').forEach(button=>button.onclick=()=>movement(find(button.dataset.stock)));$('#financeBody').querySelectorAll('[data-archive]').forEach(button=>button.onclick=()=>archive(button.dataset.kind,find(button.dataset.archive)));$('#financeBody').querySelectorAll('[data-payroll]').forEach(button=>button.onclick=()=>payEmployee(find(button.dataset.payroll)));$('#financeBody').querySelectorAll('[data-report]').forEach(button=>button.onclick=()=>exportReport(button.dataset.report));}
function find(id){return [...model.entries,...model.inventory,...model.recipes,...model.employees].find(row=>row.id===id);}
function dialog(title,body,submit){$('#financeDialog')?.remove();const el=document.createElement('dialog');el.id='financeDialog';el.className='os-dialog finance-dialog';el.innerHTML=`<header><div><span class="finance-eyebrow"><bdi dir="ltr">CARDfy</bdi> · الحسابات</span><h2>${esc(title)}</h2></div><button class="os-button" data-close aria-label="إغلاق">×</button></header><form id="financeForm" class="os-form">${body}<p id="formError" class="full os-error" hidden></p><div class="full os-actions"><button class="os-button" type="button" data-close>إلغاء</button><button class="os-button primary" type="submit">حفظ</button></div></form>`;document.body.append(el);el.querySelectorAll('[data-close]').forEach(button=>button.onclick=()=>el.close());el.querySelector('form').onsubmit=async event=>{event.preventDefault();const button=el.querySelector('[type=submit]');button.disabled=true;try{await submit(Object.fromEntries(new FormData(event.target)));el.close();await load();}catch(error){$('#formError').hidden=false;$('#formError').textContent=error.message||'تعذر حفظ البيانات.';}finally{button.disabled=false;}};el.showModal();return el;}
function field(name,label,value='',type='text',extra=''){return `<label class="os-field">${esc(label)}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;}
function choices(name,label,options,value){return `<label class="os-field">${esc(label)}<select name="${name}">${options.map(([v,l])=>`<option value="${esc(v)}" ${String(v)===String(value)?'selected':''}>${esc(l)}</option>`).join('')}</select></label>`;}
function branchChoices(value=''){return choices('branch_id','الفرع',[['','كل الفروع'],...snapshot.branches.filter(branch=>branch.enabled).map(branch=>[branch.id,branch.name])],value);}
function edit(kind,row={}){let body=branchChoices(row.branch_id||'');if(['inventory','recipe','employee'].includes(kind)){body+=field('name','الاسم',row.name||'','text','required maxlength="160"');if(kind==='inventory')body+=choices('unit','الوحدة',['kg','g','liter','ml','piece','box','pack','bottle'].map(unit=>[unit,unit]),row.unit||'kg')+(!row.id?field('quantity','الرصيد الافتتاحي',0,'number','min="0" step="0.0001" required'):'')+field('unit_price','سعر شراء الوحدة',row.unit_price||0,'number','min="0" step="0.0001" required')+field('minimum_quantity','حد إعادة الطلب',row.minimum_quantity||0,'number','min="0" step="0.0001"');if(kind==='employee')body+=field('job_title','المسمى الوظيفي',row.job_title||'')+field('salary','الراتب الأساسي',row.salary||0,'number','min="0" step="0.01" required');if(kind==='recipe')body+=field('selling_price','سعر البيع',row.selling_price||0,'number','min="0" step="0.01" required')+field('target_margin','هامش الربح المستهدف %',row.target_margin??30,'number','min="0" max="99.99" step="0.01" required')+'<div class="full" id="ingredients"></div><button class="os-button full" type="button" id="addIngredient">إضافة مكوّن</button>';}else body+=field('title','البيان',row.title||'','text','required maxlength="160"')+field('category','التصنيف',row.category||'')+field('amount',kind==='closure'?'الرصيد المعدود عند الإغلاق':'المبلغ',row.amount||0,'number','min="0" step="0.01" required')+choices('payment_method','طريقة الدفع',[['cash','نقدي'],['card','بطاقة'],['instapay','إنستاباي'],['wallet','محفظة'],['other','أخرى']],row.payment_method||'cash')+field('occurred_on','التاريخ',row.occurred_on||$('#to').value,'date','required')+field('notes','ملاحظات',row.notes||'');const parts=(row.ingredients||[]).map(part=>({...part}));const el=dialog(row.id?'تعديل البيانات':'إضافة سجل',body,async data=>{if(kind==='recipe')data.ingredients=Array.from(el.querySelectorAll('[data-ingredient]')).map(node=>({item_id:node.querySelector('[name=item]').value,quantity:Number(node.querySelector('[name=qty]').value),unit:node.querySelector('[name=unit]').value}));await rpc('cfy_os_finance_mutate',{p_token:context.token,p_kind:kind,p_action:'save',p_data:{...data,id:row.id||null,version:row.version||1}});});if(kind==='recipe'){const add=part=>{const node=document.createElement('div');node.className='finance-ingredient';node.dataset.ingredient='';node.innerHTML=choices('item','المكوّن',model.inventory.map(item=>[item.id,item.name]),part.item_id)+field('qty','الكمية',part.quantity||1,'number','min="0.0001" step="0.0001" required')+choices('unit','وحدة المكوّن',['kg','g','liter','ml','piece','box','pack','bottle'].map(unit=>[unit,unit]),part.unit||'g')+'<button type="button" class="os-button danger">إزالة</button>';node.querySelector('button').onclick=()=>node.remove();$('#ingredients').append(node);};parts.forEach(add);$('#addIngredient').onclick=()=>add({});if(!parts.length)add({});}}
function payEmployee(employee){edit('payroll',{title:`راتب ${employee.name}`,category:employee.id,amount:employee.salary,payment_method:'cash',occurred_on:$('#to').value,notes:`صرف راتب — ${employee.job_title||'موظف'}`,branch_id:employee.branch_id});}
function movement(row){dialog(`حركة مخزون — ${row.name}`,field('quantity_delta','الكمية: موجب للإضافة، سالب للصرف',1,'number',`step="0.0001" required min="-${esc(row.quantity)}"`)+field('unit_price','سعر شراء الوحدة',row.unit_price,'number','min="0" step="0.0001" required')+field('reason','السبب','','text','required maxlength="500"'),data=>rpc('cfy_os_finance_mutate',{p_token:context.token,p_kind:'inventory',p_action:'movement',p_data:{...data,id:row.id,version:row.version}}));}
function archive(kind,row){dialog('أرشفة السجل','<p class="full finance-note">سيُستبعد السجل من العروض النشطة مع الاحتفاظ به داخل سجل المراجعة. تأكد من اختيار السجل الصحيح.</p>',()=>rpc('cfy_os_finance_mutate',{p_token:context.token,p_kind:kind,p_action:'archive',p_data:{id:row.id,version:row.version}}));}
function exportReport(id){const reportRows={revenues:model.revenue.map(row=>[row.occurred_on,row.reference||row.title,row.payment_method,row.amount]),expenses:model.expenses.map(row=>[row.occurred_on,row.title,row.category,row.amount]),cashbox:[['الرصيد الافتتاحي',model.opening],['النقد الداخل',model.cashIn],['النقد الخارج',model.cashOut],['الإغلاق المتوقع',model.closing]],inventory:model.inventory.map(row=>[row.name,row.quantity,row.unit,row.unit_price,num(row.quantity)*num(row.unit_price)]),recipes:model.recipes.map(row=>[row.name,row.cost,row.selling_price,safeMargin(row.selling_price,row.cost)]),payroll:model.employees.map(row=>[row.name,row.job_title,row.salary]),profit:[['الإيرادات',model.revenueTotal],['المصروفات والرواتب',model.expenseTotal],['الربح التشغيلي',model.operatingProfit]]};const headers={revenues:['التاريخ','العملية','الدفع','القيمة'],expenses:['التاريخ','البيان','التصنيف','القيمة'],cashbox:['البند','القيمة'],inventory:['المادة','الرصيد','الوحدة','سعر الوحدة','القيمة'],recipes:['الوصفة','التكلفة','سعر البيع','الهامش %'],payroll:['الموظف','الوظيفة','الراتب الأساسي'],profit:['البند','القيمة']};exportCSV(`CARDfy-${id}-${$('#from').value}-${$('#to').value}`,headers[id],reportRows[id]);}