import {$,context,rpc,run,status,money,escapeHTML as esc,dateFilters,bindPeriods,filterArgs,table,chart,exportCSV} from './shared.js';
const sections=[['revenues','الإيرادات'],['expenses','المصروفات'],['cashbox','الخزنة'],['inventory','المخزن'],['recipes','الوصفات والتكلفة'],['payroll','الموظفون والرواتب'],['profit','الأرباح والخسائر'],['reports','التقارير']];
let snapshot,section,rows=[];
const sum=(items,key='amount')=>items.reduce((n,row)=>n+Number(row[key]||0),0);
const live=items=>(items||[]).filter(x=>!x.archived);
const links=()=>sections.map(([id,label])=>`<a class="os-button" href="?page=accounts-${id}${context.role==='owner'?'':'&as=staff'}">${label}</a>`).join('');
export async function mountFinance(page){section=page.replace('accounts-','');$('#osContent').innerHTML=`<div class="os-heading"><div><h1>${sections.find(x=>x[0]===section)?.[1]||'الحسابات'}</h1><p>إدارة مالية واضحة من بيانات مطعمك الفعلية.</p></div><button class="os-button" id="export">تصدير CSV</button></div><div id="financeFilters">${dateFilters()}</div><div class="os-actions">${links()}</div><div id="financeBody" style="margin-top:22px"></div>`;bindPeriods();$('#applyFilters').onclick=e=>run(e.target,load);$('#export').onclick=()=>exportCSV('CARDfy-'+section,['البيان','القيمة'],rows);await load();}
async function load(){status('جارٍ تحميل الحسابات…');snapshot=await rpc('cfy_os_finance_snapshot',{p_token:context.token,...filterArgs()});const select=$('#branch'),old=select.value;select.innerHTML='<option value="">جميع الفروع</option>'+snapshot.branches.map(b=>`<option value="${esc(b.id)}">${esc(b.name)}</option>`).join('');select.value=old;render();status('');}
function kpi(label,value){return `<div class="os-card"><span>${esc(label)}</span><strong class="os-kpi">${esc(value)}</strong></div>`;}
function render(){const entries=live(snapshot.entries),revenue=live(snapshot.order_revenue).concat(entries.filter(e=>e.kind==='revenue')),expenses=entries.filter(e=>['expense','payroll'].includes(e.kind)),inventory=live(snapshot.inventory),recipes=live(snapshot.recipes),employees=live(snapshot.employees);let body='';rows=[];
 if(section==='accounts'||!sections.some(x=>x[0]===section)){const values=[money(sum(revenue)),money(sum(expenses)),money(snapshot.cash_balance),money(inventory.reduce((n,i)=>n+Number(i.quantity)*Number(i.unit_price),0)),recipes.length+' وصفة',employees.length+' موظف',money(sum(revenue)-sum(expenses)),'تصدير التقارير'];body='<div class="os-grid">'+sections.map(([id,label],i)=>`<a class="os-card os-card-link" href="?page=accounts-${id}${context.role==='owner'?'':'&as=staff'}"><h2>${label}</h2><strong class="os-kpi">${values[i]}</strong><span>عرض التفاصيل ←</span></a>`).join('')+'</div>';rows=sections.map((x,i)=>[x[1],values[i]]);}
 else if(['revenues','expenses','cashbox','profit','reports'].includes(section)){
  const selected=section==='revenues'?revenue:section==='expenses'?expenses:entries.filter(e=>['cash_in','cash_out','closure'].includes(e.kind));
  body=`<div class="os-grid">${kpi('الإيرادات',money(sum(revenue)))}${kpi('المصروفات المسجلة',money(sum(expenses)))}${kpi('صافي الإيراد بعد المصروفات',money(sum(revenue)-sum(expenses)))}${kpi('رصيد الخزنة حتى نهاية الفترة',money(snapshot.cash_balance))}</div>`;
  if(section==='profit')body+='<p class="os-muted">الصافي = الإيرادات المدفوعة + الإيرادات اليدوية − المصروفات والرواتب المسجلة. تكلفة الوصفات تقديرية ولا تُخصم تلقائيًا؛ سجّل المصروفات الفعلية دون تكرارها.</p>';
  const trendRows=section==='expenses'?expenses:revenue,byDay={};trendRows.forEach(e=>byDay[e.occurred_on]=(byDay[e.occurred_on]||0)+Number(e.amount));body+=`<section class="os-card" style="margin-top:18px"><h2>${section==='expenses'?'المصروفات':'الإيراد'} خلال الفترة</h2>${chart(Object.entries(byDay).sort().map(([label,value])=>({label,value})))}</section>`;
  if(section==='revenues'){const grouped=key=>Object.values(revenue.reduce((a,e)=>{const label=e[key]||'غير محدد';a[label]??={label,value:0,orders:0};a[label].value+=Number(e.amount);a[label].orders++;return a},{}));const source=grouped('source'),service=grouped('order_type'),payment=grouped('payment_method');body+=`<div class="os-grid" style="margin-top:18px"><section class="os-card"><h2>حسب قناة الطلب</h2>${table(['القناة','المعاملات','الإيراد'],source.map(x=>[x.label,x.orders,money(x.value)]))}</section><section class="os-card"><h2>حسب نوع الخدمة</h2>${table(['النوع','المعاملات','الإيراد'],service.map(x=>[x.label,x.orders,money(x.value)]))}</section><section class="os-card"><h2>حسب طريقة الدفع</h2>${table(['الدفع','المعاملات','الإيراد'],payment.map(x=>[x.label,x.orders,money(x.value)]))}</section></div>`;}
  if(!['profit','reports'].includes(section)){const kind=section==='revenues'?'revenue':section==='expenses'?'expense':'cash_in';body+=`<div class="os-actions" style="margin-top:18px"><button class="os-button primary" data-new="${kind}">إضافة ${section==='revenues'?'إيراد يدوي':section==='expenses'?'مصروف':'حركة قبض'}</button>${section==='cashbox'?'<button class="os-button" data-new="cash_out">حركة صرف</button><button class="os-button" data-new="closure">تسجيل جرد الإغلاق</button>':''}</div>`;body+=entryTable(selected);rows=selected.map(e=>[e.title||e.reference,e.amount]);}
  else {rows=[['الإيرادات',sum(revenue)],['المصروفات والرواتب',sum(expenses)],['الصافي',sum(revenue)-sum(expenses)],['رصيد الخزنة',snapshot.cash_balance]];body+=table(['البيان','القيمة'],rows.map(([k,v])=>[k,money(v)]));if(section==='reports')body+='<p class="os-muted">التصدير يشمل ملخص الفترة والفرع المختارين. استخدم صفحة القسم لتصدير سجلاته التفصيلية.</p>';}
 }
 else {const list=section==='inventory'?inventory:section==='recipes'?recipes:employees;const kind=section==='inventory'?'inventory':section==='recipes'?'recipe':'employee';body=`<div class="os-actions"><button class="os-button primary" data-new="${kind}">إضافة ${kind==='inventory'?'صنف':kind==='recipe'?'وصفة':'موظف'}</button>${kind==='employee'?'<button class="os-button" data-new="payroll">تسجيل صرف راتب</button>':''}</div><div class="os-grid" style="margin-top:18px">`+list.map(x=>`<article class="os-card"><h2>${esc(x.name)}</h2>${kind==='inventory'?`<p>${esc(x.quantity)} ${esc(x.unit)} · سعر الوحدة ${money(x.unit_price)}</p><strong class="os-kpi">${money(Number(x.quantity)*Number(x.unit_price))}</strong><p>${Number(x.quantity)<=Number(x.minimum_quantity)?'وصل الصنف إلى حد إعادة الطلب':'متوفر'}</p>`:kind==='recipe'?`<p>تكلفة المكونات ${money(x.cost)}</p><p>سعر البيع ${money(x.selling_price)}</p><p>الربح المتوقع ${money(Number(x.selling_price)-Number(x.cost))}</p><p>سعر مقترح لهامش ${esc(x.target_margin)}%: ${money(Number(x.cost)/(1-Number(x.target_margin)/100))}</p>`:`<p>${esc(x.job_title)}</p><strong class="os-kpi">${money(x.salary)}</strong><p>الراتب الأساسي؛ سجّل الصرف عند دفعه فعليًا.</p>`}<div class="os-actions"><button class="os-button" data-edit="${x.id}" data-kind="${kind}">تعديل</button>${kind==='inventory'?`<button class="os-button" data-stock="${x.id}">حركة مخزون</button>`:''}<button class="os-button danger" data-archive="${x.id}" data-kind="${kind}">أرشفة</button></div></article>`).join('')+'</div>';rows=list.map(x=>[x.name,x.quantity??x.cost??x.salary]);if(!list.length)body+='<p class="os-empty">ابدأ بإضافة أول سجل.</p>';}
 $('#financeBody').innerHTML=body;$('#financeBody').querySelectorAll('[data-new]').forEach(b=>b.onclick=()=>edit(b.dataset.new));$('#financeBody').querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(b.dataset.kind,find(b.dataset.edit)));$('#financeBody').querySelectorAll('[data-stock]').forEach(b=>b.onclick=()=>movement(find(b.dataset.stock)));$('#financeBody').querySelectorAll('[data-archive]').forEach(b=>b.onclick=()=>archive(b.dataset.kind,find(b.dataset.archive)));
}
function find(id){return [...snapshot.entries,...snapshot.inventory,...snapshot.recipes,...snapshot.employees].find(x=>x.id===id);}
function entryTable(list){return `<div class="os-table-wrap"><table class="os-table"><thead><tr><th>التاريخ</th><th>البيان</th><th>القيمة</th><th>الدفع</th><th>إجراءات</th></tr></thead><tbody>${list.map(e=>`<tr><td>${esc(e.occurred_on)}</td><td>${esc(e.title||e.reference)}</td><td>${money(e.amount)}</td><td>${esc(e.payment_method)}</td><td>${e.kind?`<button class="os-button" data-edit="${e.id}" data-kind="${e.kind}">تعديل</button><button class="os-button danger" data-archive="${e.id}" data-kind="${e.kind}">أرشفة</button>`:'طلب مدفوع'}</td></tr>`).join('')}</tbody></table></div>`;}
function dialog(title,body,submit){$('#financeDialog')?.remove();const el=document.createElement('dialog');el.id='financeDialog';el.className='os-dialog';el.innerHTML=`<header><h2>${esc(title)}</h2><button class="os-button" data-close aria-label="إغلاق">×</button></header><form id="financeForm" class="os-form">${body}<p id="formError" class="full os-error" hidden></p><div class="full os-actions"><button class="os-button primary" type="submit">حفظ</button></div></form>`;document.body.append(el);el.querySelector('[data-close]').onclick=()=>el.close();el.querySelector('form').onsubmit=async event=>{event.preventDefault();const button=el.querySelector('[type=submit]');button.disabled=true;try{await submit(Object.fromEntries(new FormData(event.target)));el.close();await load();}catch(e){$('#formError').hidden=false;$('#formError').textContent=e.message;}finally{button.disabled=false;}};el.showModal();return el;}
function field(name,label,value='',type='text',extra=''){return `<label class="os-field">${label}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;}
function choices(name,label,options,value){return `<label class="os-field">${label}<select name="${name}">${options.map(([v,l])=>`<option value="${esc(v)}" ${v===value?'selected':''}>${esc(l)}</option>`).join('')}</select></label>`;}
function edit(kind,row={}){let body=choices('branch_id','الفرع',[['','غير محدد'],...snapshot.branches.filter(b=>b.enabled).map(b=>[b.id,b.name])],row.branch_id||'');if(['inventory','recipe','employee'].includes(kind)){body+=field('name','الاسم',row.name||'','text','required maxlength="160"');if(kind==='inventory')body+=choices('unit','الوحدة',['kg','g','liter','ml','piece','box','pack','bottle'].map(x=>[x,x]),row.unit||'kg')+(!row.id?field('quantity','الرصيد الافتتاحي',0,'number','min="0" step="0.0001" required'):'')+field('unit_price','سعر شراء الوحدة',row.unit_price||0,'number','min="0" step="0.0001" required')+field('minimum_quantity','حد إعادة الطلب',row.minimum_quantity||0,'number','min="0" step="0.0001"');if(kind==='employee')body+=field('job_title','الوظيفة',row.job_title||'')+field('salary','الراتب الأساسي',row.salary||0,'number','min="0" step="0.01" required');if(kind==='recipe')body+=field('selling_price','سعر البيع',row.selling_price||0,'number','min="0" step="0.01" required')+field('target_margin','هامش الربح المستهدف %',row.target_margin??30,'number','min="0" max="99.99" step="0.01" required')+'<div class="full" id="ingredients"></div><button class="os-button full" type="button" id="addIngredient">إضافة مكوّن</button>';}
 else body+=field('title','البيان',row.title||'','text','required maxlength="160"')+field('category','التصنيف',row.category||'')+field('amount',kind==='closure'?'الرصيد المعدود عند الإغلاق':'المبلغ',row.amount||0,'number','min="0" step="0.01" required')+choices('payment_method','طريقة الدفع',[['cash','نقدي'],['card','بطاقة'],['instapay','إنستاباي'],['wallet','محفظة'],['other','أخرى']],row.payment_method||'cash')+field('occurred_on','التاريخ',row.occurred_on||$('#to').value,'date','required')+field('notes','ملاحظات',row.notes||'');
 let parts=(row.ingredients||[]).map(x=>({...x}));const el=dialog('حفظ البيانات',body,async data=>{if(kind==='recipe')data.ingredients=Array.from(el.querySelectorAll('[data-ingredient]')).map(node=>({item_id:node.querySelector('[name=item]').value,quantity:Number(node.querySelector('[name=qty]').value),unit:node.querySelector('[name=unit]').value}));await rpc('cfy_os_finance_mutate',{p_token:context.token,p_kind:kind,p_action:'save',p_data:{...data,id:row.id||null,version:row.version||1}});});
 if(kind==='recipe'){const add=part=>{const node=document.createElement('div');node.className='os-card';node.dataset.ingredient='';node.innerHTML=choices('item','المكوّن',live(snapshot.inventory).map(i=>[i.id,i.name]),part.item_id)+field('qty','الكمية',part.quantity||1,'number','min="0.0001" step="0.0001" required')+choices('unit','وحدة المكوّن',['kg','g','liter','ml','piece','box','pack','bottle'].map(u=>[u,u]),part.unit||'g')+'<button type="button" class="os-button danger">إزالة</button>';node.querySelector('button').onclick=()=>node.remove();$('#ingredients').append(node);};parts.forEach(add);$('#addIngredient').onclick=()=>add({});}
}
function movement(row){dialog('حركة مخزون — '+row.name,field('quantity_delta','الكمية: موجب للشراء، سالب للصرف',1,'number','step="0.0001" required')+field('unit_price','سعر شراء الوحدة',row.unit_price,'number','min="0" step="0.0001" required')+field('reason','السبب','','text','required maxlength="500"'),data=>rpc('cfy_os_finance_mutate',{p_token:context.token,p_kind:'inventory',p_action:'movement',p_data:{...data,id:row.id,version:row.version}}));}
function archive(kind,row){dialog('أرشفة السجل','<p class="full">سيُستبعد هذا السجل من الحسابات النشطة مع الاحتفاظ بتاريخه. تأكد من اختيار السجل الصحيح.</p>',()=>rpc('cfy_os_finance_mutate',{p_token:context.token,p_kind:kind,p_action:'archive',p_data:{id:row.id,version:row.version}}));}
