import {$,context,rpc,run,status,money,escapeHTML as esc} from './shared.js?v=20260913-1';
let page,snapshot,bucket='new',query='',type='',source='',timer;
const typeLabel=t=>({delivery:'توصيل',takeaway:'استلام',dinein:'داخل المطعم'})[t]||t;
const stateLabel=s=>({new:'جديد',preparing:'جاري التجهيز',ready:'جاهز',on_the_way:'في الطريق',delivered:'تم التوصيل',completed:'مكتمل',cancelled:'ملغي'})[s]||s;
export async function mountOperations(value){page=value;const title=page==='kitchen'?'المطبخ':page==='delivery'?'طلبات التوصيل':'محضّر الطلب';$('#osContent').innerHTML=`<div class="os-heading"><div><h1>${title}</h1><p>${page==='kitchen'?'الطلبات النشطة — تفاصيل واضحة للتحضير':page==='delivery'?'طلباتك المسندة إليك ومتابعة التسليم':'استلام الطلبات وتجهيزها وتسليمها'}</p></div><button class="os-button" id="refreshOps">تحديث</button></div><div id="shift"></div><div class="os-filters"><input class="os-search" id="orderSearch" placeholder="ابحث برقم الطلب أو اسم العميل أو الهاتف"><label class="os-field">نوع الطلب<select id="orderType"><option value="">جميع الأنواع</option><option value="delivery">توصيل</option><option value="takeaway">استلام</option><option value="dinein">داخل المطعم</option></select></label><label class="os-field">المصدر<select id="orderSource"><option value="">كل المصادر</option><option value="online">أونلاين</option><option value="pos">POS</option><option value="phone">هاتف</option></select></label></div><div class="os-actions" id="orderBuckets"></div><div id="ordersBoard" style="margin-top:18px"></div>`;
 $('#orderSearch').oninput=e=>{query=e.target.value;render();};$('#orderType').onchange=e=>{type=e.target.value;render();};$('#orderSource').onchange=e=>{source=e.target.value;render();};$('#refreshOps').onclick=e=>run(e.target,load);
 await load();if(page==='delivery'&&context.role==='delivery'&&context.shift_state==='offline'){await rpc('cfy_menu_staff_shift',{p_token:context.token,p_state:'available'});await load();}
 timer=setInterval(()=>{if(!document.querySelector('dialog[open]')&&!document.querySelector('#ordersBoard select:focus'))load().catch(()=>status('تعذر التحديث. البيانات قديمة؛ أعد الاتصال.',true));},15000);window.addEventListener('pagehide',()=>clearInterval(timer),{once:true});}
async function load(){snapshot=await rpc('cfy_os_operational_snapshot',{p_token:context.token,p_page:page});render();status('');}
function items(order){return (order.items||[]).map(i=>{const s=i.snapshot||{};return `<div style="padding:9px 0;border-bottom:1px solid var(--os-line)"><b>${Number(i.quantity)} × ${esc(s.product?.name_ar||s.product?.name_en||'منتج')}</b><div class="os-muted">${esc([s.variant?.name,...(s.options||[]).map(x=>x.name),s.notes].filter(Boolean).join(' · '))}</div></div>`;}).join('');}
function group(order){if(['completed','cancelled','delivered','on_the_way'].includes(order.status)||(order.order_type==='delivery'&&order.assigned_driver_id))return 'done';if(order.status==='new')return 'new';return 'preparing';}
function render(){if(!snapshot)return;const a=snapshot.orders||[];if(page==='prep'){$('#orderBuckets').innerHTML=[['new','جديد'],['preparing','جاري التجهيز'],['done','مكتمل / تم التسليم']].map(([id,title])=>`<button class="os-button ${bucket===id?'primary':''}" data-bucket="${id}">${title} (${a.filter(o=>group(o)===id).length})</button>`).join('');$('#orderBuckets').querySelectorAll('button').forEach(b=>b.onclick=()=>{bucket=b.dataset.bucket;render();});}
 if(page==='delivery'&&context.role==='delivery'){$('#shift').innerHTML=`<section class="os-card" style="margin-bottom:18px"><b>حالة الشيفت: ${esc(({available:'متاح',paused:'إيقاف مؤقت',offline:'منتهي'})[snapshot.actor.shift_state]||'')}</b><div class="os-actions"><button class="os-button good" data-shift="available">متاح</button><button class="os-button" data-shift="paused">إيقاف مؤقت</button><button class="os-button danger" data-shift="offline">إنهاء الشيفت</button></div></section>`;$('#shift').querySelectorAll('[data-shift]').forEach(b=>b.onclick=()=>run(b,async()=>{await rpc('cfy_menu_staff_shift',{p_token:context.token,p_state:b.dataset.shift});await load();}));}
 const orders=a.filter(o=>(page!=='prep'||group(o)===bucket)&&(page!=='kitchen'||['new','preparing'].includes(o.status))&&(!type||o.order_type===type)&&(!source||o.order_source===source)&&(!query||[o.reference,o.customer_name,o.phone].join(' ').toLowerCase().includes(query.toLowerCase())));
 $('#ordersBoard').className=page==='kitchen'?'os-kitchen':'os-grid';$('#ordersBoard').innerHTML=orders.length?orders.map(o=>{const age=Math.max(0,Math.floor((Date.now()-new Date(o.created_at))/60000));return `<article class="os-card" data-order="${o.id}"><div class="os-heading"><b>${esc(o.reference)}</b><span class="os-badge">${stateLabel(o.status)}</span></div><p>${typeLabel(o.order_type)} · ${esc(o.order_source)} · منذ ${age} دقيقة</p><button class="os-button" data-details="${o.id}">${esc(o.customer_name||o.table_label||'تفاصيل الطلب')}</button>${items(o)}${o.notes?`<p>ملاحظات: ${esc(o.notes)}</p>`:''}${page!=='kitchen'?`<strong class="os-kpi">${money(o.total)}</strong><p>${esc(o.payment_method)} · ${o.payment_status==='paid'?'مدفوع':'غير مدفوع'}</p>`:''}${o.issue_open?`<p class="os-error">${esc(o.issue_text||'يوجد بلاغ يحتاج متابعة')}</p>`:''}<div class="os-actions">${actions(o)}</div></article>`;}).join(''):'<p class="os-empty">لا توجد طلبات في هذه الحالة.</p>';
 $('#ordersBoard').querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>perform(b.closest('[data-order]').dataset.order,b.dataset.action,b));$('#ordersBoard').querySelectorAll('[data-details]').forEach(b=>b.onclick=()=>details(a.find(o=>o.id===b.dataset.details)));}
function actions(o){const button=(act,title)=>`<button class="os-button ${['ready','delivered','complete'].includes(act)?'primary':''}" data-action="${act}">${title}</button>`;let h='';if(page==='delivery'){if(o.status==='ready')h+=button('picked_up','استلمت الطلب من المطعم');if(o.status==='on_the_way')h+=button('delivered','تأكيد التسليم')+button('delivery_exception','تعذر الوصول إلى OTP');if(!['completed','cancelled'].includes(o.status))h+=button('issue','تسجيل مشكلة');return h;}
 if(o.status==='new')h+=button('accept','استلام وبدء التجهيز');if(o.status==='preparing')h+=button('ready','تم التحضير');if(page==='prep'&&o.status==='ready'){if(o.order_type==='delivery')h+=`<select class="os-search" data-driver><option value="">اقتراح تلقائي</option>${snapshot.drivers.filter(d=>d.shift_state==='available').map(d=>`<option value="${d.id}">${esc(d.name)}</option>`).join('')}</select>`+button('assign_driver','إسناد وتسليم للمندوب');else h+=button('complete','تم الاستلام وإغلاق الطلب');}if(page==='prep'&&o.status==='delivered')h+=button('complete','إغلاق الطلب');h+=button('print','طباعة');return h;}
function modal(title,body,onSubmit){$('#operationDialog')?.remove();const d=document.createElement('dialog');d.id='operationDialog';d.className='os-dialog';d.innerHTML=`<header><h2>${esc(title)}</h2><button class="os-button" data-close>×</button></header><form>${body}<p class="os-error" id="operationError" hidden></p>${onSubmit?'<button class="os-button primary" type="submit">تأكيد</button>':''}</form>`;document.body.append(d);d.querySelector('[data-close]').onclick=()=>d.close();if(onSubmit)d.querySelector('form').onsubmit=async e=>{e.preventDefault();const b=d.querySelector('[type=submit]');b.disabled=true;try{await onSubmit(Object.fromEntries(new FormData(e.target)));d.close();await load();}catch(err){$('#operationError').hidden=false;$('#operationError').textContent=err.message.includes('invalid_otp')?'رمز التسليم غير صحيح. اطلب الرمز من العميل.':err.message;}finally{b.disabled=false;}};d.showModal();return d;}
function details(o){const phone=String(o.phone||'').replace(/[^+\d]/g,''),wa=phone.replace(/^0/,'20').replace(/^\+/,'');modal('تفاصيل '+o.reference,`<h3>${esc(o.customer_name||o.table_label||'طلب مطعم')}</h3><p>${esc(o.phone)}</p><p>${esc(o.address)}</p><div class="os-actions">${phone?`<a class="os-button" href="tel:${esc(phone)}">اتصال</a><a class="os-button" target="_blank" rel="noopener" href="https://wa.me/${esc(wa)}">واتساب</a>`:''}${o.address?`<a class="os-button" target="_blank" rel="noopener" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(o.address)}">فتح الخريطة</a>`:''}</div>${items(o)}<p>${esc(o.notes||'لا توجد ملاحظات')}</p><b>${money(o.total)}</b><p>${esc(o.payment_method)} · ${esc(o.payment_status)}</p><p class="os-muted">المسافة غير متاحة دون إحداثيات مؤكدة.</p>`);}
async function perform(id,action,button){const send=data=>rpc('cfy_os_order_action',{p_token:context.token,p_page:page,p_order_id:id,p_action:action,p_data:data});if(action==='print'){const o=snapshot.orders.find(x=>x.id===id);const w=window.open('','_blank');if(!w){status('المتصفح منع نافذة الطباعة. اسمح بها ثم أعد المحاولة.',true);return;}w.document.write(`<!doctype html><html lang="ar" dir="rtl"><head><title>${esc(o.reference)}</title></head><body><h2>${esc(o.reference)}</h2><p>${typeLabel(o.order_type)}</p>${items(o)}<p>${esc(o.notes||'')}</p><b>${money(o.total)}</b></body></html>`);w.document.close();w.print();status('تم فتح حوار الطباعة. تحقق من خروج الورقة على الطابعة.');return;}
 if(action==='delivered')return modal('تأكيد التسليم','<label class="os-field">رمز العميل<input name="otp" inputmode="numeric" autocomplete="off" required minlength="4" maxlength="8"></label><p>أدخل الرمز بعد تسليم الطلب للعميل فقط.</p>',send);
 if(action==='delivery_exception')return modal('تعذر الوصول إلى OTP','<p>سيُرسل للعميل طلب تأكيد استلام داخل متابعة الطلب. لن يغلق الطلب نهائيًا قبل رده.</p><label class="os-field">سبب الاستثناء<textarea name="reason" required minlength="5" maxlength="500"></textarea></label><label><input name="confirmed" type="checkbox" value="true" required> سلمت الطلب للعميل وأؤكد تسجيل الاستثناء.</label>',send);
 if(action==='issue')return modal('تسجيل مشكلة','<label class="os-field">وصف المشكلة<textarea name="text" required maxlength="1000"></textarea></label>',send);
 await run(button,async()=>{await send(action==='assign_driver'?{driver_id:button.closest('[data-order]').querySelector('[data-driver]').value}:{});await load();});}
