import {$,context,rpc,run,status,money,escapeHTML as esc} from './shared.js?v=20260920-pos-ui';
import {customerHandoff} from './customer-handoff.mjs?v=20260920-pos-ui';

let page,snapshot,lines=[],category='',query='',selectedId='',requestKey=crypto.randomUUID(),pending=false,deliveryAllowed=false;
const draftKey=()=>`cardfy_os_pos_draft:${context.client_id}:${context.id||'owner'}:${page}`;
const safeImage=url=>/^https:\/\//i.test(String(url||''))?url:'';
const product=id=>snapshot.catalog.products.find(p=>p.id===id);
const productName=p=>p?.name_ar||p?.name_en||'منتج';
const variant=(p,id)=>p?.variants?.find(v=>v.id===id)||null;
const options=line=>(product(line.product_id)?.option_groups||[]).flatMap(g=>g.options.filter(o=>(line.option_ids||[]).includes(o.id)));
const unit=line=>Number(variant(product(line.product_id),line.variant_id)?.price??product(line.product_id)?.base_price??0)+options(line).reduce((n,o)=>n+Number(o.price_delta||0),0);
const signature=line=>[line.product_id,line.variant_id||'',...(line.option_ids||[]).slice().sort(),String(line.notes||'').trim()].join('|');
const subtotal=()=>lines.reduce((n,l)=>n+unit(l)*Number(l.quantity||0),0);
const selected=()=>lines.find(l=>l.id===selectedId)||null;
const zone=()=>snapshot.catalog.delivery_zones?.find(z=>z.id===$('#posMeta [name="delivery_zone_id"]')?.value)||null;
const deliveryFee=()=>$('#posMeta [name="order_type"]')?.value==='delivery'?Number(zone()?.fee||0):0;

function makeLine(p){const v=p.variant_required?p.variants?.[0]:null,ids=[];for(const g of p.option_groups||[]){const min=Math.max(g.required?1:0,Number(g.min_select||0));ids.push(...g.options.slice(0,min).map(o=>o.id));}return{id:crypto.randomUUID(),product_id:p.id,quantity:1,variant_id:v?.id||'',option_ids:ids,notes:''};}
function merge(preferred=''){const next=[];for(const line of lines){const twin=next.find(x=>signature(x)===signature(line));if(twin){twin.quantity+=line.quantity;if(line.id===preferred)selectedId=twin.id;}else next.push(line);}lines=next;}
function saveDraft(){const form=$('#posMeta');sessionStorage.setItem(draftKey(),JSON.stringify({lines,form:form?Object.fromEntries(new FormData(form)):null}));requestKey=crypto.randomUUID();}
function restoreDraft(){try{const d=JSON.parse(sessionStorage.getItem(draftKey())||'{}');lines=Array.isArray(d.lines)?d.lines:[];return d.form||null;}catch{lines=[];return null;}}

export async function mountPOS(value){
 document.body.classList.add('pos-active');page=value;snapshot=await rpc('cfy_os_operational_snapshot',{p_token:context.token,p_page:page});const c=snapshot.catalog;deliveryAllowed=Boolean(c.settings.delivery_enabled);
 $('#osContent').innerHTML=`<section class="pos-view" aria-labelledby="posTitle"><div class="pos-title"><div><p>نقطة بيع الطلبات الخارجية</p><h1 id="posTitle">التوصيل والاستلام</h1></div><span class="pos-live">● متصل بالنظام</span></div><div class="pos-layout"><section class="pos-catalog"><div class="pos-hero"><b>طلبات أسرع، تفاصيل أوضح</b><span>اختر المنتج ثم اضبط الحجم والإضافات من الطلب الحالي.</span></div><label class="pos-search"><span>⌕</span><input id="productSearch" type="search" placeholder="ابحث عن منتج أو صنف…"></label><div id="posCategories" class="pos-categories"></div><div id="posProducts" class="pos-products"></div></section><aside class="pos-order"><div class="pos-mode"><span>نوع الطلب</span><div>${deliveryAllowed?'<button data-type="delivery">توصيل</button>':''}<button data-type="takeaway">استلام من المطعم</button></div></div><div class="pos-order-head"><h2>الطلب الحالي <span id="posCount"></span></h2><button id="clearPOS" class="pos-link pos-danger">حذف الكل</button></div><div id="posLines" class="pos-lines"></div><div id="posEditor"></div><form id="posMeta" class="pos-meta"><input type="hidden" name="order_type" value="${deliveryAllowed?'delivery':'takeaway'}"><label>المصدر<select name="source"><option value="pos">POS</option><option value="phone">هاتف</option></select></label><label>الفرع<select name="branch_id"><option value="">اختر الفرع</option>${snapshot.branches.map(b=>`<option value="${b.id}">${esc(b.name)}</option>`).join('')}</select></label><label>طريقة الدفع<select name="payment_method">${(c.settings.payment_methods||['cash']).map(v=>`<option value="${esc(v)}">${esc(({cash:'نقدي',card_at_venue:'بطاقة عند المطعم',pay_on_delivery:'عند الاستلام'})[v]||v)}</option>`).join('')}</select></label><label>اسم العميل<input name="customer_name" maxlength="120" placeholder="اختياري للاستلام"></label><label>الموبايل<input name="phone" inputmode="tel" maxlength="30" placeholder="رقم العميل"></label><input type="hidden" name="delivery_zone_id"><input type="hidden" name="address"><label class="pos-notes">ملاحظات الطلب<input name="notes" maxlength="500" placeholder="ملاحظات على الطلب…"></label></form><button id="addressPOS" class="pos-address" type="button"><span>⌖</span><span><b>بيانات وعنوان التوصيل</b><small id="addressSummary">أضف العميل والمنطقة والعنوان</small></span></button><div id="posQuote" class="pos-summary"></div><button id="completePOS" class="pos-complete" type="button">✓ إتمام الطلب</button><button id="draftPOS" class="pos-secondary" type="button">حفظ المسودة على هذا الجهاز</button><p class="pos-hint">يُرسل الطلب إلى محضّر الطلب أولًا. لا يتم تسجيل الدفع إلا بعد التحصيل الفعلي.</p></aside></div></section>`;
 if(snapshot.branches.length===1)$('#posMeta [name="branch_id"]').value=snapshot.branches[0].id;
 const restored=restoreDraft();if(restored)for(const[name,value]of Object.entries(restored)){const field=$(`#posMeta [name="${CSS.escape(name)}"]`);if(field)field.value=value;}if(!deliveryAllowed)setType('takeaway');
 $('#productSearch').oninput=e=>{query=e.target.value;renderProducts();};$('#posMeta').onchange=e=>{if(e.target.name==='branch_id'){$('#posMeta [name="delivery_zone_id"]').value='';renderAddress();}saveDraft();renderSummary();};$('#posMeta').oninput=saveDraft;document.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>setType(b.dataset.type));$('#clearPOS').onclick=()=>{lines=[];selectedId='';saveDraft();renderCart();};$('#addressPOS').onclick=openAddress;$('#draftPOS').onclick=()=>{saveDraft();status('تم حفظ المسودة على هذا الجهاز.');};$('#completePOS').onclick=e=>complete(e.currentTarget);renderCategories();renderProducts();renderCart();renderAddress();status('');
}
function setType(type){if(type==='delivery'&&!deliveryAllowed)return;$('#posMeta [name="order_type"]').value=type;if(type!=='delivery'){$('#posMeta [name="delivery_zone_id"]').value='';$('#posMeta [name="address"]').value='';}saveDraft();renderAddress();renderSummary();document.querySelectorAll('[data-type]').forEach(b=>b.classList.toggle('active',b.dataset.type===type));}
function renderCategories(){$('#posCategories').innerHTML=[['','الكل'],...snapshot.catalog.categories.map(c=>[c.id,c.name_ar||c.name_en])].map(([id,title])=>`<button class="${id===category?'active':''}" data-category="${id}">${esc(title)}</button>`).join('');$('#posCategories').querySelectorAll('button').forEach(b=>b.onclick=()=>{category=b.dataset.category;renderCategories();renderProducts();});}
function renderProducts(){const visible=snapshot.catalog.products.filter(p=>p.available&&(!category||p.category_id===category)&&(!query||`${p.name_ar||''} ${p.name_en||''}`.toLowerCase().includes(query.trim().toLowerCase())));$('#posProducts').innerHTML=visible.length?visible.map(p=>{const image=safeImage(p.image_url);return`<button class="pos-product" data-product="${p.id}">${image?`<img src="${esc(image)}" alt="${esc(productName(p))}" loading="lazy">`:'<span class="pos-product-placeholder">🍽</span>'}<span class="pos-product-copy"><b>${esc(productName(p))}</b><strong>${money(p.base_price)}</strong></span><i>＋</i></button>`;}).join(''):'<p class="os-empty">لا توجد منتجات مطابقة.</p>';$('#posProducts').querySelectorAll('[data-product]').forEach(b=>b.onclick=()=>addProduct(product(b.dataset.product)));}
function addProduct(p){const line=makeLine(p),twin=lines.find(x=>signature(x)===signature(line));if(twin){twin.quantity++;selectedId=twin.id;}else{lines.push(line);selectedId=line.id;}saveDraft();renderCart();}
function renderCart(){const count=lines.reduce((n,l)=>n+Number(l.quantity||0),0);$('#posCount').textContent=count?`(${count})`:'';$('#clearPOS').disabled=!lines.length;$('#posLines').innerHTML=lines.length?lines.map(l=>{const p=product(l.product_id),v=variant(p,l.variant_id),opts=options(l),image=safeImage(p?.image_url);return`<article class="pos-line ${l.id===selectedId?'active':''}" data-line="${l.id}" tabindex="0">${image?`<img src="${esc(image)}" alt="">`:'<span class="pos-line-placeholder">🍽</span>'}<div><b>${esc(productName(p))}</b><small>${esc([v?.name,...opts.map(o=>o.name),l.notes].filter(Boolean).join(' • ')||'اضغط لتعديل الإضافات')}</small><strong>${money(unit(l)*l.quantity)}</strong></div><div class="pos-qty"><button data-delta="1" aria-label="زيادة الكمية">＋</button><span>${l.quantity}</span><button data-delta="-1" aria-label="تقليل الكمية">−</button><button class="pos-remove" data-remove aria-label="حذف المنتج">×</button></div></article>`;}).join(''):'<div class="pos-empty">أضف منتجات لبدء الطلب</div>';$('#posLines').querySelectorAll('[data-line]').forEach(card=>{card.onclick=()=>{selectedId=selectedId===card.dataset.line?'':card.dataset.line;renderCart();};card.onkeydown=e=>{if(e.key==='Enter')card.click();};card.querySelectorAll('button').forEach(b=>b.onclick=e=>{e.stopPropagation();const line=lines.find(x=>x.id===card.dataset.line);if(b.hasAttribute('data-remove'))lines=lines.filter(x=>x.id!==line.id);else{line.quantity+=Number(b.dataset.delta);if(line.quantity<=0)lines=lines.filter(x=>x.id!==line.id);}if(!lines.some(x=>x.id===selectedId))selectedId='';saveDraft();renderCart();});});renderEditor();renderSummary();}
function renderEditor(){const line=selected(),p=product(line?.product_id),host=$('#posEditor');if(!line||!p){host.innerHTML='';return;}host.innerHTML=`<section class="pos-editor"><header><div><b>${esc(productName(p))}</b><span>الإضافات والاختيارات</span></div><button id="closeEditor" aria-label="إغلاق">×</button></header>${p.variants?.length?`<fieldset><legend>الحجم ${p.variant_required?'<em>مطلوب</em>':''}</legend><div>${p.variants.map(v=>`<button class="${line.variant_id===v.id?'active':''}" data-variant="${v.id}">${esc(v.name)} <small>${money(v.price)}</small></button>`).join('')}</div></fieldset>`:''}${(p.option_groups||[]).map(g=>`<fieldset><legend>${esc(g.name)} <em>${g.required||Number(g.min_select)>0?'مطلوب':'اختياري'}</em></legend><div>${g.options.map(o=>`<button class="${line.option_ids.includes(o.id)?'active':''}" data-option="${o.id}" data-group="${g.id}">${esc(o.name)} <small>${Number(o.price_delta)>0?'+'+money(o.price_delta):money(0)}</small></button>`).join('')}</div></fieldset>`).join('')}<label>ملاحظات الصنف<input id="lineNotes" maxlength="300" value="${esc(line.notes||'')}" placeholder="مثال: بدون بصل"></label></section>`;$('#closeEditor').onclick=()=>{selectedId='';renderCart();};host.querySelectorAll('[data-variant]').forEach(b=>b.onclick=()=>updateLine(line.id,l=>l.variant_id=b.dataset.variant));host.querySelectorAll('[data-option]').forEach(b=>b.onclick=()=>updateLine(line.id,l=>{const g=p.option_groups.find(x=>x.id===b.dataset.group),ids=new Set(l.option_ids||[]),groupIds=new Set(g.options.map(o=>o.id));if(ids.has(b.dataset.option))ids.delete(b.dataset.option);else{if(Number(g.max_select||1)===1)for(const id of groupIds)ids.delete(id);if([...ids].filter(id=>groupIds.has(id)).length>=Number(g.max_select||1))return;ids.add(b.dataset.option);}l.option_ids=[...ids];}));$('#lineNotes').onchange=e=>updateLine(line.id,l=>l.notes=e.target.value);}
function updateLine(id,change){const line=lines.find(l=>l.id===id);if(!line)return;change(line);merge(id);saveDraft();renderCart();}
function renderAddress(){const delivery=$('#posMeta [name="order_type"]')?.value==='delivery';$('#addressPOS').hidden=!delivery;document.querySelectorAll('[data-type]').forEach(b=>b.classList.toggle('active',b.dataset.type===$('#posMeta [name="order_type"]').value));if(delivery){const name=$('#posMeta [name="customer_name"]').value,address=$('#posMeta [name="address"]').value;$('#addressSummary').textContent=address?`${name||'العميل'} · ${zone()?.name||'بدون منطقة'} · ${address}`:'أضف العميل والمنطقة والعنوان';}}
function openAddress(){const form=$('#posMeta'),branch=form.elements.branch_id.value,zones=(snapshot.catalog.delivery_zones||[]).filter(z=>!branch||!z.branch_id||z.branch_id===branch);$('#posAddressDialog')?.remove();const d=document.createElement('dialog');d.id='posAddressDialog';d.className='os-dialog pos-dialog';d.innerHTML=`<header><div><h2>بيانات التوصيل</h2><p>أضف بيانات العميل والعنوان لهذا الطلب.</p></div><button class="os-button" data-close>×</button></header><form class="pos-address-form"><label>اسم العميل<input name="customer_name" required maxlength="120" value="${esc(form.elements.customer_name.value)}"></label><label>رقم الهاتف<input name="phone" required inputmode="tel" maxlength="30" value="${esc(form.elements.phone.value)}"></label><label>المنطقة<select name="delivery_zone_id" required><option value="">اختر المنطقة</option>${zones.map(z=>`<option value="${z.id}" ${z.id===form.elements.delivery_zone_id.value?'selected':''}>${esc(z.name)} — ${money(z.fee)}</option>`).join('')}</select></label><label>العنوان بالتفصيل<input name="address" required maxlength="500" value="${esc(form.elements.address.value)}"></label><button class="pos-complete" type="submit">حفظ بيانات التوصيل</button></form>`;document.body.append(d);d.querySelector('[data-close]').onclick=()=>d.close();d.querySelector('form').onsubmit=e=>{e.preventDefault();for(const[name,value]of Object.entries(Object.fromEntries(new FormData(e.target))))form.elements[name].value=value;saveDraft();renderAddress();renderSummary();d.close();};d.showModal();}
function renderSummary(q=null){const sub=q?Number(q.products_subtotal||0):subtotal(),fee=q?Number(q.delivery_fee||0):deliveryFee(),discount=q?Number(q.product_discount||0)+Number(q.coupon_discount||0):0,total=q?Number(q.total||0):sub+fee;$('#posQuote').innerHTML=`<div><span>المجموع الفرعي</span><b>${money(sub)}</b></div>${fee||$('#posMeta [name="order_type"]')?.value==='delivery'?`<div><span>رسوم التوصيل${zone()?` — ${esc(zone().name)}`:''}</span><b>${money(fee)}</b></div>`:''}${discount?`<div><span>الخصومات</span><b>− ${money(discount)}</b></div>`:''}<div class="total"><span>الإجمالي</span><b>${money(total)}</b></div>`;}
function validateLine(line){const p=product(line.product_id);if(p.variant_required&&!variant(p,line.variant_id))return`اختر الحجم للمنتج ${productName(p)}.`;for(const g of p.option_groups||[]){const count=g.options.filter(o=>line.option_ids.includes(o.id)).length,min=Math.max(g.required?1:0,Number(g.min_select||0)),max=Number(g.max_select||1);if(count<min||count>max)return`راجع اختيارات ${g.name} للمنتج ${productName(p)}.`;}return'';}
function payload(){const p=Object.fromEntries(new FormData($('#posMeta')));if(p.order_type!=='delivery'){p.delivery_zone_id='';p.address='';}return{...p,table_id:'',coupon_code:'',items:lines.map(({product_id,quantity,variant_id,option_ids,notes})=>({product_id,quantity,variant_id,option_ids,notes}))};}
async function quote(){if(!lines.length)throw new Error('أضف منتجات أولًا.');const q=await rpc('cfy_os_pos_quote',{p_token:context.token,p_page:page,p_order:payload()});renderSummary(q);return q;}
async function complete(button){if(pending)return;const invalid=lines.map(l=>({id:l.id,error:validateLine(l)})).find(x=>x.error);if(invalid){selectedId=invalid.id;renderCart();status(invalid.error,true);return;}const data=payload();if(data.order_type==='delivery'&&(!data.customer_name.trim()||!data.phone.trim()||!data.delivery_zone_id||!data.address.trim())){status('أكمل بيانات العميل والمنطقة والعنوان قبل إتمام الطلب.',true);openAddress();return;}pending=true;try{await run(button,async()=>{await quote();const r=await rpc('cfy_os_pos_order',{p_token:context.token,p_page:page,p_order:payload(),p_intent:'save',p_request_key:requestKey});status(`تم إنشاء ${r.reference} وإرساله إلى محضّر الطلب — ${money(r.total)}`);lines=[];selectedId='';sessionStorage.removeItem(draftKey());requestKey=crypto.randomUUID();renderCart();receipt(r);});}finally{pending=false;}}
function receipt(r){const d=document.createElement('dialog');d.className='os-dialog pos-dialog';d.innerHTML=`<h2>تم حفظ الطلب</h2><p>${esc(r.reference)} — ${money(r.total)}</p><p>حالة الطلب: جديد لدى محضّر الطلب</p>${customerHandoff(r)}<button class="pos-complete primary" type="button">طباعة الإيصال</button><button class="pos-secondary" data-close type="button">إغلاق</button>`;document.body.append(d);d.querySelector('[data-close]').onclick=()=>d.close();d.querySelector('.pos-complete').onclick=()=>{const w=window.open('','_blank');if(!w){status('اسمح بنافذة الطباعة وأعد المحاولة.',true);return;}w.document.write(`<html lang="ar" dir="rtl"><title>${esc(r.reference)}</title><h2>${esc(r.reference)}</h2>${(r.order?.items||[]).map(i=>`<p>${Number(i.quantity)} × ${esc(i.snapshot?.product?.name_ar||'منتج')} — ${money(i.line_total)}</p>`).join('')}<b>${money(r.total)}</b>${customerHandoff(r)}</html>`);w.document.close();w.print();};d.showModal();}
