const sb=window.supabase.createClient('https://ytixcczbjmjnuotzavbb.supabase.co','sb_publishable_0j9jf0boDrMGGO8S6mw-4Q_5bOeHIuU');const TOKEN='cardfy_menu_staff_token_v1',$=s=>document.querySelector(s);let token='',staff=null,snap=null,catalog=null,category='all',query='',lines=[],selected=null,selVariant=null,selOptions=new Set(),orderType='takeaway';
const safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const money=v=>Number(v||0).toLocaleString('ar-EG',{maximumFractionDigits:2})+' '+(catalog?.settings?.currency==='EGP'?'ج.م':catalog?.settings?.currency||'EGP');function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('on');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('on'),2000)}
function lineKey(p,v,os,n=''){return[p.id,v?.id||'',os.map(x=>x.id).sort().join(','),n].join('|')}function unit(p,v,os){return Number(v?.price??p.base_price??0)+os.reduce((a,o)=>a+Number(o.price_delta||0),0)}function addLine(p,v=null,os=[],notes=''){const key=lineKey(p,v,os,notes),u=unit(p,v,os),x=lines.find(l=>l.key===key);if(x)x.qty++;else lines.push({key,product:p,variant:v,options:os,notes,unit:u,qty:1});renderOrder();renderProducts()}
function products(){let a=(catalog.products||[]).filter(p=>p.available!==false);if(category!=='all')a=a.filter(p=>p.category_id===category);if(query){const q=query.toLowerCase();a=a.filter(p=>`${p.name_ar||''} ${p.name_en||''}`.toLowerCase().includes(q))}return a}
function renderCats(){$('#cats').innerHTML=`<button class="${category==='all'?'active':''}" data-c="all">الكل</button>`+(catalog.categories||[]).map(c=>`<button class="${category===c.id?'active':''}" data-c="${c.id}">${safe(c.name_ar||c.name_en)}</button>`).join('');$('#cats').querySelectorAll('button').forEach(b=>b.onclick=()=>{category=b.dataset.c;renderCats();renderProducts()})}
function renderProducts(){$('#products').innerHTML=products().map(p=>`<button class="pos-product ${selected?.id===p.id?'selected':''}" data-p="${p.id}"><div class="pos-img" ${p.image_url?`style="background-image:url('${safe(p.image_url).replace(/'/g,'%27')}')"`:''}></div><strong>${safe(p.name_ar||p.name_en)}</strong><small>${money(p.base_price)}</small></button>`).join('');$('#products').querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>tap(b.dataset.p))}
function tap(id){const p=(catalog.products||[]).find(x=>x.id===id);if(!p)return;selected=p;selVariant=null;selOptions=new Set();if(!(p.variants||[]).length&&!(p.option_groups||[]).length){addLine(p);selected=null;renderPanel();return}renderProducts();renderPanel()}
function renderPanel(){const h=$('#addonsPanel'),p=selected;if(!p){h.innerHTML='<div class="panel-empty">اختَر منتجًا لعرض الاختيارات.</div>';return}h.innerHTML=`<div class="addon-title">${safe(p.name_ar||p.name_en)}</div>${(p.variants||[]).length?`<div class="addon-title">الحجم</div><div class="variant-grid">${p.variants.map(v=>`<button class="addon-tile ${selVariant?.id===v.id?'on':''}" data-v="${v.id}">${safe(v.name)}<small>${money(v.price)}</small></button>`).join('')}</div>`:''}${(p.option_groups||[]).map(g=>`<div class="addon-title">${safe(g.name)} ${g.required?'*':''}</div><div class="addon-grid">${(g.options||[]).map(o=>`<button class="addon-tile ${selOptions.has(o.id)?'on':''}" data-o="${o.id}" data-g="${g.id}">${safe(o.name)}<small>${Number(o.price_delta)?'+'+money(o.price_delta):'بدون زيادة'}</small></button>`).join('')}</div>`).join('')}<textarea id="itemNotes" style="width:100%;margin-top:10px;border:1px solid #e2e5ea;border-radius:10px;padding:9px" placeholder="ملاحظات الصنف"></textarea><div id="panelError" class="panel-note"></div><button id="panelAdd" class="panel-add">إضافة للطلب</button>`;h.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{selVariant=(p.variants||[]).find(v=>v.id===b.dataset.v);renderPanel()});h.querySelectorAll('[data-o]').forEach(b=>b.onclick=()=>toggleOption(b.dataset.g,b.dataset.o));$('#panelAdd').onclick=confirmProduct}
function toggleOption(gid,oid){const g=(selected.option_groups||[]).find(x=>x.id===gid);if(!g)return;const ids=(g.options||[]).map(x=>x.id),picked=ids.filter(x=>selOptions.has(x));if(selOptions.has(oid))selOptions.delete(oid);else{if(Number(g.max_select||1)===1)picked.forEach(x=>selOptions.delete(x));else if(picked.length>=Number(g.max_select||1)){toast('وصلت للحد الأقصى');return}selOptions.add(oid)}renderPanel()}
function confirmProduct(){const p=selected;if(p.variant_required&&!selVariant){$('#panelError').textContent='اختر الحجم أولًا';return}let os=[];for(const g of p.option_groups||[]){const x=(g.options||[]).filter(o=>selOptions.has(o.id)),min=Math.max(Number(g.min_select||0),g.required?1:0),max=Number(g.max_select||1);if(x.length<min){$('#panelError').textContent=`اختر ${min} على الأقل من ${g.name}`;return}if(x.length>max){$('#panelError').textContent=`الحد الأقصى ${max}`;return}os.push(...x)}addLine(p,selVariant,os,$('#itemNotes')?.value.trim()||'');selected=null;renderPanel();renderProducts()}
function renderOrder(){$('#orderLines').innerHTML=lines.length?lines.map((l,i)=>`<div class="pos-line"><div class="line-main"><b>#${i+1} ${safe(l.product.name_ar||l.product.name_en)}</b><strong>${money(l.unit*l.qty)}</strong></div><div class="line-custom">${l.variant?safe(l.variant.name):''}${l.options.length?' · '+l.options.map(o=>safe(o.name)).join('، '):''}${l.notes?' · '+safe(l.notes):''}</div><div class="line-actions"><div class="qty"><button data-plus="${i}">+</button><b>${l.qty}</b><button data-minus="${i}">−</button></div><button class="remove" data-remove="${i}">حذف</button></div></div>`).join(''):'<div class="panel-empty">لم تضف أصنافًا بعد.</div>';$('#orderLines').querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>{lines[+b.dataset.plus].qty++;renderOrder()});$('#orderLines').querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>{const i=+b.dataset.minus;if(lines[i].qty>1)lines[i].qty--;else lines.splice(i,1);renderOrder();renderProducts()});$('#orderLines').querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{lines.splice(+b.dataset.remove,1);renderOrder();renderProducts()});$('#total').textContent=money(lines.reduce((a,l)=>a+l.unit*l.qty,0));$('#lineCount').textContent=lines.reduce((a,l)=>a+l.qty,0)}
function types(){const s=catalog.settings||{},a=[];if(s.delivery_enabled)a.push('delivery');if(s.takeaway_enabled)a.push('takeaway');if(s.dinein_enabled)a.push('dinein');return a}function typeLabel(t){return t==='delivery'?'توصيل':t==='takeaway'?'استلام':'داخل المطعم'}function renderTypes(){const a=types();if(!a.includes(orderType))orderType=a[0]||'';$('#types').innerHTML=a.map(t=>`<button class="${orderType===t?'active':''}" data-t="${t}">${typeLabel(t)}</button>`).join('');$('#types').querySelectorAll('button').forEach(b=>b.onclick=()=>{orderType=b.dataset.t;renderTypes()});const del=orderType==='delivery',din=orderType==='dinein';$('#tableSelect').hidden=!din;$('#customerName').hidden=din;$('#phone').hidden=din;$('#address').hidden=!del;$('#zone').hidden=!del}
function payload(){return{order_type:orderType,table_id:$('#tableSelect').value,customer_name:$('#customerName').value.trim(),phone:$('#phone').value.trim(),address:$('#address').value.trim(),delivery_zone_id:$('#zone').value,items:lines.map(l=>({product_id:l.product.id,quantity:l.qty,variant_id:l.variant?.id||'',option_ids:l.options.map(o=>o.id),notes:l.notes}))}}
async function send(){if(!lines.length){toast('الطلب فارغ');return}if(orderType==='dinein'&&!$('#tableSelect').value){toast('اختر الترابيزة');return}const b=$('#sendOrder');b.disabled=true;$('#status').textContent='جاري الحفظ...';const r=await sb.rpc('cfy_menu_staff_create_order',{p_token:token,p_source:$('#source').value,p_order:payload()});b.disabled=false;if(r.error){$('#status').textContent='تعذر الحفظ: '+r.error.message;return}$('#status').innerHTML=`تم حفظ <b>${safe(r.data.reference)}</b>${r.data.delivery_otp?` · OTP <b>${safe(r.data.delivery_otp)}</b>`:''}`;lines=[];renderOrder();toast('تم إرسال الطلب')}
async function boot(){token=localStorage.getItem(TOKEN)||'';if(!token){location='/menu/staff/';return}const ses=await sb.rpc('cfy_menu_staff_session',{p_token:token});if(ses.error||!ses.data||!['cashier','coordinator'].includes(ses.data.role)){location='/menu/staff/';return}location='/restaurant/?page='+(ses.data.role==='coordinator'?'prep':'takeaway')+'&as=staff'}
boot();
