const sb=window.supabase.createClient('https://ytixcczbjmjnuotzavbb.supabase.co','sb_publishable_0j9jf0boDrMGGO8S6mw-4Q_5bOeHIuU');const TOKEN='cardfy_menu_staff_token_v1',$=s=>document.querySelector(s);let token='',staff=null,snap=null,filter='active';
const safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const money=v=>Number(v||0).toLocaleString('ar-EG',{maximumFractionDigits:2})+' ج.م';const roleLabel=r=>r==='cashier'?'كاشير':r==='coordinator'?'محضّر الطلب':r==='delivery'?'توصيل':r;const statusLabel=s=>({new:'جديد',preparing:'جاري التجهيز',ready:'جاهز',on_the_way:'في الطريق',delivered:'تم التوصيل',completed:'مكتمل',cancelled:'ملغي'})[s]||s;const typeLabel=t=>t==='delivery'?'توصيل':t==='takeaway'?'استلام':t==='dinein'?'داخل المطعم':t;
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('on');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('on'),2200)}
async function login(){const c=$('#clientCode').value.trim().toUpperCase(),sc=$('#staffCode').value.trim(),pin=$('#pin').value;$('#loginStatus').textContent='جاري الدخول...';const r=await sb.rpc('cfy_menu_staff_login',{p_code:c,p_staff_code:sc,p_pin:pin});if(r.error||!r.data?.ok){const d=r.data||{},msg=d.error==='blocked'?'تم إيقاف المحاولة مؤقتًا. حاول لاحقًا.':'الكود أو PIN غير صحيح.';$('#loginStatus').textContent=msg;return}token=r.data.token;localStorage.setItem(TOKEN,token);staff=r.data.staff;await openApp()}
async function restore(){token=localStorage.getItem(TOKEN)||'';if(!token)return false;const r=await sb.rpc('cfy_menu_staff_session',{p_token:token});if(r.error||!r.data){localStorage.removeItem(TOKEN);token='';return false}staff=r.data;return true}
async function loadSnapshot(){const r=await sb.rpc('cfy_menu_staff_operational_snapshot',{p_token:token,p_limit:200});if(r.error){toast('تعذر تحديث البيانات');return false}snap=r.data||{};staff=snap.staff||staff;return true}
async function openApp(){if(!await loadSnapshot())return;$('#login').hidden=true;$('#app').hidden=false;$('#staffName').textContent=staff.name;$('#staffMeta').textContent=(staff.brand_name?staff.brand_name+' · ':'')+roleLabel(staff.role)+' · '+(staff.client_code||'');$('#roleBanner').textContent=staff.role==='coordinator'?'أنت في مركز تشغيل الطلبات: استلام → تجهيز → جاهز → إسناد توصيل.':staff.role==='cashier'?'أنت كاشير: POS + تشغيل الحسابات والترابيزات.':'صفحة التوصيل: الطلبات المسندة لك فقط.';$('#posLink').hidden=!['cashier','coordinator'].includes(staff.role);render()}
function orderItems(o){return (o.items||[]).map(i=>{const s=i.snapshot||{},p=s.product||{},v=s.variant,opts=s.options||[];return `<div class="item"><b>${i.quantity} × ${safe(p.name_ar||p.name_en||'منتج')}</b>${v||opts.length||s.notes?`<small>${v?safe(v.name):''}${opts.length?' · '+opts.map(x=>safe(x.name)).join('، '):''}${s.notes?' · '+safe(s.notes):''}</small>`:''}</div>`}).join('')}
function actionButtons(o){let h='';if(staff.role==='coordinator'){if(o.status==='new')h+=`<button class="action" data-act="accept" data-id="${o.id}">تم استلام الطلب</button>`;if(o.status==='preparing')h+=`<button class="action ok" data-act="ready" data-id="${o.id}">تم التجهيز</button>`;if(o.status==='ready'&&o.order_type==='delivery'){const ds=snap.drivers||[];h+=`<select class="driver-select" id="drv-${o.id}"><option value="">اقتراح تلقائي</option>${ds.filter(d=>d.shift_state==='available').map(d=>`<option value="${d.id}">${safe(d.name)} · ${d.active_deliveries||0}</option>`).join('')}</select><button class="action" data-act="assign_driver" data-id="${o.id}">إسناد</button>`}if(o.status==='delivered')h+=`<button class="action ok" data-act="complete" data-id="${o.id}">مكتمل</button>`;if(!['completed','cancelled','delivered'].includes(o.status))h+=`<button class="action danger" data-act="cancel" data-id="${o.id}">إلغاء</button>`}else if(staff.role==='cashier'){if(o.status==='new')h+=`<button class="action" data-act="accept" data-id="${o.id}">استلام</button>`;if(o.status==='ready'&&o.order_type!=='delivery')h+=`<button class="action ok" data-act="complete" data-id="${o.id}">إغلاق الطلب</button>`;if(!['completed','cancelled','delivered'].includes(o.status))h+=`<button class="action danger" data-act="cancel" data-id="${o.id}">إلغاء</button>`}else if(staff.role==='delivery'){if(o.status==='ready')h+=`<button class="action" data-act="picked_up" data-id="${o.id}">استلمت الطلب من المطعم</button>`;if(o.status==='on_the_way')h+=`<button class="action ok" data-act="delivered" data-id="${o.id}">تم التوصيل</button>`}h+=`<button class="action secondary" data-issue data-id="${o.id}">مشكلة</button>`;return h}
function visibleOrders(){let a=snap.orders||[];if(filter==='active')return a.filter(o=>!['completed','cancelled'].includes(o.status));if(filter==='all')return a;return a.filter(o=>o.status===filter)}
function render(){renderShift();renderStats();renderTabs();const list=visibleOrders();$('#orders').innerHTML=list.length?list.map(o=>`<div class="order ${o.issue_open?'issue':''} ${staff.role==='delivery'?'delivery-card':''}"><div class="order-head"><div><div class="ref">${safe(o.reference)}</div><div class="meta">${typeLabel(o.order_type)} · ${o.order_source==='online'?'Online':o.order_source==='phone'?'هاتف':'POS'}${o.table_number?' · ترابيزة '+safe(o.table_number):''}</div></div><span class="badge ${o.status}">${statusLabel(o.status)}</span></div><div class="order-items">${orderItems(o)}</div>${staff.role==='delivery'?`<div class="address">${safe(o.address||'')}</div><div class="meta">${safe(o.phone||'')}</div><div class="amount">المطلوب تحصيله: ${money(o.total)}</div>`:`<div class="meta">${safe(o.customer_name||'')} ${safe(o.phone||'')}</div><div style="font-weight:1000;margin-top:7px">${money(o.total)}</div>`}${o.issue_open?`<div class="meta" style="color:#a72d42">مشكلة: ${safe(o.issue_text)}</div>`:''}<div class="order-actions">${actionButtons(o)}</div></div>`).join(''):'<div class="empty">لا توجد طلبات هنا.</div>';bindActions();renderTables()}
function renderShift(){const box=$('#shiftBox');if(staff.role!=='delivery'){box.hidden=true;return}box.hidden=false;box.innerHTML=`<b>حالة الشيفت: ${staff.shift_state==='available'?'متاح':staff.shift_state==='paused'?'متوقف مؤقتًا':'خارج الشيفت'}</b><div class="meta">يمكن إسناد أكثر من طلب لك أثناء الشيفت.</div><div class="shift-actions"><button class="action ok" data-shift="available">متاح</button><button class="action warn" data-shift="paused">Pause</button><button class="action secondary" data-shift="offline">إنهاء الشيفت</button></div>`;box.querySelectorAll('[data-shift]').forEach(b=>b.onclick=()=>setShift(b.dataset.shift))}
function renderStats(){const a=snap.orders||[];$('#stats').innerHTML=staff.role==='delivery'?`<div class="stat"><b>${a.filter(o=>o.status==='ready').length}</b><span>جاهز للاستلام</span></div><div class="stat"><b>${a.filter(o=>o.status==='on_the_way').length}</b><span>في الطريق</span></div><div class="stat"><b>${a.length}</b><span>إجمالي المسند</span></div>`:`<div class="stat"><b>${a.filter(o=>o.status==='new').length}</b><span>جديد</span></div><div class="stat"><b>${a.filter(o=>o.status==='preparing').length}</b><span>تجهيز</span></div><div class="stat"><b>${a.filter(o=>o.status==='ready').length}</b><span>جاهز</span></div>`}
function renderTabs(){const vals=staff.role==='delivery'?[['active','نشطة'],['ready','جاهزة'],['on_the_way','في الطريق'],['delivered','تمت']]:[['active','نشطة'],['new','جديدة'],['preparing','تجهيز'],['ready','جاهزة'],['completed','مكتملة'],['all','الكل']];$('#tabs').innerHTML=vals.map(([v,l])=>`<button class="${filter===v?'active':''}" data-filter="${v}">${l}</button>`).join('');$('#tabs').querySelectorAll('button').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;render()})}
function renderTables(){const wrap=$('#tablesWrap');if(!['cashier','coordinator'].includes(staff.role)){wrap.hidden=true;return}wrap.hidden=false;const ts=snap.tables||[];$('#tables').innerHTML=ts.length?ts.map(t=>{const s=t.session;return `<div class="table"><b>${safe(t.label)}</b><small>${!s?'متاحة':s.status==='open'?'مشغولة':s.status==='bill_requested'?'طلب الحساب':'في انتظار الدفع'}${s?' · '+money(s.running_total):''}</small>${s?`<div class="order-actions">${s.status!=='payment_pending'?`<button class="action warn" data-tact="payment_pending" data-sid="${s.id}">بدء الدفع</button>`:''}<button class="action ok" data-tact="close_paid" data-sid="${s.id}">تم الدفع وإغلاق</button></div>`:''}</div>`}).join(''):'<div class="empty">لا توجد ترابيزات.</div>';$('#tables').querySelectorAll('[data-tact]').forEach(b=>b.onclick=()=>tableAction(b.dataset.sid,b.dataset.tact))}
function bindActions(){$('#orders').querySelectorAll('[data-act]').forEach(b=>b.onclick=()=>orderAct(b.dataset.id,b.dataset.act));$('#orders').querySelectorAll('[data-issue]').forEach(b=>b.onclick=()=>issue(b.dataset.id))}
async function orderAct(id,act){let data={};if(act==='assign_driver')data.driver_id=document.getElementById('drv-'+id)?.value||'';if(act==='delivered'){const otp=prompt('أدخل رمز العميل');if(otp===null)return;data.otp=otp}if(act==='cancel'){const reason=prompt('سبب الإلغاء');if(reason===null)return;data.reason=reason}const r=await sb.rpc('cfy_menu_staff_order_action',{p_token:token,p_order_id:id,p_action:act,p_data:data});if(r.error){toast('تعذر التنفيذ: '+r.error.message);return}toast('تم تحديث الطلب');await reload()}
async function issue(id){const text=prompt('اكتب وصف المشكلة');if(!text)return;const r=await sb.rpc('cfy_menu_staff_order_action',{p_token:token,p_order_id:id,p_action:'issue',p_data:{text}});if(r.error)toast('تعذر تسجيل المشكلة');else{toast('تم تسجيل المشكلة');await reload()}}
async function tableAction(id,act){if(act==='close_paid'&&!confirm('تأكيد الدفع وإغلاق الترابيزة؟'))return;const r=await sb.rpc('cfy_menu_staff_table_action',{p_token:token,p_session_id:id,p_action:act});if(r.error)toast('تعذر تحديث الترابيزة');else{toast('تم التحديث');await reload()}}
async function setShift(s){const r=await sb.rpc('cfy_menu_staff_shift',{p_token:token,p_state:s});if(r.error)toast('تعذر تحديث الشيفت');else{staff.shift_state=s;toast('تم تحديث حالة الشيفت');await reload()}}
async function reload(){const r=await sb.rpc('cfy_menu_staff_operational_snapshot',{p_token:token,p_limit:200});if(r.error){toast('انتهت الجلسة أو تعذر التحديث');return}snap=r.data||{};staff=snap.staff||staff;render()}
async function logout(){if(token)await sb.rpc('cfy_menu_staff_logout',{p_token:token});localStorage.removeItem(TOKEN);location.reload()}
$('#loginBtn').onclick=login;$('#pin').addEventListener('keydown',e=>{if(e.key==='Enter')login()});$('#logout').onclick=logout;$('#refresh').onclick=reload;(async()=>{if(await restore())await openApp();})();setInterval(()=>{if(token)reload()},20000);