import {useMemo,useState} from "react";
import {toast,Toaster} from "sonner";
import {PosHeader} from "@/components/pos/PosHeader";
import {ProductArea} from "@/components/pos/ProductArea";
import {OrderPanel,type OrderType} from "@/components/pos/OrderPanel";
import {AddressDialog,emptyCustomer,type CustomerInfo} from "@/components/pos/AddressDialog";
import {PaymentDialog} from "@/integration/PaymentDialog";
import {ReceiptDialog} from "@/integration/ReceiptDialog";
import {deliveryZones,modifierGroups,type Product} from "@/lib/pos-data";
import {defaultSelections,lineTotal,signature,type OrderLine,type Selections} from "@/lib/pos-order";
import type {PosServices} from "@/integration/types";

let counter=0;const newId=()=>`line-${++counter}`;
export function App({services}:{services:PosServices}){
 const settings=services.snapshot.catalog.settings||{},deliveryEnabled=Boolean(settings.delivery_enabled),draftKey=`cardfy_pos_draft:${services.context.client_id}:${services.branchId}`;
 const saved=useMemo(()=>{try{return JSON.parse(sessionStorage.getItem(draftKey)||"null")}catch{return null}},[draftKey]);
 const initialType:OrderType=saved?.orderType==="delivery"&&deliveryEnabled?"delivery":"pickup";
 const [orderType,setOrderType]=useState<OrderType>(initialType);
 const [lines,setLines]=useState<OrderLine[]>(Array.isArray(saved?.lines)?saved.lines:[]),[selectedLineId,setSelectedLineId]=useState<string|null>(null),[notes,setNotes]=useState(typeof saved?.notes==="string"?saved.notes:""),[customer,setCustomer]=useState<CustomerInfo>(saved?.customer||emptyCustomer),[addressOpen,setAddressOpen]=useState(false),[paymentOpen,setPaymentOpen]=useState(false),[busy,setBusy]=useState(false),[headerQuery,setHeaderQuery]=useState(""),[receipt,setReceipt]=useState<any>(null);
 const selectedLine=lines.find(l=>l.id===selectedLineId)||null,subtotal=useMemo(()=>lines.reduce((sum,l)=>sum+lineTotal(l),0),[lines]),zone=deliveryZones.find(z=>z.id===customer.zoneId)||null,deliveryFee=orderType==="delivery"&&zone?zone.fee:0;
 const pendingCount=(services.snapshot.orders||[]).filter((o:any)=>o.order_type!=="dinein"&&!['completed','cancelled','delivered','on_the_way'].includes(o.status)&&!o.assigned_driver_id).length;
 const methods=(settings.payment_methods||['cash']).filter((m:string)=>orderType==="delivery"?['pay_on_delivery','cash'].includes(m):['cash','card_at_venue'].includes(m));
 const addProduct=(product:Product)=>{const selections=defaultSelections(product),sig=signature(product.id,selections),existing=lines.find(l=>signature(l.productId,l.selections)===sig);if(existing){setLines(p=>p.map(l=>l.id===existing.id?{...l,quantity:l.quantity+1}:l));setSelectedLineId(existing.id);return}const line={id:newId(),productId:product.id,quantity:1,selections};setLines(p=>[...p,line]);setSelectedLineId(line.id)};
 const changeQuantity=(id:string,delta:number)=>setLines(prev=>prev.flatMap(l=>{if(l.id!==id)return[l];const quantity=l.quantity+delta;if(quantity<=0){if(selectedLineId===id)setSelectedLineId(null);return[]}return[{...l,quantity}]}));
 const removeLine=(id:string)=>{setLines(p=>p.filter(l=>l.id!==id));if(selectedLineId===id)setSelectedLineId(null)};
 const clearAll=()=>{setLines([]);setSelectedLineId(null);setNotes("");sessionStorage.removeItem(draftKey)};
 const toggleModifier=(groupId:string,optionId:string)=>{if(!selectedLine)return;const group=modifierGroups[groupId];if(!group)return;const current=selectedLine.selections[groupId]||[];let next:string[];if(group.multi)next=current.includes(optionId)?current.filter(id=>id!==optionId):(current.length>=group.max?current:[...current,optionId]);else next=current.includes(optionId)&&!group.required?[]:[optionId];const selections:Selections={...selectedLine.selections,[groupId]:next},sig=signature(selectedLine.productId,selections);setLines(prev=>{const twin=prev.find(l=>l.id!==selectedLine.id&&signature(l.productId,l.selections)===sig);if(twin){setSelectedLineId(twin.id);return prev.filter(l=>l.id!==selectedLine.id).map(l=>l.id===twin.id?{...l,quantity:l.quantity+selectedLine.quantity}:l)}return prev.map(l=>l.id===selectedLine.id?{...l,selections}:l)})};
 const validate=()=>{for(const line of lines){for(const gid of Object.keys(line.selections)){const g=modifierGroups[gid],count=line.selections[gid].length;if(g&&(count<g.min||count>g.max)){setSelectedLineId(line.id);throw new Error(`راجع اختيارات ${g.name}.`)}}}if(orderType==="delivery"&&(!customer.name.trim()||!customer.phone.trim()||!customer.zoneId||!customer.address.trim())){setAddressOpen(true);throw new Error("أكمل بيانات التوصيل قبل إتمام الطلب.")}if(!methods.length)throw new Error("لا توجد طريقة دفع مفعّلة لهذا النوع من الطلبات.")};
 const payload=(payment_method:string)=>({order_type:orderType==="pickup"?"takeaway":"delivery",source:"pos",branch_id:services.branchId,payment_method,customer_name:orderType==="delivery"?customer.name:"",phone:orderType==="delivery"?customer.phone:"",delivery_zone_id:orderType==="delivery"?customer.zoneId:"",address:orderType==="delivery"?customer.address:"",notes:[notes,orderType==="delivery"&&customer.notes?`ملاحظات التوصيل: ${customer.notes}`:""].filter(Boolean).join("\n"),table_id:"",coupon_code:"",items:lines.map(line=>{const variant=Object.entries(line.selections).find(([gid])=>modifierGroups[gid]?.kind==="variant")?.[1]?.[0]||"";const option_ids=Object.entries(line.selections).filter(([gid])=>modifierGroups[gid]?.kind==="option").flatMap(([,ids])=>ids);return{product_id:line.productId,quantity:line.quantity,variant_id:variant,option_ids,notes:""}})});
 const beginComplete=()=>{try{validate();setPaymentOpen(true)}catch(error:any){toast.error(error.message)}};
 const submit=async(method:string)=>{setBusy(true);try{const order=payload(method);await services.rpc('cfy_os_pos_quote',{p_token:services.context.token,p_page:'takeaway',p_order:order});const result=await services.rpc('cfy_os_pos_order',{p_token:services.context.token,p_page:'takeaway',p_order:order,p_intent:'save',p_request_key:crypto.randomUUID()});setPaymentOpen(false);clearAll();setCustomer(emptyCustomer);setReceipt(result);services.status(`تم إنشاء ${result.reference} وإرساله إلى محضّر الطلب.`);toast.success(`تم إنشاء ${result.reference}`)}catch(error:any){services.status(error.message||"تعذر إنشاء الطلب.",true);toast.error(error.message||"تعذر إنشاء الطلب.")}finally{setBusy(false)}};
 return <div className="flex min-h-screen flex-col bg-background lg:h-screen lg:overflow-hidden"><PosHeader actorName={services.context.name||"CARDfy"} actorRole={services.context.role==='owner'?"مالك المطعم":"موظف المطعم"} pendingCount={pendingCount} onMenu={services.onMenu} onBell={services.onBell} onSearch={setHeaderQuery}/><main className="grid min-h-0 flex-1 gap-3 p-3 sm:gap-4 sm:p-4 lg:grid-cols-[minmax(0,1fr)_25rem] xl:grid-cols-[minmax(0,1fr)_28rem]"><ProductArea onAdd={addProduct} externalQuery={headerQuery}/><OrderPanel orderType={orderType} onOrderTypeChange={type=>type!=="delivery"||deliveryEnabled?setOrderType(type):undefined} lines={lines} selectedLine={selectedLine} onSelectLine={id=>setSelectedLineId(id===selectedLineId?null:id)} onQuantity={changeQuantity} onRemove={removeLine} onClearAll={clearAll} onToggleModifier={toggleModifier} onCloseModifiers={()=>setSelectedLineId(null)} notes={notes} onNotesChange={setNotes} subtotal={subtotal} deliveryFee={deliveryFee} zoneName={zone?.name||null} hasAddress={Boolean(customer.address)} onOpenAddress={()=>setAddressOpen(true)} onSaveOrder={()=>{sessionStorage.setItem(draftKey,JSON.stringify({lines,notes,customer,orderType}));toast.success("تم حفظ الطلب مؤقتاً")}} onComplete={beginComplete} deliveryEnabled={deliveryEnabled}/></main><footer className="hidden items-center justify-between gap-2 border-t border-border/70 px-5 py-2 text-xs text-muted-foreground lg:flex"><span className="font-bold"><bdi dir="ltr">CARD<span className="text-brand">fy</span> Restaurant POS</bdi></span><span>كل شيء في مكان واحد .. إدارة أسهل .. مطعم أكثر نجاحاً</span></footer><AddressDialog open={addressOpen} onOpenChange={setAddressOpen} value={customer} onSave={info=>{setCustomer(info);setAddressOpen(false);toast.success("تم حفظ بيانات التوصيل")}}/><PaymentDialog open={paymentOpen} onOpenChange={setPaymentOpen} methods={methods} busy={busy} onConfirm={submit}/>{receipt&&<ReceiptDialog result={receipt} handoffHtml={services.customerHandoff(receipt)} onClose={()=>setReceipt(null)}/>}<Toaster richColors position="top-center" dir="rtl"/></div>;
}
