(function(){
let tableContext=null,currentType='',currentQuote=null,currentCoupon='',idemKey='',customer={};
const labels={delivery:'توصيل',takeaway:'استلام من المطعم',dinein:'داخل المطعم'},field=id=>document.getElementById(id);
function errorAr(err){const m=String(err?.message||err||''),map={restaurant_closed:'المطعم مغلق في الوقت المختار.',delivery_zone_required:'اختر منطقة التوصيل.',minimum_order_not_met:'الطلب أقل من الحد الأدنى للمنطقة.',invalid_coupon:'كود الخصم غير صالح أو منتهي.',coupon_minimum_not_met:'الطلب أقل من الحد الأدنى المطلوب للكوبون.',delivery_details_required:'أكمل الاسم والموبايل والعنوان.',takeaway_details_required:'أكمل بيانات الاستلام.',invalid_egyptian_phone:'اكتب رقمًا مصريًا بصيغة 01xxxxxxxxx.',customer_profile_required:'احفظ بيانات العميل أولًا.',invalid_branch:'اختر فرعًا صالحًا.',branch_required:'اختر الفرع.',invalid_delivery_zone:'منطقة التوصيل لا تتبع الفرع المختار.',table_required:'رقم الترابيزة غير صالح.',table_not_accepting_orders:'الترابيزة لا تستقبل طلبات جديدة الآن.',product_unavailable:'يوجد منتج لم يعد متاحًا.',variant_required:'يوجد منتج يحتاج اختيار الحجم.',invalid_options:'راجع الإضافات المختارة.'};for(const k in map)if(m.includes(k))return map[k];return 'تعذر تنفيذ العملية. راجع البيانات وحاول مرة أخرى.'}
function inject(){if(field('checkoutModal'))return;const el=document.createElement('div');el.id='checkoutModal';el.className='checkout-modal';el.hidden=true;el.innerHTML=`<div class="checkout-sheet" role="dialog" aria-modal="true"><div class="checkout-head"><div><h2>إتمام الطلب</h2><p id="checkoutStep">بيانات العميل ثم مراجعة السلة والدفع</p></div><button id="closeCheckout" class="close-btn">×</button></div><div id="checkoutBody"></div></div>`;document.body.append(el);el.onclick=e=>{if(e.target===el)closeCheckout()};field('closeCheckout').onclick=closeCheckout;const btn=document.querySelector('.checkout-disabled');if(btn){btn.disabled=false;btn.className='submit-order';btn.textContent='إتمام الطلب';btn.onclick=e=>{e.preventDefault();openCheckout()}}}
async function loadTableContext(){if(!state.tableKey||!state.settings.table_qr_enabled)return null;const r=await sb.rpc('cfy_menu_table_context',{p_code:state.code,p_table_key:state.tableKey});tableContext=r.error?null:r.data;return tableContext}
function availableTypes(){const s=state.settings,r=[];if(s.delivery_enabled)r.push('delivery');if(s.takeaway_enabled)r.push('takeaway');if(s.dinein_enabled&&s.table_qr_enabled&&tableContext?.table)r.push('dinein');return r}
function buildItems(){return state.cart.map(x=>({product_id:x.product_id,quantity:Number(x.qty||1),variant_id:x.variant?.id||'',option_ids:(x.options||[]).map(o=>o.id),notes:x.notes||''}))}
function scheduledIso(){const v=field('coScheduled')?.value;if(!v)return '';const d=new Date(v);return Number.isNaN(d.getTime())?'':d.toISOString()}
function payload(){return{order_type:currentType,items:buildItems(),customer_name:customer.name||'',phone:customer.phone||'',address:currentType==='delivery'?(customer.address||''):'',branch_id:customer.branch_id||'',delivery_zone_id:currentType==='delivery'?(customer.zone_id||''):'',table_key:currentType==='dinein'?state.tableKey:'',notes:field('coNotes')?.value.trim()||customer.notes||'',coupon_code:currentCoupon,scheduled_for:scheduledIso(),payment_method:field('coPayment')?.value||'cash'}}
function typeButtons(){return `<div class="order-types">${availableTypes().map(t=>`<button class="order-type ${t===currentType?'active':''}" data-type="${t}">${labels[t]}</button>`).join('')}</div>`}
function renderCustomer(){field('checkoutStep').textContent='1 من 2 — بيانات العميل';const body=field('checkoutBody');if(currentType==='dinein'){customer={name:'ضيف الترابيزة',phone:'01000000000',branch_id:''};renderPayment();return}const api=window.CardfyCustomer,p=api?.profile||{};customer={...p};body.innerHTML=`${typeButtons()}<form id="checkoutCustomer">${api.fields(p)}<p class="server-note">اكتب الموبايل بصيغة مصرية محلية، بدون +20.</p><div id="checkoutError" class="checkout-error"></div><button class="submit-order">متابعة إلى السلة والدفع</button></form>`;body.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>{currentType=b.dataset.type;currentQuote=null;renderCustomer()});field('checkoutCustomer').onsubmit=async e=>{e.preventDefault();const btn=e.submitter,raw=Object.fromEntries(new FormData(e.target));if(currentType==='delivery'&&(!raw.zone_id||String(raw.address||'').trim().length<5)){field('checkoutError').textContent='اختر المنطقة واكتب العنوان بالتفصيل.';return}btn.disabled=true;try{customer=await api.save(raw);renderPayment()}catch(x){field('checkoutError').textContent=errorAr(x)}finally{btn.disabled=false}}}
function cartReview(){return state.cart.map(x=>`<div class="quote-row"><span>${Number(x.qty)} × ${safe(x.name)}${x.variant?' · '+safe(x.variant.name):''}</span><b>${money(x.unit_price*x.qty)}</b></div>`).join('')}
function paymentOptions(){const allowed=currentType==='delivery'?['cash','pay_on_delivery']:['cash','card_at_venue'];return (state.settings.payment_methods||['cash']).filter(v=>allowed.includes(v)).map(v=>`<option value="${safe(v)}">${({cash:'نقدي',card_at_venue:'بطاقة عند المطعم',pay_on_delivery:'الدفع عند الاستلام'})[v]||safe(v)}</option>`).join('')}
function renderPayment(){field('checkoutStep').textContent='2 من 2 — مراجعة السلة والدفع';const s=state.settings;field('checkoutBody').innerHTML=`<button id="backCustomer" class="order-type">رجوع للبيانات</button>${currentType==='dinein'&&tableContext?.table?`<div class="table-context">الترابيزة: ${safe(tableContext.table.label)}</div>`:''}<div class="quote-box">${cartReview()}</div><div class="checkout-grid"><div class="checkout-field"><label>طريقة الدفع</label><select id="coPayment">${paymentOptions()}</select></div>${(s.scheduled_ordering_enabled||s.pickup_scheduling_enabled)?'<div class="checkout-field"><label>موعد لاحق (اختياري)</label><input id="coScheduled" type="datetime-local"></div>':''}<div class="checkout-field full"><label>ملاحظات الطلب</label><textarea id="coNotes" maxlength="1000"></textarea></div></div><div class="coupon-row"><input id="coCoupon" placeholder="كود الخصم" maxlength="40" value="${safe(currentCoupon)}"><button id="applyCoupon">تطبيق</button></div><div id="quoteBox" class="quote-box"><div class="server-note">جارٍ حساب السعر النهائي...</div></div><div id="checkoutError" class="checkout-error"></div><button id="placeOrder" class="submit-order">تأكيد وإرسال الطلب</button>`;field('backCustomer').onclick=renderCustomer;field('applyCoupon').onclick=()=>{currentCoupon=field('coCoupon').value.trim().toUpperCase();runQuote()};field('coPayment').onchange=runQuote;field('placeOrder').onclick=submitOrder;runQuote()}
async function runQuote(){if(!currentType||!state.cart.length)return;const box=field('quoteBox');box.innerHTML='<div class="server-note">جاري حساب السعر النهائي...</div>';const r=await sb.rpc(currentType==='dinein'?'cfy_menu_quote_order_v3':'cfy_os_public_quote',{p_code:state.code,p_order:payload()});if(r.error){currentQuote=null;box.innerHTML=`<div class="server-note">${safe(errorAr(r.error))}</div>`;return}currentQuote=r.data;box.innerHTML=`<div class="quote-row"><span>إجمالي المنتجات</span><b>${money(currentQuote.products_subtotal)}</b></div>${Number(currentQuote.product_discount)>0?`<div class="quote-row"><span>خصم المنتجات</span><b>- ${money(currentQuote.product_discount)}</b></div>`:''}${Number(currentQuote.coupon_discount)>0?`<div class="quote-row"><span>خصم الكوبون</span><b>- ${money(currentQuote.coupon_discount)}</b></div>`:''}<div class="quote-row"><span>التوصيل</span><b>${money(currentQuote.delivery_fee)}</b></div><div class="quote-row total"><span>الإجمالي النهائي</span><b>${money(currentQuote.total)}</b></div>`}
async function customerAPI(){for(let i=0;i<50&&!window.CardfyCustomer;i++)await new Promise(r=>setTimeout(r,50));if(!window.CardfyCustomer)throw new Error('customer_profile_unavailable');return window.CardfyCustomer}
async function openCheckout(){if(!state.cart.length){toast('السلة فارغة');return}await loadTableContext();const api=await customerAPI();await api.refresh();currentType=availableTypes()[0]||'';currentCoupon='';currentQuote=null;idemKey=crypto.randomUUID();field('checkoutModal').hidden=false;document.body.style.overflow='hidden';renderCustomer()}
function closeCheckout(){const m=field('checkoutModal');if(m&&!m.hidden){m.hidden=true;document.body.style.overflow=''}}
async function submitOrder(){const err=field('checkoutError'),btn=field('placeOrder');err.textContent='';await runQuote();if(!currentQuote){err.textContent='تعذر حساب السعر النهائي.';return}btn.disabled=true;btn.textContent='جاري حفظ الطلب...';const p={...payload(),idempotency_key:idemKey};const r=currentType==='dinein'?await sb.rpc('cfy_menu_create_order_v3',{p_code:state.code,p_order:p}):await sb.rpc('cfy_os_public_order',{p_code:state.code,p_device_token:window.CardfyCustomer.device,p_order:p});btn.disabled=false;btn.textContent='تأكيد وإرسال الطلب';if(r.error){err.textContent=errorAr(r.error);return}if(r.data?.duplicate){err.textContent='الطلب تم تسجيله بالفعل.';return}state.cart=[];localStorage.removeItem(cartKey());persistCart();renderAll();await window.CardfyCustomer?.refresh();showConfirmation(r.data)}
function showConfirmation(o){const track=`/menu/track/?ref=${encodeURIComponent(o.reference)}&token=${encodeURIComponent(o.tracking_token||'')}`;field('checkoutStep').textContent='تم إرسال الطلب';field('checkoutBody').innerHTML=`<div class="confirmation"><div class="ok-icon">✓</div><h2>تم إرسال طلبك بنجاح</h2><div class="ref">${safe(o.reference)}</div><p>${labels[o.order_type]||''}${o.table?.label?` · ترابيزة ${safe(o.table.label)}`:''}</p><div class="quote-box"><div class="quote-row total"><span>الإجمالي</span><b>${money(o.total)}</b></div></div>${o.delivery_otp?`<div class="otp-box">رمز تأكيد التسليم<b>${safe(o.delivery_otp)}</b><small>لا تعطِ الرمز للمندوب إلا بعد استلام الطلب.</small></div>`:''}<div class="confirmation-actions"><a class="track-btn" href="${track}">متابعة الطلب</a><button class="bill-btn" id="returnHome">العودة للمنيو</button>${o.order_type==='dinein'&&state.tableKey?'<button id="requestBillNow" class="bill-btn">طلب الحساب</button>':''}</div><div class="server-note">يمكنك الرجوع إلى الطلب الحالي والطلبات السابقة من «طلباتي».</div></div>`;field('returnHome').onclick=closeCheckout;if(field('requestBillNow'))field('requestBillNow').onclick=async()=>{const r=await sb.rpc('cfy_menu_request_bill',{p_code:state.code,p_table_key:state.tableKey});toast(r.error?'تعذر إرسال الطلب':'تم إرسال طلب الحساب')};}
function start(){inject();if(state.tableKey)loadTableContext()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(start,100));else setTimeout(start,100);
})();
