(function(){
let tableContext=null,currentType='',currentQuote=null,currentCoupon='',idemKey='';
const labels={delivery:'توصيل',takeaway:'استلام من المطعم',dinein:'داخل المطعم'};
function errorAr(err){const m=String(err?.message||err||'');const map={restaurant_closed:'المطعم مغلق في الوقت المختار.',delivery_zone_required:'اختر منطقة التوصيل.',minimum_order_not_met:'الطلب أقل من الحد الأدنى للمنطقة.',invalid_coupon:'كود الخصم غير صالح أو منتهي.',coupon_minimum_not_met:'الطلب أقل من الحد الأدنى المطلوب للكوبون.',delivery_details_required:'أكمل الاسم والهاتف والعنوان.',takeaway_details_required:'أكمل بيانات الاستلام.',table_required:'رقم الترابيزة غير صالح.',table_qr_disabled:'الطلب من QR الترابيزة غير مفعّل.',table_not_accepting_orders:'الترابيزة طلبت الحساب ولا تستقبل إضافات جديدة حاليًا.',invalid_scheduled_time:'وقت الطلب المجدول غير صالح.',scheduling_disabled:'الطلبات المجدولة غير مفعلة.',product_unavailable:'يوجد منتج لم يعد متاحًا. راجع السلة.',variant_required:'يوجد منتج يحتاج اختيار الحجم.',invalid_options:'راجع الإضافات المختارة.',duplicate_options:'يوجد اختيار مكرر في الإضافات.',menu_unavailable:'المنيو غير متاحة حاليًا.'};for(const k in map)if(m.includes(k))return map[k];return 'تعذر تنفيذ العملية. راجع البيانات وحاول مرة أخرى.'}
function inject(){
  const old=document.getElementById('checkoutModal');if(old)return;
  const el=document.createElement('div');el.id='checkoutModal';el.className='checkout-modal';el.hidden=true;el.innerHTML=`<div class="checkout-sheet" role="dialog" aria-modal="true"><div class="checkout-head"><div><h2>إتمام الطلب</h2><p>السعر النهائي يتحسب من السيرفر قبل حفظ الطلب.</p></div><button id="closeCheckout" class="close-btn">×</button></div><div id="checkoutBody"></div></div>`;document.body.appendChild(el);
  el.addEventListener('click',e=>{if(e.target===el)closeCheckout()});document.getElementById('closeCheckout').onclick=closeCheckout;
  const btn=document.querySelector('.checkout-disabled');if(btn){btn.disabled=false;btn.className='submit-order';btn.textContent='إتمام الطلب';btn.onclick=e=>{e.preventDefault();openCheckout()}}
}
async function loadTableContext(){if(!state.tableKey||!state.settings.table_qr_enabled)return null;const {data,error}=await sb.rpc('cfy_menu_table_context',{p_code:state.code,p_table_key:state.tableKey});if(error||!data)return null;tableContext=data;return data}
function availableTypes(){const s=state.settings,r=[];if(s.delivery_enabled)r.push('delivery');if(s.takeaway_enabled)r.push('takeaway');if(s.dinein_enabled&&s.table_qr_enabled&&tableContext?.table)r.push('dinein');return r}
function buildItems(){return state.cart.map(x=>({product_id:x.product_id,quantity:Number(x.qty||1),variant_id:x.variant?.id||'',option_ids:(x.options||[]).map(o=>o.id),notes:x.notes||''}))}
function field(id){return document.getElementById(id)}
function scheduledIso(){const v=field('coScheduled')?.value;if(!v)return '';const d=new Date(v);return Number.isNaN(d.getTime())?'':d.toISOString()}
function payload(){return{order_type:currentType,items:buildItems(),customer_name:field('coName')?.value.trim()||'',phone:field('coPhone')?.value.trim()||'',address:field('coAddress')?.value.trim()||'',delivery_zone_id:field('coZone')?.value||'',table_key:currentType==='dinein'?state.tableKey:'',notes:field('coNotes')?.value.trim()||'',coupon_code:currentCoupon,scheduled_for:scheduledIso()}}
function renderForm(){
  const types=availableTypes();if(!types.includes(currentType))currentType=types[0]||'';
  const s=state.settings,zones=state.catalog.delivery_zones||[];const isDelivery=currentType==='delivery',isTake=currentType==='takeaway',isDine=currentType==='dinein';
  const body=field('checkoutBody');if(!currentType){body.innerHTML='<div class="empty">لا يوجد نوع طلب متاح حاليًا.</div>';return}
  body.innerHTML=`<div class="order-types">${types.map(t=>`<button class="order-type ${t===currentType?'active':''}" data-type="${t}">${labels[t]}</button>`).join('')}</div>${isDine&&tableContext?.table?`<div class="table-context">الترابيزة: ${safe(tableContext.table.label)}${tableContext.session?` · حساب مفتوح حاليًا: ${money(tableContext.session.running_total||0)}`:''}</div>`:''}<div class="checkout-grid">${!isDine?`<div class="checkout-field"><label>الاسم</label><input id="coName" maxlength="160" autocomplete="name"></div><div class="checkout-field"><label>الهاتف</label><input id="coPhone" maxlength="40" inputmode="tel" autocomplete="tel"></div>`:''}${isDelivery?`<div class="checkout-field full"><label>العنوان</label><textarea id="coAddress" maxlength="1000" autocomplete="street-address"></textarea></div><div class="checkout-field"><label>منطقة التوصيل</label><select id="coZone"><option value="">اختر المنطقة</option>${zones.map(z=>`<option value="${z.id}">${safe(z.name)} — ${money(z.fee)}${Number(z.minimum_order)>0?` · حد أدنى ${money(z.minimum_order)}`:''}</option>`).join('')}</select></div>`:''}${(s.scheduled_ordering_enabled||s.pickup_scheduling_enabled)?`<div class="checkout-field"><label>موعد لاحق (اختياري)</label><input id="coScheduled" type="datetime-local"></div>`:''}<div class="checkout-field full"><label>ملاحظات الطلب</label><textarea id="coNotes" maxlength="1000" placeholder="أي ملاحظات عامة على الطلب"></textarea></div></div><div class="coupon-row"><input id="coCoupon" placeholder="كود الخصم" maxlength="40" value="${safe(currentCoupon)}"><button id="applyCoupon">تطبيق</button></div><div id="quoteBox" class="quote-box"><div class="server-note">اختر البيانات المطلوبة ليتم حساب الإجمالي النهائي من السيرفر.</div></div><div id="checkoutError" class="checkout-error"></div><button id="placeOrder" class="submit-order">تأكيد وحفظ الطلب</button>`;
  body.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>{currentType=b.dataset.type;currentQuote=null;renderForm();scheduleQuote()});
  ['coName','coPhone','coAddress','coZone','coScheduled','coNotes'].forEach(id=>{const x=field(id);if(x)x.addEventListener('change',scheduleQuote)});
  field('applyCoupon').onclick=()=>{currentCoupon=field('coCoupon').value.trim().toUpperCase();scheduleQuote(true)};
  field('placeOrder').onclick=submitOrder;scheduleQuote();
}
let quoteTimer;
function scheduleQuote(immediate=false){clearTimeout(quoteTimer);quoteTimer=setTimeout(runQuote,immediate?0:250)}
async function runQuote(){if(!currentType||!state.cart.length)return;const p=payload();if(currentType==='delivery'&&!p.delivery_zone_id){renderQuote(null);return}const box=field('quoteBox');if(box)box.innerHTML='<div class="server-note">جاري حساب السعر النهائي...</div>';const {data,error}=await sb.rpc('cfy_menu_quote_order',{p_code:state.code,p_order:p});if(error){currentQuote=null;renderQuote(null,errorAr(error));return}currentQuote=data;renderQuote(data)}
function renderQuote(q,err=''){const box=field('quoteBox');if(!box)return;if(!q){box.innerHTML=`<div class="server-note">${safe(err||'أكمل البيانات المطلوبة لحساب الإجمالي.')}</div>`;return}box.innerHTML=`<div class="quote-row"><span>إجمالي المنتجات</span><b>${money(q.products_subtotal)}</b></div>${Number(q.product_discount)>0?`<div class="quote-row"><span>خصم المنتجات</span><b>- ${money(q.product_discount)}</b></div>`:''}${Number(q.coupon_discount)>0?`<div class="quote-row"><span>خصم الكوبون</span><b>- ${money(q.coupon_discount)}</b></div>`:''}${Number(q.delivery_fee)>0?`<div class="quote-row"><span>التوصيل</span><b>${money(q.delivery_fee)}</b></div>`:''}<div class="quote-row total"><span>الإجمالي النهائي</span><b>${money(q.total)}</b></div>${q.delivery_zone?.eta_minutes?`<div class="server-note">الوقت المتوقع للتوصيل: حوالي ${q.delivery_zone.eta_minutes} دقيقة.</div>`:''}`}
async function openCheckout(){if(!state.cart.length){toast('السلة فارغة');return}await loadTableContext();currentType=availableTypes()[0]||'';currentCoupon='';currentQuote=null;idemKey=crypto.randomUUID?crypto.randomUUID():String(Date.now())+'-'+Math.random().toString(36).slice(2);field('checkoutModal').hidden=false;document.body.style.overflow='hidden';renderForm()}
function closeCheckout(){const m=field('checkoutModal');if(m&&!m.hidden){m.hidden=true;document.body.style.overflow=''}}
async function submitOrder(){const err=field('checkoutError');err.textContent='';const btn=field('placeOrder');if(!currentType)return;if(!currentQuote){await runQuote();if(!currentQuote){err.textContent='تعذر حساب السعر النهائي. راجع البيانات.';return}}const p={...payload(),idempotency_key:idemKey};btn.disabled=true;btn.textContent='جاري حفظ الطلب...';const {data,error}=await sb.rpc('cfy_menu_create_order',{p_code:state.code,p_order:p});btn.disabled=false;btn.textContent='تأكيد وحفظ الطلب';if(error){err.textContent=errorAr(error);return}if(data?.duplicate){err.textContent='الطلب تم تسجيله بالفعل. لا تعيد الإرسال.';return}state.cart=[];localStorage.removeItem(cartKey());persistCart();renderAll();showConfirmation(data)}
function showConfirmation(o){const body=field('checkoutBody'),track=`/menu/track/?ref=${encodeURIComponent(o.reference)}&token=${encodeURIComponent(o.tracking_token||'')}`;body.innerHTML=`<div class="confirmation"><div class="ok-icon">✓</div><h2>تم إرسال طلبك بنجاح</h2><div class="ref">${safe(o.reference)}</div><p>${labels[o.order_type]||''}${o.table?.label?` · ترابيزة ${safe(o.table.label)}`:''}</p><div class="quote-box"><div class="quote-row total"><span>الإجمالي</span><b>${money(o.total)}</b></div></div>${o.delivery_otp?`<div class="otp-box">رمز تأكيد التسليم<b>${safe(o.delivery_otp)}</b><small>احتفظ به ولا تعطه للمندوب إلا عند استلام الطلب.</small></div>`:''}<div class="confirmation-actions"><a class="track-btn" href="${track}">متابعة الطلب</a>${o.order_type==='dinein'&&state.tableKey?'<button id="requestBillNow" class="bill-btn">طلب الحساب</button>':''}</div><div class="server-note">تم حفظ الطلب في قاعدة البيانات. أي إشعار خارجي يعتبر خطوة إضافية فقط.</div></div>`;if(field('requestBillNow'))field('requestBillNow').onclick=async()=>{const {error}=await sb.rpc('cfy_menu_request_bill',{p_code:state.code,p_table_key:state.tableKey});if(error)toast(errorAr(error));else{toast('تم إرسال طلب الحساب');field('requestBillNow').disabled=true}}}
async function start(){inject();await loadTableContext();if(tableContext?.table){const b=document.createElement('div');b.className='table-context';b.style.margin='8px 14px';b.textContent='أنت على '+tableContext.table.label+(tableContext.session?' · الحساب المفتوح '+money(tableContext.session.running_total||0):'');const main=document.querySelector('main');main?.prepend(b)} }
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(start,80));else setTimeout(start,80);
})();