(function(){
const DEVICE='cardfy_customer_device_v1',PROFILE='cardfy_customer_profile_v1:';let device=localStorage.getItem(DEVICE),profile=null,orders=[],branches=[];
if(!device){const bytes=crypto.getRandomValues(new Uint8Array(32));device=[...bytes].map(v=>v.toString(16).padStart(2,'0')).join('');localStorage.setItem(DEVICE,device)}
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const localPhone=v=>{const d=String(v||'').replace(/\D/g,'');return d.startsWith('20')&&d.length===12?'0'+d.slice(2):d};
function dialog(title,body){document.getElementById('customerDialog')?.remove();const d=document.createElement('dialog');d.id='customerDialog';d.className='customer-dialog';d.innerHTML=`<header><h2>${esc(title)}</h2><button class="close-btn" aria-label="إغلاق">×</button></header><div class="customer-dialog-body">${body}</div>`;document.body.append(d);d.querySelector('.close-btn').onclick=()=>d.close();d.addEventListener('click',e=>{if(e.target===d)d.close()});d.showModal();return d}
function zoneOptions(value=''){return (state.catalog?.delivery_zones||[]).map(z=>`<option value="${esc(z.id)}" ${z.id===value?'selected':''}>${esc(z.name)} — ${money(z.fee)}</option>`).join('')}
function branchOptions(value=''){return branches.map(b=>`<option value="${esc(b.id)}" ${b.id===value?'selected':''}>${esc(b.name)}</option>`).join('')}
async function refresh(){try{const [p,b]=await Promise.all([sb.rpc('cfy_os_customer_profile',{p_code:state.code,p_device_token:device,p_data:null}),sb.rpc('cfy_os_public_branches',{p_code:state.code})]);branches=b.data||[];if(p.data){profile=p.data.profile||null;orders=p.data.orders||[];localStorage.setItem(PROFILE+state.code,JSON.stringify(profile))}else{try{profile=JSON.parse(localStorage.getItem(PROFILE+state.code)||'null')}catch{profile=null}}}catch{try{profile=JSON.parse(localStorage.getItem(PROFILE+state.code)||'null')}catch{profile=null}}return profile}
function fields(p=profile||{}){return `<div class="customer-fields"><label>الاسم<input name="name" required minlength="2" maxlength="160" value="${esc(p.name||'')}"></label><label>الموبايل<input name="phone" required inputmode="tel" pattern="01[0-9]{9}" maxlength="11" placeholder="01xxxxxxxxx" value="${esc(localPhone(p.phone))}"></label><label>واتساب / هاتف إضافي<input name="whatsapp" inputmode="tel" maxlength="40" value="${esc(localPhone(p.whatsapp))}"></label><label>الفرع<select name="branch_id" required><option value="">اختر الفرع</option>${branchOptions(p.branch_id)}</select></label><label>المنطقة<select name="zone_id"><option value="">اختر المنطقة</option>${zoneOptions(p.zone_id)}</select></label><label class="wide">العنوان بالتفصيل<textarea name="address" maxlength="1000">${esc(p.address||'')}</textarea></label></div>`}
async function save(data){const payload={...data,phone:localPhone(data.phone),whatsapp:localPhone(data.whatsapp)};const r=await sb.rpc('cfy_os_customer_profile',{p_code:state.code,p_device_token:device,p_data:payload});if(r.error)throw r.error;profile=r.data.profile;orders=r.data.orders||[];localStorage.setItem(PROFILE+state.code,JSON.stringify(profile));return profile}
async function account(){await refresh();const d=dialog('حسابي',`<form id="customerForm">${fields()}<p id="customerError" class="checkout-error"></p><button class="customer-action">حفظ البيانات</button></form>${!orders.length?'<div class="recovery"><h3>استعادة الحساب</h3><p>لخصوصية طلباتك، أدخل الموبايل ورقم طلب سابق.</p><div class="customer-fields"><label>الموبايل<input id="recoverPhone" inputmode="tel" placeholder="01xxxxxxxxx"></label><label>رقم الطلب<input id="recoverRef" placeholder="MN-..."></label></div><button id="recover" class="customer-action">استعادة</button><p id="recoverStatus"></p></div>':''}`);d.querySelector('#customerForm').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{await save(Object.fromEntries(new FormData(e.target)));b.textContent='تم الحفظ ✓';setTimeout(()=>d.close(),500)}catch(x){d.querySelector('#customerError').textContent=String(x.message).includes('invalid_egyptian_phone')?'اكتب رقمًا مصريًا بصيغة 01xxxxxxxxx.':'تعذر حفظ البيانات. راجع الحقول.'}finally{b.disabled=false}};const recover=d.querySelector('#recover');if(recover)recover.onclick=async()=>{recover.disabled=true;const r=await sb.rpc('cfy_os_customer_recover',{p_code:state.code,p_phone:d.querySelector('#recoverPhone').value,p_reference:d.querySelector('#recoverRef').value,p_device_token:device});recover.disabled=false;if(r.error){d.querySelector('#recoverStatus').textContent='تعذر الاستعادة. راجع الموبايل ورقم الطلب.';return}profile=r.data.profile;orders=r.data.orders||[];localStorage.setItem(PROFILE+state.code,JSON.stringify(profile));d.close();account()}}
async function myOrders(){await refresh();const content=orders.length?orders.map(o=>`<article class="customer-order"><b>${esc(o.reference)}</b><p>${esc(o.order_type)} · ${new Date(o.created_at).toLocaleString('ar-EG')} · ${money(o.total)}</p><p>الحالة: ${esc(o.status)}${o.delivery_otp?` · رمز التسليم: <b>${esc(o.delivery_otp)}</b>`:''}</p><a href="/menu/track/?ref=${encodeURIComponent(o.reference)}&token=${encodeURIComponent(o.tracking_token)}">متابعة الطلب</a></article>`).join(''):'<p>لا توجد طلبات محفوظة على هذا الجهاز. احفظ بياناتك من «حسابي» أولًا.</p>';dialog('طلباتي',content)}
async function boot(){if(typeof state==='undefined'||!state.code||!state.catalog){setTimeout(boot,80);return}await refresh();document.getElementById('myAccount').onclick=account;document.getElementById('myOrders').onclick=myOrders;window.CardfyCustomer={get profile(){return profile},get branches(){return branches},device,refresh,save,fields,localPhone}}
boot();
})();
