const SUPA_URL='https://ytixcczbjmjnuotzavbb.supabase.co';
const SUPA_KEY='sb_publishable_0j9jf0boDrMGGO8S6mw-4Q_5bOeHIuU';
const sb=window.supabase.createClient(SUPA_URL,SUPA_KEY);
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={code:'',catalog:null,settings:{},query:'',category:'all',cart:[],detail:null,detailQty:1,tableKey:''};
const safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>Number(v||0).toLocaleString('ar-EG',{maximumFractionDigits:2})+' '+currency();
const currency=()=>state.settings.currency==='EGP'?'ج.م':(state.settings.currency||'EGP');
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('on');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('on'),2200)}
function fail(msg){$('#loading').hidden=true;const f=$('#fatal');f.textContent=msg;f.hidden=false}
function normalizeSettings(s={}){return{...s,theme_mode:s.theme_mode||'light',layout_preset:s.layout_preset||'classic',accent_color:/^#[0-9a-f]{6}$/i.test(s.accent_color||'')?s.accent_color:'#ff6b1a',show_cover:s.show_cover!==false,show_description:s.show_description!==false,show_contact_buttons:s.show_contact_buttons!==false,restaurant_open:s.restaurant_open!==false,operating_mode:s.operating_mode||'restaurant',table_qr_enabled:s.table_qr_enabled===true}}
async function boot(){
  const p=new URLSearchParams(location.search);state.code=(p.get('code')||'').trim().toUpperCase();state.tableKey=(p.get('table')||'').trim();
  if(!state.code){fail('رابط المنيو غير مكتمل.');return}
  const {data,error}=await sb.rpc('cfy_menu_public_catalog',{p_code:state.code});
  if(error||!data){fail('هذه المنيو غير متاحة حاليًا.');return}
  state.catalog=data;state.settings=normalizeSettings(data.settings||{});loadCart();applyTheme();renderHeader();renderCategories();renderAll();bindBase();renderCartBar();
  $('#loading').hidden=true;$('#app').hidden=false;
}
function applyTheme(){document.body.classList.toggle('theme-dark',state.settings.theme_mode==='dark');document.body.classList.remove('layout-classic','layout-modern','layout-visual');document.body.classList.add('layout-'+state.settings.layout_preset);document.documentElement.style.setProperty('--accent',state.settings.accent_color);const meta=$('meta[name=theme-color]');if(meta)meta.content=state.settings.theme_mode==='dark'?'#101114':'#ffffff'}
function renderHeader(){
  const c=state.catalog.client||{},s=state.settings,name=s.display_name||c.brand_name_ar||c.brand_name_en||'Professional Menu';
  document.title=name+' — CARDfy';$('#restaurantName').textContent=name;
  const cover=$('#cover');cover.classList.toggle('hidden',!s.show_cover);cover.style.backgroundImage=s.show_cover&&s.cover_url?`url("${String(s.cover_url).replace(/"/g,'')}")`:'';
  $('#logo').innerHTML=s.logo_url?`<img src="${safe(s.logo_url)}" alt="${safe(name)}">`:safe(name.slice(0,2));
  const d=$('#description');d.hidden=!s.show_description;d.textContent=s.description||'';
  const b=$('#openBadge');b.textContent=s.restaurant_open?'مفتوح الآن':'مغلق حاليًا';b.classList.toggle('closed',!s.restaurant_open);
  const contacts=[];
  if(s.restaurant_phone)contacts.push(`<a class="contact-btn" href="tel:${encodeURIComponent(s.restaurant_phone)}">اتصال</a>`);
  if(s.restaurant_whatsapp){const wa=String(s.restaurant_whatsapp).replace(/\D/g,'');if(wa)contacts.push(`<a class="contact-btn" target="_blank" rel="noopener" href="https://wa.me/${wa}">واتساب</a>`)}
  if(s.map_link)contacts.push(`<a class="contact-btn" target="_blank" rel="noopener" href="${safe(s.map_link)}">الموقع</a>`);
  const row=$('#contactRow');row.hidden=!s.show_contact_buttons;row.innerHTML=contacts.join('');
}
function renderCategories(){const cats=(state.catalog.categories||[]);const host=$('#categories');host.innerHTML=`<button class="cat-btn ${state.category==='all'?'active':''}" data-cat="all">الكل</button>`+cats.map(c=>`<button class="cat-btn ${state.category===c.id?'active':''}" data-cat="${c.id}">${safe(c.name_ar||c.name_en||'قسم')}</button>`).join('');$$('.cat-btn',host).forEach(b=>b.onclick=()=>{state.category=b.dataset.cat;renderCategories();renderAll()})}
function filteredProducts(){let ps=state.catalog.products||[];if(state.category!=='all')ps=ps.filter(p=>p.category_id===state.category);const q=state.query.trim().toLowerCase();if(q)ps=ps.filter(p=>`${p.name_ar||''} ${p.name_en||''} ${p.description_ar||''} ${p.description_en||''}`.toLowerCase().includes(q));return ps}
function needsDetails(p){return !!p.variant_required||(p.option_groups||[]).some(g=>g.required||Number(g.min_select||0)>0)}
function productCard(p){const simple=!needsDetails(p),desc=p.description_ar||p.description_en||'',img=p.image_url?`style="background-image:url('${safe(p.image_url).replace(/'/g,'%27')}')"`:'';return `<article class="product-card ${p.available===false?'unavailable':''}" data-product="${p.id}"><div class="product-image" ${img}>${p.featured?'<span class="featured">★ مميز</span>':''}</div><div class="product-body"><div class="product-name">${safe(p.name_ar||p.name_en||'منتج')}</div>${desc?`<div class="product-desc">${safe(desc)}</div>`:''}<div class="product-foot"><div>${p.available===false?'<span class="availability">غير متاح</span>':`<span class="price">${money(p.base_price)}</span>`}</div>${p.available===false?'':simple?`<button class="quick-add" data-quick="${p.id}" aria-label="إضافة للسلة">+</button>`:`<button class="details-btn" data-details="${p.id}">اختيارات</button>`}</div></div></article>`}
function renderAll(){const ps=filteredProducts(),host=$('#productsGrid');host.innerHTML=ps.map(productCard).join('');$('#productsCount').textContent=ps.length+' صنف';$('#emptyState').hidden=ps.length>0;const featured=(state.catalog.products||[]).filter(p=>p.featured&&p.available!==false).slice(0,8);const fs=$('#featuredSection');fs.hidden=featured.length===0||state.query||state.category!=='all';if(!fs.hidden)$('#featuredGrid').innerHTML=featured.map(productCard).join('');bindProducts()}
function bindProducts(){$$('[data-product]').forEach(card=>card.onclick=e=>{if(e.target.closest('button'))return;openDetails(card.dataset.product)});$$('[data-details]').forEach(b=>b.onclick=e=>{e.stopPropagation();openDetails(b.dataset.details)});$$('[data-quick]').forEach(b=>b.onclick=e=>{e.stopPropagation();quickAdd(b.dataset.quick)})}
function bindBase(){
  $('#search').oninput=e=>{state.query=e.target.value;renderAll()};$('#closeProduct').onclick=closeProduct;$('#productModal').onclick=e=>{if(e.target===$('#productModal'))closeProduct()};$('#cartBar').onclick=openCart;$('#closeCart').onclick=closeCart;$('#cartDrawer').onclick=e=>{if(e.target===$('#cartDrawer'))closeCart()};document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeProduct();closeCart()}})
}
function findProduct(id){return (state.catalog.products||[]).find(p=>p.id===id)}
function quickAdd(id){const p=findProduct(id);if(!p||p.available===false)return;if(needsDetails(p)){openDetails(id);return}addCartItem(p,{variant:null,options:[],notes:'',qty:1});toast('تمت الإضافة للسلة')}
function openDetails(id){const p=findProduct(id);if(!p)return;state.detail=p;state.detailQty=1;renderDetails();$('#productModal').hidden=false;document.body.style.overflow='hidden'}
function closeProduct(){if(!$('#productModal').hidden){$('#productModal').hidden=true;document.body.style.overflow=''}}
function renderDetails(){const p=state.detail;if(!p)return;const groups=p.option_groups||[],variants=p.variants||[],img=p.image_url?`style="background-image:url('${safe(p.image_url).replace(/'/g,'%27')}')"`:'';$('#productModalBody').innerHTML=`<div class="detail-image" ${img}></div><div class="detail-head"><h2 id="productModalTitle">${safe(p.name_ar||p.name_en||'منتج')}</h2><p>${safe(p.description_ar||p.description_en||'')}</p><div id="detailPrice" class="detail-price">${money(p.base_price)}</div></div>${variants.length?`<div class="choice-section" data-variants><div class="choice-title"><b>الحجم / الاختيار</b>${p.variant_required?'<span class="required">مطلوب</span>':''}</div><div class="choice-list">${!p.variant_required?'<label class="choice-option selected"><span><input type="radio" name="variant" value="" checked> بدون تغيير</span><small>'+money(p.base_price)+'</small></label>':''}${variants.map(v=>`<label class="choice-option"><span><input type="radio" name="variant" value="${v.id}"> ${safe(v.name)}</span><small>${money(v.price)}</small></label>`).join('')}</div></div>`:''}${groups.map(g=>groupHtml(g)).join('')}<div class="choice-section"><div class="choice-title"><b>ملاحظات خاصة</b><span></span></div><textarea id="itemNotes" class="notes" maxlength="500" placeholder="مثال: بدون بصل، درجة تسوية معينة..."></textarea></div><div class="qty-row"><b>الكمية</b><div class="qty-control"><button id="qtyPlus">+</button><b id="qtyValue">1</b><button id="qtyMinus">−</button></div></div><div id="detailValidation" class="validation"></div><button id="addDetailed" class="add-cart-btn" ${p.available===false?'disabled':''}>${p.available===false?'غير متاح حاليًا':'إضافة للسلة · '+money(p.base_price)}</button>`;bindDetails();updateDetailPrice()}
function groupHtml(g){const required=g.required||Number(g.min_select||0)>0,type=Number(g.max_select||1)===1?'radio':'checkbox';return `<div class="choice-section" data-group="${g.id}" data-min="${Number(g.min_select||0)}" data-max="${Number(g.max_select||1)}" data-required="${required?'1':'0'}"><div class="choice-title"><b>${safe(g.name)}</b>${required?`<span class="required">مطلوب ${Math.max(1,Number(g.min_select||0))}</span>`:'<span></span>'}</div><div class="choice-list">${(g.options||[]).map(o=>`<label class="choice-option"><span><input type="${type}" name="group-${g.id}" value="${o.id}" data-price="${Number(o.price_delta||0)}"> ${safe(o.name)}</span><small>${Number(o.price_delta||0)?'+'+money(o.price_delta):'بدون زيادة'}</small></label>`).join('')}</div></div>`}
function bindDetails(){
  const plus=$('#qtyPlus'),minus=$('#qtyMinus');plus.onclick=()=>{state.detailQty=Math.min(99,state.detailQty+1);$('#qtyValue').textContent=state.detailQty;updateDetailPrice()};minus.onclick=()=>{state.detailQty=Math.max(1,state.detailQty-1);$('#qtyValue').textContent=state.detailQty;updateDetailPrice()};
  $$('input[name="variant"]',$('#productModalBody')).forEach(x=>x.onchange=()=>{refreshSelectedStyles();updateDetailPrice()});
  $$('[data-group] input',$('#productModalBody')).forEach(x=>x.onchange=e=>{const section=e.target.closest('[data-group]'),max=Number(section.dataset.max||1);if(e.target.type==='checkbox'){const checked=$$('input:checked',section);if(checked.length>max){e.target.checked=false;toast('الحد الأقصى '+max+' اختيار')}}refreshSelectedStyles();updateDetailPrice()});
  $('#addDetailed').onclick=()=>{const selection=readSelection();const error=validateSelection(selection);$('#detailValidation').textContent=error||'';if(error)return;addCartItem(state.detail,{...selection,qty:state.detailQty,notes:$('#itemNotes').value.trim()});toast('تمت الإضافة للسلة');closeProduct()};refreshSelectedStyles()
}
function refreshSelectedStyles(){$$('.choice-option',$('#productModalBody')).forEach(l=>l.classList.toggle('selected',!!l.querySelector('input')?.checked))}
function readSelection(){const p=state.detail;const variantId=$('input[name="variant"]:checked',$('#productModalBody'))?.value||'';const variant=(p.variants||[]).find(v=>v.id===variantId)||null;const selectedOptions=[];$$('[data-group]',$('#productModalBody')).forEach(g=>$$('input:checked',g).forEach(i=>{const group=(p.option_groups||[]).find(x=>x.id===g.dataset.group),option=(group?.options||[]).find(o=>o.id===i.value);if(option)selectedOptions.push({group_id:group.id,group_name:group.name,id:option.id,name:option.name,price_delta:Number(option.price_delta||0)})}));return{variant,options:selectedOptions}}
function validateSelection(sel){const p=state.detail;if(p.variant_required&&!sel.variant)return 'اختر الحجم / الـVariant أولًا.';for(const g of p.option_groups||[]){const count=sel.options.filter(o=>o.group_id===g.id).length,min=Math.max(Number(g.min_select||0),g.required?1:0),max=Number(g.max_select||1);if(count<min)return `اختر ${min} على الأقل من ${g.name}.`;if(count>max)return `الحد الأقصى ${max} من ${g.name}.`}return ''}
function currentDetailUnit(){const p=state.detail;if(!p)return 0;const s=readSelection(),base=s.variant?Number(s.variant.price||0):Number(p.base_price||0);return base+s.options.reduce((a,o)=>a+Number(o.price_delta||0),0)}
function updateDetailPrice(){const unit=currentDetailUnit(),total=unit*state.detailQty;$('#detailPrice').textContent=money(unit);const b=$('#addDetailed');if(b&&!b.disabled)b.textContent='إضافة للسلة · '+money(total)}
function cartKey(){return 'cardfy_menu_cart_v1:'+state.code}
function loadCart(){try{const x=JSON.parse(localStorage.getItem(cartKey())||'[]');state.cart=Array.isArray(x)?x:[]}catch(_){state.cart=[]}}
function persistCart(){localStorage.setItem(cartKey(),JSON.stringify(state.cart));renderCartBar();if(!$('#cartDrawer').hidden)renderCart()}
function lineKey(product,variant,options,notes){return [product.id,variant?.id||'',options.map(o=>o.id).sort().join(','),notes||''].join('|')}
function addCartItem(product,{variant=null,options=[],notes='',qty=1}){const unit=(variant?Number(variant.price||0):Number(product.base_price||0))+options.reduce((a,o)=>a+Number(o.price_delta||0),0),key=lineKey(product,variant,options,notes),existing=state.cart.find(x=>x.key===key);if(existing)existing.qty=Math.min(99,existing.qty+qty);else state.cart.push({key,product_id:product.id,name:product.name_ar||product.name_en||'منتج',image_url:product.image_url||'',variant,options,notes,unit_price:unit,qty});persistCart()}
function cartTotals(){return state.cart.reduce((a,x)=>({count:a.count+x.qty,total:a.total+x.unit_price*x.qty}),{count:0,total:0})}
function renderCartBar(){const t=cartTotals(),bar=$('#cartBar');bar.hidden=t.count===0;$('#cartCount').textContent=t.count;$('#cartTotal').textContent=money(t.total)}
function openCart(){renderCart();$('#cartDrawer').hidden=false;document.body.style.overflow='hidden'}
function closeCart(){if(!$('#cartDrawer').hidden){$('#cartDrawer').hidden=true;document.body.style.overflow=''}}
function renderCart(){const host=$('#cartItems'),t=cartTotals();host.innerHTML=state.cart.length?state.cart.map((x,i)=>`<div class="cart-item"><div class="cart-item-top"><div><h3>${safe(x.name)}</h3><div class="cart-custom">${x.variant?safe(x.variant.name):''}${x.options.length?(x.variant?' · ':'')+x.options.map(o=>safe(o.name)).join('، '):''}${x.notes?'<br>ملاحظة: '+safe(x.notes):''}</div></div><strong>${money(x.unit_price*x.qty)}</strong></div><div class="cart-item-actions"><div class="small-qty"><button data-inc="${i}">+</button><b>${x.qty}</b><button data-dec="${i}">−</button></div><button class="remove-btn" data-remove="${i}">حذف</button></div></div>`).join(''):'<div class="empty">السلة فارغة.</div>';$('#drawerTotal').textContent=money(t.total);$$('[data-inc]',host).forEach(b=>b.onclick=()=>changeQty(+b.dataset.inc,1));$$('[data-dec]',host).forEach(b=>b.onclick=()=>changeQty(+b.dataset.dec,-1));$$('[data-remove]',host).forEach(b=>b.onclick=()=>{state.cart.splice(+b.dataset.remove,1);persistCart()})}
function changeQty(i,d){const x=state.cart[i];if(!x)return;x.qty=Math.max(1,Math.min(99,x.qty+d));persistCart()}
boot();
