const M=window.MenuOwner,$=s=>document.querySelector(s);let ctx=null;
function card(label,value,sub=''){return `<div class="card stat"><b>${value}</b><span>${label}${sub?` · ${sub}`:''}</span></div>`}
function rows(data,labelKey,valueKey,format=v=>v){if(!data?.length)return '<div class="empty">لا توجد بيانات بعد.</div>';const max=Math.max(...data.map(x=>Number(x[valueKey]||0)),1);return data.map(x=>`<div style="margin-bottom:10px"><div class="inline" style="justify-content:space-between"><b style="font-size:11px">${M.safe(x[labelKey])}</b><span class="muted">${format(x[valueKey])}</span></div><div class="kpi-bar"><i style="width:${Math.max(2,Number(x[valueKey]||0)/max*100)}%"></i></div></div>`).join('')}
function typeLabel(t){return t==='delivery'?'توصيل':t==='takeaway'?'استلام':t==='dinein'?'داخل المطعم':t}
function sourceLabel(t){return t==='pos'?'POS':t==='phone'?'هاتف':'Online'}
function statusLabel(t){return M.statusLabel(t)}
function render(a){const s=a.summary||{},cur=a.currency||'EGP';$('#summary').innerHTML=card('عدد الطلبات',Number(s.orders_count||0).toLocaleString('ar-EG'))+card('الإيراد',M.money(s.revenue,cur))+card('متوسط الطلب',M.money(s.average_order,cur))+card('طلبات ملغية',Number(s.cancelled||0).toLocaleString('ar-EG'))+card('متوسط التجهيز',Number(s.avg_prep_minutes||0).toFixed(1),'دقيقة')+card('التوصيل',Number(s.avg_delivery_minutes||0).toFixed(1),'دقيقة')+card('التقييم',Number(s.rating||0).toFixed(1),'/ 5');
  const daily=a.daily||[],max=Math.max(...daily.map(x=>Number(x.revenue||0)),1);$('#daily').innerHTML=daily.length?daily.map(x=>`<div class="bar" style="height:${Math.max(4,Number(x.revenue||0)/max*100)}%" title="${M.money(x.revenue,cur)}"><span>${String(x.date||'').slice(5)}</span></div>`).join(''):'<div class="empty" style="width:100%">لا توجد مبيعات.</div>';
  $('#types').innerHTML=rows((a.order_types||[]).map(x=>({...x,label:typeLabel(x.type)})),'label','count',v=>v+' طلب');$('#sources').innerHTML=rows((a.order_sources||[]).map(x=>({...x,label:sourceLabel(x.source)})),'label','count',v=>v+' طلب');$('#products').innerHTML=rows(a.top_products||[],'name','quantity',v=>v+' قطعة');$('#statuses').innerHTML=rows((a.statuses||[]).map(x=>({...x,label:statusLabel(x.status)})),'label','count',v=>v+' طلب')}
async function load(){const days=Number($('#range').value||30),from=new Date(Date.now()-(days-1)*86400000);from.setHours(0,0,0,0);const r=await M.sb.rpc('cfy_menu_analytics',{p_token:ctx.key,p_from:from.toISOString(),p_to:new Date(Date.now()+1000).toISOString()});if(r.error){M.toast('تعذر تحميل التحليلات');return}render(r.data||{})}
(async()=>{try{ctx=await M.boot({ops:false});$('#refresh').onclick=load;$('#range').onchange=load;await load()}catch(e){document.querySelector('.ops-main').innerHTML='<div class="card error">تعذر فتح Analytics.</div>'}})();
