const M=window.MenuOwner;let ctx=null,ops=null,filter='active',seenPrints=new Set();
const $=s=>document.querySelector(s);
function itemsHtml(o){return (o.items||[]).map(i=>{const s=i.snapshot||{},p=s.product||{},v=s.variant,os=s.options||[];return `<div class="item"><b>${i.quantity} × ${M.safe(p.name_ar||p.name_en||'منتج')}</b>${v||os.length||s.notes?`<small>${v?'الحجم: '+M.safe(v.name):''}${os.length?' · '+os.map(x=>M.safe(x.name)).join('، '):''}${s.notes?' · '+M.safe(s.notes):''}</small>`:''}</div>`}).join('')}
function isVisible(o){if(filter==='all')return true;if(filter==='active')return !['completed','cancelled'].includes(o.status);return o.status===filter||o.order_type===filter||o.order_source===filter}
function actionsHtml(o){let h='';if(o.status==='new')h+=`<button class="btn" data-act="accept" data-id="${o.id}">تم استلام الطلب</button>`;if(o.status==='preparing')h+=`<button class="btn ok" data-act="ready" data-id="${o.id}">تم التجهيز</button>`;if(o.status==='ready'&&o.order_type!=='delivery')h+=`<button class="btn ok" data-act="complete" data-id="${o.id}">مكتمل</button>`;if(o.status==='ready'&&o.order_type==='delivery'){const drivers=(ops.staff||[]).filter(s=>s.role==='delivery'&&s.enabled&&s.shift_state==='available');h+=`<select class="filter-select" id="driver-${o.id}"><option value="">اقتراح تلقائي</option>${drivers.map(d=>`<option value="${d.id}" ${o.assigned_driver_id===d.id?'selected':''}>${M.safe(d.name)} · ${d.active_deliveries||0} طلب</option>`).join('')}</select><button class="btn" data-act="assign_driver" data-id="${o.id}">إسناد مندوب</button>`}if(o.status==='on_the_way')h+=`<button class="btn ok" data-act="delivered" data-id="${o.id}">تأكيد التوصيل بالرمز</button>`;if(o.status==='delivered')h+=`<button class="btn ok" data-act="complete" data-id="${o.id}">إغلاق كمكتمل</button>`;if(!['completed','cancelled','delivered'].includes(o.status))h+=`<button class="btn danger" data-act="cancel" data-id="${o.id}">إلغاء</button>`;h+=`<button class="btn secondary" data-print="kitchen" data-id="${o.id}">طباعة مطبخ</button><button class="btn secondary" data-print="cashier" data-id="${o.id}">إيصال</button><button class="btn secondary" data-issue data-id="${o.id}">${o.issue_open?'تحديث المشكلة':'تسجيل مشكلة'}</button>`;return h}
function render(){const orders=(ops.orders||[]).filter(isVisible);const all=ops.orders||[];$('#stats').innerHTML=`<div class="card stat"><b>${all.filter(x=>x.status==='new').length}</b><span>طلبات جديدة</span></div><div class="card stat"><b>${all.filter(x=>['preparing','ready'].includes(x.status)).length}</b><span>قيد التشغيل</span></div><div class="card stat"><b>${all.filter(x=>x.order_type==='delivery'&&['ready','on_the_way'].includes(x.status)).length}</b><span>توصيل نشط</span></div>`;
  const fs=[['active','نشطة'],['new','جديدة'],['preparing','تجهيز'],['ready','جاهزة'],['delivery','توصيل'],['dinein','داخل المطعم'],['pos','POS'],['online','Online'],['completed','مكتملة'],['cancelled','ملغية'],['all','الكل']];$('#filters').innerHTML=fs.map(([v,l])=>`<button class="${filter===v?'active':''}" data-filter="${v}">${l}</button>`).join('');$('#filters').querySelectorAll('button').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;render()});
  $('#orders').innerHTML=orders.length?orders.map(o=>`<div class="order-card ${o.issue_open?'issue':''}"><div class="order-head"><div><div class="order-ref">${M.safe(o.reference)}</div><div class="order-meta">${M.orderSource(o.order_source)} · ${M.orderType(o.order_type)}${o.table_number?' · ترابيزة '+M.safe(o.table_number):''}${o.driver_name?' · '+M.safe(o.driver_name):''} · ${new Date(o.created_at).toLocaleString('ar-EG')}</div></div><span class="status ${o.status}">${M.statusLabel(o.status)}</span></div><div class="order-body"><div class="items">${itemsHtml(o)}${o.customer_name?`<div class="order-meta">العميل: ${M.safe(o.customer_name)} ${o.phone?'· '+M.safe(o.phone):''}</div>`:''}${o.address?`<div class="order-meta">${M.safe(o.address)}</div>`:''}${o.issue_open?`<div class="error notice">مشكلة: ${M.safe(o.issue_text)}</div>`:''}</div><div class="money">${M.money(o.total,ops.settings?.currency)}</div></div><div class="order-actions">${actionsHtml(o)}</div></div>`).join(''):'<div class="empty">لا توجد طلبات في الفلتر الحالي.</div>';
  bindActions();renderTables();renderPrints();autoPrintPending()}
function bindActions(){$('#orders').querySelectorAll('[data-act]').forEach(b=>b.onclick=()=>act(b.dataset.id,b.dataset.act));$('#orders').querySelectorAll('[data-print]').forEach(b=>b.onclick=()=>{const o=(ops.orders||[]).find(x=>x.id===b.dataset.id);if(o)printOrder(o,b.dataset.print)});$('#orders').querySelectorAll('[data-issue]').forEach(b=>b.onclick=()=>issue(b.dataset.id))}
async function act(id,action){let data={};if(action==='assign_driver')data.driver_id=document.getElementById('driver-'+id)?.value||'';if(action==='delivered'){const otp=prompt('أدخل رمز التسليم المكون من 6 أرقام');if(otp===null)return;data.otp=otp}if(action==='cancel'){const reason=prompt('سبب الإلغاء (اختياري)');if(reason===null)return;data.reason=reason}const r=await M.sb.rpc('cfy_menu_owner_order_action',{p_token:ctx.key,p_order_id:id,p_action:action,p_data:data});if(r.error){M.toast('تعذر التنفيذ: '+r.error.message);return}M.toast('تم تحديث الطلب');await reload()}
async function issue(id){const o=(ops.orders||[]).find(x=>x.id===id);if(o?.issue_open&&confirm('هل تريد إغلاق المشكلة الحالية؟')){await act(id,'resolve_issue');return}const text=prompt('اكتب وصف المشكلة');if(!text)return;const r=await M.sb.rpc('cfy_menu_owner_order_action',{p_token:ctx.key,p_order_id:id,p_action:'issue',p_data:{text}});if(r.error)M.toast('تعذر تسجيل المشكلة');else{M.toast('تم تسجيل المشكلة');await reload()}}
function renderTables(){const host=$('#tables'),tables=ops.tables||[];host.innerHTML=tables.length?tables.map(t=>{const s=t.session,state=s?.status||'available';return `<div class="table-card"><b>${M.safe(t.label)}</b><div class="table-state ${state}">${state==='available'?'متاحة':state==='open'?'مشغولة':state==='bill_requested'?'طلب الحساب':state==='payment_pending'?'في انتظار الدفع':state}</div>${s?`<div class="order-meta">الإجمالي: ${M.money(s.running_total,ops.settings?.currency)}</div><div class="order-actions">${state!=='payment_pending'?`<button class="btn warn" data-table-action="payment_pending" data-session="${s.id}">بدء الدفع</button>`:''}<button class="btn ok" data-table-action="close_paid" data-session="${s.id}">تم الدفع وإغلاق الترابيزة</button></div>`:''}</div>`}).join(''):'<div class="empty">لم تتم إضافة ترابيزات بعد.</div>';host.querySelectorAll('[data-table-action]').forEach(b=>b.onclick=()=>tableAction(b.dataset.session,b.dataset.tableAction))}
async function tableAction(session,action){if(action==='close_paid'&&!confirm('تأكيد الدفع وإغلاق حساب الترابيزة؟'))return;const r=await M.sb.rpc('cfy_menu_owner_table_action',{p_token:ctx.key,p_session_id:session,p_action:action});if(r.error)M.toast('تعذر تحديث الترابيزة');else{M.toast('تم تحديث الترابيزة');await reload()}}
function renderPrints(){const jobs=ops.print_jobs||[];$('#prints').innerHTML=jobs.length?jobs.slice(0,20).map(j=>`<div class="order-card"><div class="order-head"><div><b>${j.job_type==='kitchen'?'تذكرة مطبخ':j.job_type==='cashier'?'إيصال كاشير':'اختبار طباعة'}</b><div class="order-meta">${new Date(j.created_at).toLocaleString('ar-EG')}</div></div><span class="status ${j.status==='failed'?'cancelled':j.status==='printed'?'completed':'new'}">${j.status==='pending'?'بانتظار الطباعة':j.status==='printed'?'تمت الطباعة':'فشلت'}</span></div>${j.last_error?`<div class="order-meta">${M.safe(j.last_error)}</div>`:''}<div class="order-actions"><button class="btn secondary" data-job-print="${j.id}">طباعة</button></div></div>`).join(''):'<div class="empty">لا توجد مهام طباعة.</div>';$('#prints').querySelectorAll('[data-job-print]').forEach(b=>b.onclick=()=>{const j=jobs.find(x=>x.id===b.dataset.jobPrint);if(j)printJob(j)})}
function ticketHtml(payload,type){const o=payload||{},items=o.items||[];const title=type==='kitchen'?'KITCHEN TICKET':'RECEIPT';return `<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><title>${title}</title><style>body{font-family:Arial,sans-serif;width:72mm;margin:0 auto;padding:4mm;font-size:12px}h2{text-align:center}.line{border-top:1px dashed #000;margin:8px 0}.item{margin:6px 0}.muted{font-size:10px}.total{font-size:16px;font-weight:bold;text-align:center}</style></head><body><h2>${title}</h2><div>${M.safe(o.reference||'')}</div><div>${M.orderType(o.order_type||'')} ${o.table_number?'· '+M.safe(o.table_number):''}</div><div class="line"></div>${items.map(i=>{const s=i.snapshot||{},p=s.product||{},v=s.variant,opts=s.options||[];return `<div class="item"><b>${i.quantity} × ${M.safe(p.name_ar||p.name_en||'منتج')}</b><div class="muted">${v?M.safe(v.name):''} ${opts.map(x=>M.safe(x.name)).join('، ')} ${s.notes?'<br>'+M.safe(s.notes):''}</div></div>`}).join('')}<div class="line"></div>${type==='cashier'?`<div class="total">${M.money(o.total||0,ops.settings?.currency)}</div>`:''}<script>window.onload=()=>{window.print();setTimeout(()=>window.close(),500)}<\/script></body></html>`}
async function printOrder(o,type){const w=window.open('','_blank','width=480,height=720');if(!w){M.toast('المتصفح منع نافذة الطباعة. اسمح بالنوافذ المنبثقة ثم أعد المحاولة.');return false}w.document.write(ticketHtml(o,type));w.document.close();return true}
async function printJob(j){const ok=printOrder(j.payload||{},j.job_type);const r=await M.sb.rpc('cfy_menu_mark_print_job',{p_token:ctx.key,p_job_id:j.id,p_status:ok?'printed':'failed',p_error:ok?'':'popup_blocked'});if(r.error)M.toast('تم فتح الطباعة لكن تعذر تحديث حالتها.');await reload()}
async function autoPrintPending(){if(!ops.settings?.auto_print_kitchen||!ops.settings?.kitchen_printer_enabled)return;for(const j of (ops.print_jobs||[]).filter(x=>x.status==='pending'&&x.job_type==='kitchen')){if(seenPrints.has(j.id))continue;seenPrints.add(j.id);await printJob(j);break}}
async function reload(){const r=await M.sb.rpc('cfy_menu_operational_snapshot',{p_token:ctx.key,p_limit:200});if(r.error){M.toast('تعذر تحديث الطلبات');return}ops=r.data||{};render()}
(async()=>{try{ctx=await M.boot({ops:true});ops=ctx.ops;render();$('#refresh').onclick=reload;setInterval(reload,20000)}catch(e){document.querySelector('.ops-main').innerHTML='<div class="card error">تعذر فتح مركز الطلبات.</div>'}})();