const M=window.MenuOwner,$=s=>document.querySelector(s);let ctx=null,ops=null;const days=['الأحد','الإثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت'];
function renderTabs(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.tab-panel').forEach(p=>p.hidden=p.id!==b.dataset.tab)})}
// Render payment fields only when the settings form is loaded/refreshed.
function renderPaymentMethods(){
  const card=document.querySelector('#general > .card');if(!card)return;
  let box=document.getElementById('paymentMethodsBox');
  if(!box){box=document.createElement('div');box.id='paymentMethodsBox';box.className='card';box.style.marginTop='12px';card.appendChild(box)}
  const labels={cash:'كاش',card_at_venue:'بطاقة عند المطعم',pay_on_delivery:'الدفع عند الاستلام'};
  const enabled=Array.isArray(ops.settings?.payment_methods)?ops.settings.payment_methods:Object.keys(labels);
  box.innerHTML='<b>طرق الدفع المفعّلة</b><div class="grid2" style="margin-top:8px">'+Object.entries(labels).map(([v,l])=>`<label class="card"><input type="checkbox" data-pay-method="${v}" ${enabled.includes(v)?'checked':''}> ${l}</label>`).join('')+'</div><div class="muted">Online Payment غير مفعّل في الديمو.</div>';
}
function renderGeneral(){renderPaymentMethods();const s=ops.settings||{};$('#restaurantOpen').value=String(s.restaurant_open!==false);$('#timezone').value=s.timezone||'Africa/Cairo';$('#prep').value=s.average_prep_minutes??30;$('#advance').value=s.max_advance_days??7;$('#scheduled').checked=!!s.scheduled_ordering_enabled;$('#tracking').checked=s.tracking_enabled!==false;$('#otp').checked=s.otp_enabled!==false;$('#asap').checked=s.asap_enabled!==false;const h=s.opening_hours||{};$('#hours').innerHTML=days.map((d,i)=>{const x=h[String(i)]||{enabled:false,start:'09:00',end:'23:00'};return `<div class="card inline"><label style="min-width:72px"><input type="checkbox" data-day-enable="${i}" ${x.enabled?'checked':''}> ${d}</label><input type="time" data-day-start="${i}" value="${x.start||'09:00'}"><span>إلى</span><input type="time" data-day-end="${i}" value="${x.end||'23:00'}"></div>`}).join('')}
function hoursPayload(){const o={};days.forEach((_,i)=>{o[String(i)]={enabled:$(`[data-day-enable="${i}"]`).checked,start:$(`[data-day-start="${i}"]`).value||'09:00',end:$(`[data-day-end="${i}"]`).value||'23:00'}});return o}
async function saveGeneral(){const payload={payment_methods:[...document.querySelectorAll('[data-pay-method]:checked')].map(x=>x.dataset.payMethod),restaurant_open:$('#restaurantOpen').value==='true',timezone:$('#timezone').value.trim(),average_prep_minutes:Number($('#prep').value||30),max_advance_days:Number($('#advance').value||7),scheduled_ordering_enabled:$('#scheduled').checked,tracking_enabled:$('#tracking').checked,otp_enabled:$('#otp').checked,asap_enabled:$('#asap').checked,opening_hours:hoursPayload()};$('#generalStatus').textContent='جاري الحفظ...';const r=await M.sb.rpc('cfy_menu_save_operational_settings',{p_token:ctx.key,p_data:payload});if(r.error){$('#generalStatus').textContent='تعذر الحفظ: '+r.error.message;return}ops.settings={...ops.settings,...r.data};$('#generalStatus').textContent='تم الحفظ'}
function renderTables(){const list=ops.tables||[];$('#tablesList').innerHTML=list.length?list.map(t=>{const state=t.session?.status||'available',url=location.origin+'/menu/?code='+encodeURIComponent(ctx.session.client.code)+'&table='+encodeURIComponent(t.public_key);return `<div class="table-card"><b>${M.safe(t.label)}</b><div class="table-state ${state}">${state==='available'?'متاحة':state==='open'?'مشغولة':state==='bill_requested'?'طلب الحساب':'في انتظار الدفع'}</div><div class="order-meta">QR ثابت</div><input readonly dir="ltr" value="${M.safe(url)}" style="width:100%;margin-top:6px;border:1px solid #e5e7ec;border-radius:8px;padding:6px;font-size:8px"><div class="order-actions"><button class="btn secondary" data-copy="${M.safe(url)}">نسخ QR Link</button><button class="btn secondary" data-edit-table="${t.id}">تعديل</button><button class="btn secondary" data-rotate="${t.id}">تغيير QR</button><button class="btn danger" data-del-table="${t.id}">حذف</button></div></div>`}).join(''):'<div class="empty">أضف الترابيزات إذا كنت تستخدم Dine-in.</div>';$('#tablesList').querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{await navigator.clipboard.writeText(b.dataset.copy);M.toast('تم نسخ الرابط')});$('#tablesList').querySelectorAll('[data-edit-table]').forEach(b=>b.onclick=()=>tableModal(list.find(x=>x.id===b.dataset.editTable)));$('#tablesList').querySelectorAll('[data-rotate]').forEach(b=>b.onclick=()=>rotateTable(b.dataset.rotate));$('#tablesList').querySelectorAll('[data-del-table]').forEach(b=>b.onclick=()=>deleteTable(b.dataset.delTable))}
function modal(html){$('#modalBody').innerHTML=html;$('#modal').hidden=false;$('#modal').onclick=e=>{if(e.target===$('#modal'))$('#modal').hidden=true}}
function closeModal(){$('#modal').hidden=true}
function tableModal(t=null){modal(`<h3>${t?'تعديل':'إضافة'} ترابيزة</h3><div class="field"><label>اسم / رقم الترابيزة</label><input id="mTableLabel" maxlength="80" value="${M.safe(t?.label||'')}"></div><label style="display:block;margin-top:10px"><input id="mTableEnabled" type="checkbox" ${t?.enabled!==false?'checked':''}> مفعّلة</label><div class="actions" style="margin-top:14px"><button id="saveTable" class="btn">حفظ</button><button id="cancelModal" class="btn secondary">إلغاء</button></div>`);$('#cancelModal').onclick=closeModal;$('#saveTable').onclick=async()=>{const r=await M.sb.rpc('cfy_menu_tables_manage',{p_token:ctx.key,p_action:'upsert',p_data:{id:t?.id||'',label:$('#mTableLabel').value.trim(),enabled:$('#mTableEnabled').checked,sort_order:t?.sort_order||0}});if(r.error){M.toast('تعذر حفظ الترابيزة: '+r.error.message);return}closeModal();await reload();M.toast('تم حفظ الترابيزة')}}
async function rotateTable(id){if(!confirm('تغيير QR سيجعل الرابط القديم غير صالح. متابعة؟'))return;const r=await M.sb.rpc('cfy_menu_tables_manage',{p_token:ctx.key,p_action:'rotate_qr',p_data:{id}});if(r.error)M.toast('تعذر تغيير QR');else{await reload();M.toast('تم إنشاء QR جديد')}}
async function deleteTable(id){if(!confirm('حذف الترابيزة؟'))return;const r=await M.sb.rpc('cfy_menu_tables_manage',{p_token:ctx.key,p_action:'delete',p_data:{id}});if(r.error)M.toast('تعذر الحذف: '+r.error.message);else{await reload();M.toast('تم الحذف')}}
function renderStaff(){const list=ops.staff||[];const role={cashier:'كاشير',coordinator:'محضّر الطلب',delivery:'توصيل'};$('#staffList').innerHTML=list.length?list.map(s=>`<div class="order-card"><div class="order-head"><div><b>${M.safe(s.name)}</b><div class="order-meta">${M.safe(s.code)} · ${role[s.role]||s.role}${s.role==='delivery'?` · ${s.shift_state==='available'?'متاح':s.shift_state==='paused'?'متوقف مؤقتًا':'خارج الشيفت'} · ${s.active_deliveries||0} طلب`:''}</div></div><span class="status ${s.enabled?'completed':'cancelled'}">${s.enabled?'مفعّل':'موقوف'}</span></div><div class="order-actions"><button class="btn secondary" data-edit-staff="${s.id}">تعديل / PIN</button><button class="btn danger" data-del-staff="${s.id}">حذف</button></div></div>`).join(''):'<div class="empty">لم تتم إضافة موظفين بعد.</div>';$('#staffList').querySelectorAll('[data-edit-staff]').forEach(b=>b.onclick=()=>staffModal(list.find(x=>x.id===b.dataset.editStaff)));$('#staffList').querySelectorAll('[data-del-staff]').forEach(b=>b.onclick=()=>deleteStaff(b.dataset.delStaff))}
function staffModal(s=null){modal(`<h3>${s?'تعديل موظف':'إضافة موظف'}</h3><div class="form-grid"><div class="field"><label>الاسم</label><input id="mStaffName" maxlength="120" value="${M.safe(s?.name||'')}"></div><div class="field"><label>كود الدخول</label><input id="mStaffCode" maxlength="30" dir="ltr" value="${M.safe(s?.code||'')}"></div><div class="field"><label>الدور</label><select id="mStaffRole"><option value="cashier">كاشير</option><option value="coordinator">محضّر الطلب</option><option value="delivery">توصيل</option></select></div><div class="field"><label>${s?'PIN جديد (اتركه فارغًا بدون تغيير)':'PIN — 4 أرقام على الأقل'}</label><input id="mStaffPin" type="password" inputmode="numeric" minlength="4"></div></div><label style="display:block;margin-top:10px"><input id="mStaffEnabled" type="checkbox" ${s?.enabled!==false?'checked':''}> مفعّل</label><div class="actions" style="margin-top:14px"><button id="saveStaff" class="btn">حفظ</button><button id="cancelModal" class="btn secondary">إلغاء</button></div>`);$('#mStaffRole').value=s?.role||'cashier';$('#cancelModal').onclick=closeModal;$('#saveStaff').onclick=async()=>{const p={id:s?.id||'',name:$('#mStaffName').value.trim(),code:$('#mStaffCode').value.trim(),role:$('#mStaffRole').value,pin:$('#mStaffPin').value,enabled:$('#mStaffEnabled').checked};const r=await M.sb.rpc('cfy_menu_staff_manage',{p_token:ctx.key,p_action:'upsert',p_data:p});if(r.error){M.toast('تعذر الحفظ: '+r.error.message);return}closeModal();await reload();M.toast('تم حفظ الموظف')}}
async function deleteStaff(id){if(!confirm('حذف الموظف وإلغاء جلساته؟'))return;const r=await M.sb.rpc('cfy_menu_staff_manage',{p_token:ctx.key,p_action:'delete',p_data:{id}});if(r.error)M.toast('تعذر الحذف');else{await reload();M.toast('تم الحذف')}}
function renderPrint(){const s=ops.settings||{};$('#kitchenPrinter').checked=!!s.kitchen_printer_enabled;$('#cashierPrinter').checked=!!s.cashier_printer_enabled;$('#autoKitchen').checked=!!s.auto_print_kitchen;$('#copies').value=s.print_copies||1}
async function savePrint(){const p={kitchen_printer_enabled:$('#kitchenPrinter').checked,cashier_printer_enabled:$('#cashierPrinter').checked,auto_print_kitchen:$('#autoKitchen').checked,print_copies:Number($('#copies').value||1)};$('#printStatus').textContent='جاري الحفظ...';const r=await M.sb.rpc('cfy_menu_save_operational_settings',{p_token:ctx.key,p_data:p});if(r.error)$('#printStatus').textContent='تعذر الحفظ';else{$('#printStatus').textContent='تم الحفظ';ops.settings={...ops.settings,...r.data}}}
function testPrint(){const w=window.open('','_blank','width=420,height=600');if(!w){M.toast('اسمح بالنوافذ المنبثقة للطباعة');return}w.document.write('<html lang="ar" dir="rtl"><body style="font-family:Arial;width:72mm;margin:auto"><h2>CARDfy Test Print</h2><p>إذا ظهرت هذه الورقة فـ Browser Print يعمل.</p><hr><p>'+new Date().toLocaleString('ar-EG')+'</p><script>window.onload=()=>window.print()<\/script></body></html>');w.document.close()}
async function reload(){const r=await M.sb.rpc('cfy_menu_operational_snapshot',{p_token:ctx.key,p_limit:100});if(r.error){M.toast('تعذر التحديث');return}ops=r.data||{};renderGeneral();renderTables();renderStaff();renderPrint()}
(async()=>{try{ctx=await M.boot({ops:true});ops=ctx.ops;renderTabs();renderGeneral();renderTables();renderStaff();renderPrint();$('#saveGeneral').onclick=saveGeneral;$('#addTable').onclick=()=>tableModal();$('#addStaff').onclick=()=>staffModal();$('#savePrint').onclick=savePrint;$('#testPrint').onclick=testPrint;$('#refresh').onclick=reload}catch(e){document.querySelector('.ops-main').innerHTML='<div class="card error">تعذر فتح الإعدادات.</div>'}})();
